import {createHash} from 'node:crypto';
import {gzipSync,gunzipSync} from 'node:zlib';
import {existsSync,readdirSync,readFileSync,writeFileSync,mkdirSync,rmSync,renameSync,lstatSync} from 'node:fs';
import path from 'node:path';

const roots=['omega.sqlite','omega.sqlite-wal','omega.sqlite-shm','automations.sqlite','automations.sqlite-wal','automations.sqlite-shm','read-state.sqlite','read-state.sqlite-wal','read-state.sqlite-shm','search.sqlite','search.sqlite-wal','search.sqlite-shm','submissions.json','turn-metrics','model-settings','images','pasted-text'];
interface Archive{format:'omega-backup';version:1;createdAt:string;files:{path:string,size:number,sha256:string,data:string}[]}
function files(root:string,relative:string):string[]{const full=path.join(root,relative);if(!existsSync(full))return[];const entries=readdirSync(full,{withFileTypes:true});return entries.flatMap(entry=>entry.isSymbolicLink()?[]:entry.isDirectory()?files(root,path.join(relative,entry.name)):[path.join(relative,entry.name)]);}
function safeRelative(value:string){if(!value||path.isAbsolute(value)||value.split(path.sep).includes('..')||!roots.some(root=>value===root||value.startsWith(root+path.sep)))throw new Error('备份包含不允许的路径');return value;}
export function createBackup(state:string){const names=roots.flatMap(root=>{const full=path.join(state,root);if(!existsSync(full))return[];const info=lstatSync(full);if(info.isSymbolicLink())return[];return info.isDirectory()?files(state,root):[root];});const unique=[...new Set(names)];let total=0;const archive:Archive={format:'omega-backup',version:1,createdAt:new Date().toISOString(),files:unique.map(relative=>{const data=readFileSync(path.join(state,relative));total+=data.length;if(total>250*1024*1024)throw new Error('备份数据超过 250 MB，请先清理过期附件');return{path:relative,size:data.length,sha256:createHash('sha256').update(data).digest('hex'),data:data.toString('base64')}})};return gzipSync(JSON.stringify(archive),{level:6});}
export function validateBackup(input:Buffer){if(input.length>260*1024*1024)throw new Error('备份文件过大');let archive:Archive;try{archive=JSON.parse(gunzipSync(input,{maxOutputLength:350*1024*1024}).toString())}catch{throw new Error('不是有效的 Omega 备份文件');}if(archive.format!=='omega-backup'||archive.version!==1||!Array.isArray(archive.files)||archive.files.length>10000)throw new Error('Omega 备份格式或版本不受支持');let total=0;for(const file of archive.files){safeRelative(file.path);const data=Buffer.from(file.data,'base64');total+=data.length;if(data.length!==file.size||createHash('sha256').update(data).digest('hex')!==file.sha256)throw new Error(`备份文件校验失败：${file.path}`);if(total>250*1024*1024)throw new Error('备份展开后超过 250 MB');}return archive;}
export function stageRestore(state:string,input:Buffer){const archive=validateBackup(input);writeFileSync(path.join(state,'.restore-pending.tmp'),input,{mode:0o600});renameSync(path.join(state,'.restore-pending.tmp'),path.join(state,'.restore-pending'));return{createdAt:archive.createdAt,files:archive.files.length,restartRequired:true};}
export function applyPendingRestore(state:string){const pending=path.join(state,'.restore-pending');if(!existsSync(pending))return null;const archive=validateBackup(readFileSync(pending));for(const root of roots)rmSync(path.join(state,root),{recursive:true,force:true});for(const file of archive.files){const relative=safeRelative(file.path),target=path.join(state,relative);mkdirSync(path.dirname(target),{recursive:true,mode:0o700});writeFileSync(target,Buffer.from(file.data,'base64'),{mode:0o600});}rmSync(pending,{force:true});return{createdAt:archive.createdAt,files:archive.files.length};}
