import {MAX_MESSAGE_TEXT_FILES} from '../shared/attachment-limits.ts';
import {validateMentions} from './member-mentions.ts';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import {validateBudget} from './collaboration-budget.ts';

const now=()=>new Date().toISOString();
type Row=Record<string,any>;
interface Statement{all(...values:any[]):Row[];get(...values:any[]):Row|undefined;run(...values:any[]):{changes:number}}
interface StoreDb{exec(sql:string):void;prepare(sql:string):Statement;close():void}
const json=(value:any)=>JSON.stringify(value??null);
const parse=(value:any,fallback:any=null):any=>{try{return value==null||value===''?fallback:JSON.parse(value);}catch{return fallback;}};
const clean=(value:any,name:string,max=4000,required=false):string=>{value=typeof value==='string'?value.trim():value==null?'':null;if(value==null||value.length>max||/\u0000/.test(value))throw new Error(`${name}格式不正确或过长`);if(required&&!value)throw new Error(`请填写${name}`);return value;};
const cleanAvatar=(value:any)=>{value=clean(value,'头像',100000);if(!value||/^preset:(?:developer|designer|tester|analyst|operator|coordinator)$/.test(value)||/^data:image\/(?:png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(value))return value;throw new Error('头像格式不正确');};
const cleanPastes=(value:any)=>{if(value==null)return[];if(!Array.isArray(value)||value.length>MAX_MESSAGE_TEXT_FILES)throw new Error('粘贴文本引用格式不正确');return value.map(item=>{if(!item||typeof item.id!=='string'||!Number.isInteger(item.chars)||item.chars<1||!Number.isInteger(item.bytes)||item.bytes<1)throw new Error('粘贴文本引用格式不正确');return{id:item.id,chars:item.chars,bytes:item.bytes,createdAt:item.createdAt,expiresAt:item.expiresAt};});};
const overlap=(a:string,b:string)=>{const left=path.resolve(a),right=path.resolve(b);return left===right||left.startsWith(right+path.sep)||right.startsWith(left+path.sep);};
const accessMode=(value:any,title='',objective='')=>{if(value==='read'||value==='write')return value;const content=`${title} ${objective}`;const writes=/修改|实现|开发|修复|新增|创建|删除|写入|更新(?:代码|文件|配置|依赖|数据库|实现)|升级|安装|部署|构建|提交|合并|重构|配置|生成|落地|编码|改造|write|edit|implement|develop|fix|create|delete|update\s+(?:code|files?|config|dependencies|database|implementation)|install|deploy|build|commit|merge|refactor/i,reads=/查询|统计|筛选|复核|审核|分析|调研|检查|核对|盘点|汇总|阅读|查看|确认|检索|query|search|review|audit|analy[sz]e|inspect|check|read|research|summari[sz]e/i;return reads.test(content)&&!writes.test(content)?'read':'write';};
const workspaceConflict=(leftMode:string,rightMode:string)=>leftMode!=='read'||rightMode!=='read';
const terminal=new Set(['completed','accepted','cancelled']);
const groupStatusPriority=['running','finalizing','plan_drafting','awaiting_confirmation','awaiting_acceptance','paused'];

export const GROUP_LIMITS=Object.freeze({maxTasks:8,maxReworks:2,maxRounds:12,taskTimeoutMinutes:45,maxConcurrency:3});

export class GroupStore{
  externalQueueReason:(task:Row)=>string|null=()=>null;
  db:StoreDb;closed=false;
  constructor(file:string){this.db=new DatabaseSync(file) as StoreDb;this.db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');this.migrate();}
  migrate(){
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS group_topic_reads(member_id TEXT NOT NULL,thread_id TEXT NOT NULL,topic_id TEXT NOT NULL,cursor INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(member_id,thread_id,topic_id));
      CREATE TABLE IF NOT EXISTS groups(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',cwd TEXT NOT NULL,constraints_text TEXT NOT NULL DEFAULT '',coordinator_thread_id TEXT NOT NULL,summary TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'idle',limits_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS group_members(id TEXT PRIMARY KEY,group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,thread_id TEXT NOT NULL UNIQUE,name TEXT NOT NULL,role TEXT NOT NULL,responsibilities TEXT NOT NULL DEFAULT '',operations TEXT NOT NULL DEFAULT '',skills TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS requirements(id TEXT PRIMARY KEY,group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,content TEXT NOT NULL,acceptance TEXT NOT NULL DEFAULT '',status TEXT NOT NULL,plan_json TEXT,delivery TEXT,coordinator_turn_id TEXT,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,requirement_id TEXT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,position INTEGER NOT NULL,member_id TEXT NOT NULL REFERENCES group_members(id),title TEXT NOT NULL,objective TEXT NOT NULL,acceptance TEXT NOT NULL DEFAULT '',dependencies_json TEXT NOT NULL DEFAULT '[]',cwd TEXT NOT NULL DEFAULT '',access_mode TEXT NOT NULL DEFAULT '',status TEXT NOT NULL,dispatch_id TEXT UNIQUE,turn_id TEXT,result TEXT,error TEXT,attempt INTEGER NOT NULL DEFAULT 0,started_at TEXT,completed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS group_messages(id TEXT PRIMARY KEY,group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,requirement_id TEXT REFERENCES requirements(id) ON DELETE CASCADE,kind TEXT NOT NULL,author TEXT NOT NULL,content TEXT NOT NULL,reference_json TEXT,created_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS group_messages_group_idx ON group_messages(group_id,created_at);
      CREATE INDEX IF NOT EXISTS tasks_requirement_idx ON tasks(requirement_id,position);
      CREATE INDEX IF NOT EXISTS tasks_status_idx ON tasks(status,member_id);
      CREATE INDEX IF NOT EXISTS requirements_group_idx ON requirements(group_id,created_at);
      CREATE TABLE IF NOT EXISTS discussion_reports(requirement_id TEXT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,round_no INTEGER NOT NULL,status TEXT NOT NULL,dispatch_id TEXT,turn_id TEXT,report_json TEXT,error TEXT,PRIMARY KEY(requirement_id,round_no));
    `);
    this.addColumn('group_members','cwd',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('group_members','project_name',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('group_members','avatar',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('tasks','cwd',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('tasks','access_mode',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('tasks','deadline_at','TEXT');
    this.addColumn('tasks','recovery_checked_at','TEXT');
    this.addColumn('tasks','decision_json','TEXT');
    this.addColumn('tasks','round_no','INTEGER NOT NULL DEFAULT 1');
    this.addColumn('requirements','collaboration_mode',"TEXT NOT NULL DEFAULT 'direct'");
    this.addColumn('requirements','max_rounds','INTEGER NOT NULL DEFAULT 3');
    this.addColumn('requirements','reply_task_id','TEXT');
    this.addColumn('requirements','images_json',"TEXT NOT NULL DEFAULT '[]'");
    this.addColumn('requirements','pastes_json',"TEXT NOT NULL DEFAULT '[]'");
    this.addColumn('requirements','mentions_json',"TEXT NOT NULL DEFAULT '[]'");
    this.db.exec("UPDATE requirements SET status='completed' WHERE status='awaiting_acceptance';");
    this.db.exec("UPDATE group_members SET cwd=(SELECT cwd FROM groups WHERE groups.id=group_members.group_id) WHERE cwd='';UPDATE tasks SET cwd=(SELECT cwd FROM group_members WHERE group_members.id=tasks.member_id) WHERE cwd='';");
    const unknownModes=this.db.prepare("SELECT id,title,objective FROM tasks WHERE access_mode='' OR access_mode IS NULL").all(),setMode=this.db.prepare('UPDATE tasks SET access_mode=? WHERE id=?');for(const task of unknownModes)setMode.run(accessMode('',task.title,task.objective),task.id);
    this.addColumn('requirements','budget_json',"TEXT NOT NULL DEFAULT '{}'");
    this.addColumn('requirements','budget_started_at','TEXT');
    this.addColumn('requirements','pause_kind','TEXT');
    this.db.exec("UPDATE requirements SET pause_kind=CASE WHEN error LIKE '已达到%' THEN 'budget' ELSE 'execution' END WHERE status='paused' AND pause_kind IS NULL");
    this.db.exec('CREATE TABLE IF NOT EXISTS group_turn_usage(requirement_id TEXT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,turn_id TEXT NOT NULL,thread_id TEXT NOT NULL,tokens INTEGER,PRIMARY KEY(thread_id,turn_id))');
    this.recoverInterrupted();this.repairKnownThreadFailures();this.refreshAllStatuses();
  }
  addColumn(table:string,column:string,type:string){try{this.db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${type}`);}catch(error){if(!/duplicate column/i.test((error as Error).message))throw error;}}
  recoverInterrupted(){const stamp=now();this.db.prepare("UPDATE tasks SET status='unknown',recovery_checked_at=NULL,error=COALESCE(error,'服务重启时任务仍在执行，正在核对原执行轮次'),updated_at=? WHERE status='running'").run(stamp);this.db.prepare("UPDATE requirements SET status='paused',pause_kind=COALESCE(pause_kind,'recovery'),error=COALESCE(error,'服务重启后正在核对未完成流程'),updated_at=? WHERE status IN ('plan_drafting','finalizing') OR id IN (SELECT requirement_id FROM tasks WHERE status='unknown')").run(stamp);}
  repairKnownThreadFailures(){const rows=this.db.prepare("SELECT id FROM tasks WHERE status='unknown' AND (lower(error) LIKE 'thread not found:%' OR lower(error) LIKE '%missing source rollout%' OR lower(error) LIKE '%does not exist%')").all();for(const row of rows)this.failTask(row.id,'成员会话不存在或已无法恢复，请编辑该成员并更换关联会话后重试','failed');}
  close(){if(this.closed)return;this.closed=true;this.db.close();}
  roomWindow(groupId:string,{after,question}:{after?:string|null;question?:string|null}={}){
    const cursor=question?this.db.prepare('SELECT rowid FROM group_messages WHERE group_id=? AND requirement_id=? ORDER BY rowid LIMIT 1').get(groupId,question):this.db.prepare('SELECT rowid FROM group_messages WHERE group_id=? AND id=?').get(groupId,after);
    if(!cursor)return [];
    return this.db.prepare('SELECT * FROM group_messages WHERE group_id=? AND rowid>=? ORDER BY rowid LIMIT 120').all(groupId,cursor.rowid+(question?0:1)).map(this.publicMessage);
  }
  roomMessages(groupId:string,before:string|null=null){
    const cursor=before?this.db.prepare('SELECT rowid FROM group_messages WHERE id=? AND group_id=?').get(before,groupId):null;
    return this.db.prepare('SELECT * FROM group_messages WHERE group_id=? AND rowid<? ORDER BY rowid DESC LIMIT 120').all(groupId,cursor?.rowid||Number.MAX_SAFE_INTEGER).reverse().map(this.publicMessage);
  }
  searchMessages(query:string,limit=40){const escaped=`%${query.replace(/[\\%_]/g,value=>'\\'+value)}%`;return this.db.prepare("SELECT gm.*,g.name group_name FROM group_messages gm JOIN groups g ON g.id=gm.group_id WHERE gm.content LIKE ? ESCAPE '\\' OR g.name LIKE ? ESCAPE '\\' ORDER BY gm.created_at DESC LIMIT ?").all(escaped,escaped,limit).map(row=>{const content=String(row.content).replace(/\s+/g,' '),at=content.toLowerCase().indexOf(query.toLowerCase()),start=Math.max(0,at<0?0:at-70);return{scope:'group',id:row.group_id,anchor:row.requirement_id||row.id,title:row.group_name,snippet:(start?'…':'')+content.slice(start,start+220)+(content.length>start+220?'…':''),updatedAt:row.created_at};});}
  unreadAnchor(threadId:string){const binding=this.threadBinding(threadId);if(!binding)return null;if(binding.type==='member')return this.db.prepare("SELECT requirement_id id FROM tasks WHERE member_id=? AND status IN ('running','reviewing') ORDER BY updated_at LIMIT 1").get(binding.memberId)?.id||null;return this.db.prepare("SELECT id FROM requirements WHERE group_id=? AND status IN ('plan_drafting','finalizing','running') ORDER BY updated_at LIMIT 1").get(binding.groupId)?.id||null;}
  taskProgress(threadId:string,turnId:string,itemId:string,content:string){
    const task=this.db.prepare("SELECT t.*,m.name FROM tasks t JOIN group_members m ON m.id=t.member_id WHERE m.thread_id=? AND t.status='running' AND (t.turn_id=? OR t.turn_id IS NULL) LIMIT 1").get(threadId,turnId);
    if(!task||!content)return null;
    const id=`progress:${task.id}:${turnId}:${itemId}`,reference={type:'progress',taskId:task.id,threadId,turnId};
    this.db.prepare('INSERT INTO group_messages(id,group_id,requirement_id,kind,author,content,reference_json,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET content=excluded.content').run(id,task.group_id,task.requirement_id,'member',task.name,String(content).slice(-12000),json(reference),now());
    return task.group_id;
  }
  transaction<T>(fn:()=>T){this.db.exec('BEGIN IMMEDIATE');try{const value=fn();this.db.exec('COMMIT');return value;}catch(error){this.db.exec('ROLLBACK');throw error;}}
  validateGroupInput(input:Row={}){const limits={...GROUP_LIMITS,...(input.limits||{})};if(!Number.isInteger(limits.maxTasks)||limits.maxTasks<1||limits.maxTasks>30)throw new Error('任务上限需为 1–30');if(!Number.isInteger(limits.maxReworks)||limits.maxReworks<0||limits.maxReworks>10)throw new Error('返工上限需为 0–10');if(!Number.isInteger(limits.maxRounds)||limits.maxRounds<1||limits.maxRounds>50)throw new Error('调度轮数需为 1–50');if(!Number.isInteger(limits.taskTimeoutMinutes)||limits.taskTimeoutMinutes<5||limits.taskTimeoutMinutes>720)throw new Error('单任务超时需为 5–720 分钟');if(!Number.isInteger(limits.maxConcurrency)||limits.maxConcurrency<1||limits.maxConcurrency>10)throw new Error('并发上限需为 1–10');return{name:clean(input.name,'群组名称',80,true),description:clean(input.description,'项目说明'),constraints:clean(input.constraints,'项目约束',8000),limits};}
  createGroup(input:Row,coordinatorThreadId:string,cwd:string){const id=randomUUID(),stamp=now(),v=this.validateGroupInput(input),row={id,name:v.name,description:v.description,cwd,constraints_text:v.constraints,coordinator_thread_id:coordinatorThreadId,summary:'',status:'idle',limits_json:json(v.limits),created_at:stamp,updated_at:stamp};this.db.prepare('INSERT INTO groups(id,name,description,cwd,constraints_text,coordinator_thread_id,summary,status,limits_json,created_at,updated_at) VALUES(@id,@name,@description,@cwd,@constraints_text,@coordinator_thread_id,@summary,@status,@limits_json,@created_at,@updated_at)').run(row);this.addMessage(id,null,'system','Omega',`群组“${row.name}”已创建，可从不同项目添加成员会话。`,{threadId:coordinatorThreadId});return this.getGroup(id);}
  setConcurrency(groupId:string,value:any,requirementId:string|null=null){const row=this.db.prepare('SELECT limits_json FROM groups WHERE id=?').get(groupId);if(!row)throw Object.assign(new Error('群组不存在'),{status:404});const maxConcurrency=Number(value);if(!Number.isInteger(maxConcurrency)||maxConcurrency<1||maxConcurrency>10)throw new Error('并发数需为 1–10');const limits={...GROUP_LIMITS,...parse(row.limits_json,{}),maxConcurrency};this.db.prepare('UPDATE groups SET limits_json=?,updated_at=? WHERE id=?').run(json(limits),now(),groupId);this.addMessage(groupId,null,'system','Omega',`群组并发数已调整为 ${maxConcurrency}。`,{type:'concurrency-setting',maxConcurrency});return this.getGroup(groupId,requirementId);}
  aggregateStatus(groupId:string){const rows=this.db.prepare("SELECT status FROM requirements WHERE group_id=? AND status NOT IN ('completed','accepted','cancelled')").all(groupId);if(!rows.length)return'idle';const statuses=new Set(rows.map(row=>row.status));return groupStatusPriority.find(status=>statuses.has(status))||'paused';}
  refreshStatus(groupId:string){const status=this.aggregateStatus(groupId);this.db.prepare('UPDATE groups SET status=?,updated_at=? WHERE id=?').run(status,now(),groupId);return status;}
  refreshAllStatuses(){for(const row of this.db.prepare('SELECT id FROM groups').all())this.refreshStatus(row.id);}
  touch(groupId:string){this.db.prepare('UPDATE groups SET updated_at=? WHERE id=?').run(now(),groupId);}
  listGroups(){return this.db.prepare(`SELECT g.*,(SELECT COUNT(*) FROM group_members m WHERE m.group_id=g.id AND m.active=1) member_count,(SELECT COUNT(*) FROM requirements r WHERE r.group_id=g.id) requirement_count,(SELECT COUNT(*) FROM requirements r WHERE r.group_id=g.id AND r.status NOT IN ('completed','accepted','cancelled')) open_requirement_count,(SELECT COUNT(*) FROM tasks t WHERE t.group_id=g.id AND t.status='running') running_tasks FROM groups g ORDER BY g.updated_at DESC`).all().map(row=>this.publicGroup(row,false));}
  publicGroup(row:Row|undefined,full=true,requirementId:string|null=null):any{if(!row)return null;const limits={...GROUP_LIMITS,...parse(row.limits_json,{})};const group:any={id:row.id,name:row.name,description:row.description,cwd:row.cwd,constraints:row.constraints_text,coordinatorThreadId:row.coordinator_thread_id,summary:row.summary,status:row.status,limits,createdAt:row.created_at,updatedAt:row.updated_at,memberCount:Number(row.member_count||0),requirementCount:Number(row.requirement_count||0),openRequirementCount:Number(row.open_requirement_count||0),runningTasks:Number(row.running_tasks||0)};if(!full)return group;group.members=this.db.prepare('SELECT * FROM group_members WHERE group_id=? AND active=1 ORDER BY created_at').all(row.id).map(this.publicMember);const reqRows=this.db.prepare('SELECT * FROM requirements WHERE group_id=? ORDER BY created_at DESC LIMIT 50').all(row.id);group.requirements=reqRows.map(req=>{const value=this.publicRequirement(req,true);delete value.delivery;value.plan=value.plan?{summary:value.plan.summary}:null;value.tasks=value.tasks.map(({result,...task}:Row)=>task);return value;});const selected=requirementId?this.db.prepare('SELECT * FROM requirements WHERE id=? AND group_id=?').get(requirementId,row.id):reqRows[0];if(selected&&!reqRows.some(req=>req.id===selected.id)){const value=this.publicRequirement(selected,true);delete value.delivery;value.tasks=value.tasks.map(({result,...task}:Row)=>task);group.requirements.push(value);}group.requirement=selected?this.publicRequirement(selected,true):null;group.requirementCount=Number(this.db.prepare('SELECT COUNT(*) n FROM requirements WHERE group_id=?').get(row.id)?.n);group.openRequirementCount=Number(this.db.prepare("SELECT COUNT(*) n FROM requirements WHERE group_id=? AND status NOT IN ('completed','accepted','cancelled')").get(row.id)?.n);group.runningTasks=Number(this.db.prepare("SELECT COUNT(*) count FROM tasks WHERE group_id=? AND status='running'").get(row.id)?.count);group.messages=this.roomMessages(row.id);return group;}
  publicMember=(row:Row)=>({id:row.id,groupId:row.group_id,threadId:row.thread_id,name:row.name,role:row.role,avatar:row.avatar||'',responsibilities:row.responsibilities,operations:row.operations,skills:row.skills,cwd:row.cwd,projectName:row.project_name,active:!!row.active,createdAt:row.created_at});
  publicMessage=(row:Row)=>({id:row.id,groupId:row.group_id,requirementId:row.requirement_id,kind:row.kind,author:row.author,content:row.content,reference:parse(row.reference_json),createdAt:row.created_at});
  publicTask=(row:Row)=>({id:row.id,requirementId:row.requirement_id,groupId:row.group_id,position:row.position,round:row.round_no||1,memberId:row.member_id,title:row.title,objective:row.objective,acceptance:row.acceptance,dependencies:parse(row.dependencies_json,[]),cwd:row.cwd,accessMode:accessMode(row.access_mode,row.title,row.objective),status:row.status,queueReason:this.queueReason(row.id),dispatchId:row.dispatch_id,turnId:row.turn_id,result:row.result,error:row.error,decision:parse(row.decision_json),attempt:row.attempt,startedAt:row.started_at,deadlineAt:row.deadline_at,completedAt:row.completed_at,createdAt:row.created_at,updatedAt:row.updated_at});
  publicRequirement(row:Row,withTasks=false):any{const value:any={id:row.id,groupId:row.group_id,pauseKind:row.pause_kind||null,budget:parse(row.budget_json,{maxMinutes:0,maxTokens:0}),budgetStartedAt:row.budget_started_at,budgetUsage:this.budgetUsage(row.id),collaborationMode:row.collaboration_mode||'direct',maxRounds:row.max_rounds||3,content:row.content,acceptance:row.acceptance,images:parse(row.images_json,[]),pastedTexts:parse(row.pastes_json,[]),mentions:parse(row.mentions_json,[]),replyTaskId:row.reply_task_id,status:row.status,plan:parse(row.plan_json),delivery:row.delivery,coordinatorTurnId:row.coordinator_turn_id,error:row.error,createdAt:row.created_at,updatedAt:row.updated_at};if(withTasks)value.tasks=this.db.prepare('SELECT * FROM tasks WHERE requirement_id=? ORDER BY position').all(row.id).map(this.publicTask);return value;}
  getGroup(id:string,requirementId:string|null=null):any{const row=this.db.prepare('SELECT * FROM groups WHERE id=?').get(id);if(!row)throw Object.assign(new Error('群组不存在'),{status:404});return this.publicGroup(row,true,requirementId);}
  getRequirement(id:string):any{const row=this.db.prepare('SELECT * FROM requirements WHERE id=?').get(id);return row?this.publicRequirement(row,true):null;}
  budgetUsage(id:string){const row=this.db.prepare('SELECT SUM(tokens) tokens,COUNT(*) samples FROM group_turn_usage WHERE requirement_id=?').get(id);return{tokens:row?.tokens??null,samples:row?.samples||0};}
  configureBudget(id:string,input:Row){const budget=validateBudget(input);this.db.prepare('UPDATE requirements SET budget_json=? WHERE id=?').run(json(budget),id);}
  observeUsage(threadId:string,turnId:string,tokens:unknown){if(typeof tokens!=='number'||!Number.isSafeInteger(tokens)||tokens<0)return;const task=this.db.prepare('SELECT t.requirement_id FROM tasks t JOIN group_members m ON m.id=t.member_id WHERE m.thread_id=? AND (t.turn_id=? OR (t.turn_id IS NULL AND t.status=\'running\'))').get(threadId,turnId);const existing=this.db.prepare('SELECT requirement_id FROM group_turn_usage WHERE thread_id=? AND turn_id=?').get(threadId,turnId);const id=task?.requirement_id||existing?.requirement_id;if(!id)return;this.db.prepare('INSERT INTO group_turn_usage(requirement_id,thread_id,turn_id,tokens) VALUES(?,?,?,?) ON CONFLICT(thread_id,turn_id) DO UPDATE SET tokens=MAX(tokens,excluded.tokens)').run(id,threadId,turnId,tokens);this.enforceBudget(id);}
  budgetReason(id:string){const req=this.db.prepare('SELECT * FROM requirements WHERE id=?').get(id);if(!req)return null;const budget=parse(req.budget_json,{}),next=this.db.prepare("SELECT MIN(round_no) round FROM tasks WHERE requirement_id=? AND status='queued'").get(id);if(!next?.round)return null;if(next.round>req.max_rounds)return'已达到协作轮次上限';if(budget.maxMinutes&&req.budget_started_at&&Date.now()-Date.parse(req.budget_started_at)>=budget.maxMinutes*60000)return'已达到协作时间预算';const repeated=this.db.prepare("SELECT member_id,objective,result,COUNT(*) n FROM tasks WHERE requirement_id=? AND status='completed' AND position>? AND result<>'' GROUP BY member_id,objective,result HAVING COUNT(*)>=3 LIMIT 1").get(id,budget.progressAfter??-1);if(repeated)return'已达到连续无新进展保护条件';const used=this.budgetUsage(id).tokens;if(budget.maxTokens&&used!==null&&used>=budget.maxTokens)return'已达到已观测 Token 预算';return null;}
  enforceBudget(id:string){const req=this.db.prepare('SELECT status,group_id FROM requirements WHERE id=?').get(id);if(req?.status!=='running')return;const reason=this.budgetReason(id);if(!reason)return;this.db.prepare("UPDATE requirements SET status='paused',pause_kind='budget',error=?,updated_at=? WHERE id=?").run(reason,now(),id);this.addMessage(req.group_id,id,'system','Omega',reason+'；已开始的任务继续完成，后续工作保留。可调整预算后继续。',{type:'budget-paused'});this.refreshStatus(req.group_id);}
  extendBudget(groupId:string,id:string,input:Row){const req=this.getRequirement(id);if(!req||req.groupId!==groupId)throw new Error('问题不存在');if(!['running','paused'].includes(req.status))throw new Error('当前问题不能调整预算');if(!Number.isInteger(input.maxRounds)||input.maxRounds<1||input.maxRounds>100)throw new Error('协作轮次需为 1–100');const budget=validateBudget(input);this.transaction(()=>{this.configureBudget(id,budget);const position=this.db.prepare('SELECT COALESCE(MAX(position),-1) n FROM tasks WHERE requirement_id=?').get(id)?.n;this.db.prepare('UPDATE requirements SET budget_json=? WHERE id=?').run(json({...budget,progressAfter:position}),id);this.configureCollaboration(id,req.collaborationMode,input.maxRounds);if(req.status==='paused'&&req.pauseKind==='budget'){if(this.budgetReason(id))throw new Error('新总预算仍不足，请增加上限');const unresolved=this.db.prepare("SELECT status,error FROM (SELECT status,error FROM tasks WHERE requirement_id=? AND status IN ('unknown','failed') UNION ALL SELECT status,error FROM discussion_reports WHERE requirement_id=? AND status IN ('unknown','failed')) ORDER BY CASE status WHEN 'unknown' THEN 0 ELSE 1 END LIMIT 1").get(id,id);if(unresolved){this.db.prepare("UPDATE requirements SET pause_kind=?,error=?,updated_at=? WHERE id=?").run(unresolved.status==='unknown'?'recovery':'execution',unresolved.error||'任务仍需核对或重试',now(),id);return;}this.db.prepare("UPDATE requirements SET status='running',pause_kind=NULL,error=NULL,updated_at=? WHERE id=?").run(now(),id);}});this.addMessage(groupId,id,'user','你','已调整协作总预算，保留原任务继续执行。',{type:'budget-updated'});this.refreshStatus(groupId);return this.getGroup(groupId,id);}
  configureCollaboration(id:string,mode:string,maxRounds:number){if(!['direct','handoff','discussion'].includes(mode))throw new Error('无效的协作模式');if(!Number.isInteger(maxRounds)||maxRounds<1||maxRounds>100)throw new Error('协作轮次需为 1–100');this.db.prepare('UPDATE requirements SET collaboration_mode=?,max_rounds=? WHERE id=?').run(mode,maxRounds,id);}
  finishCollaboration(taskId:string,result:string,turnId:string,handoffs:Row[]=[]){
    const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(task?.status!=='running')return;
    const req=this.getRequirement(task.requirement_id),group=this.getGroup(task.group_id),round=Number(task.round_no||1);
    // A pause prevents new dispatches, not recording the result of an existing turn.
    if(req.status!=='running'&&req.status!=='paused')return;
    const targets=handoffs.map(item=>{const member=group.members.find((m:Row)=>m.id===item.memberId);if(!member||member.id===task.member_id)throw new Error('交接对象必须是群组内其他有效成员');return{member,objective:clean(item.objective,'交接目标',5000,true)};});
    if(new Set(targets.map(item=>item.member.id)).size!==targets.length)throw new Error('交接对象不能重复');
    this.transaction(()=>{
      if(result.trim()==='(pass)')this.db.prepare("UPDATE tasks SET status='completed',result='',completed_at=?,updated_at=? WHERE id=?").run(now(),now(),taskId);else this.completeTask(taskId,result,turnId);
      const append=(member:Row,objective:string,dependencies:string[],nextRound:number,mode:string)=>{const position=Number(this.db.prepare('SELECT COALESCE(MAX(position),-1)+1 n FROM tasks WHERE requirement_id=?').get(req.id)?.n),id=randomUUID(),stamp=now();this.db.prepare("INSERT INTO tasks(id,requirement_id,group_id,position,member_id,title,objective,dependencies_json,cwd,access_mode,status,round_no,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'queued',?,?,?)").run(id,req.id,group.id,position,member.id,objective.slice(0,120),objective,json(dependencies),member.cwd,mode,nextRound,stamp,stamp);};
      const count=Number(this.db.prepare('SELECT COUNT(*) n FROM tasks WHERE requirement_id=?').get(req.id)?.n);
      if(req.collaborationMode==='handoff'&&targets.length){
        if(count+targets.length>3000)throw new Error('单问题任务数已达 3000，请新建问题继续');
        for(const {member,objective} of targets){append(member,objective,[taskId],round+1,accessMode('',objective,objective));this.addMessage(group.id,req.id,'system','Omega',`交接给 ${member.name}：${objective}`,{type:'handoff',taskId,memberId:member.id,round:round+1});}
      }
      if(req.collaborationMode==='discussion'){
        const current=this.db.prepare('SELECT * FROM tasks WHERE requirement_id=? AND round_no=?').all(req.id,round);
        if(current.some(t=>t.status!=='completed')||current.every(t=>!t.result?.trim()))return;
        const previous=this.db.prepare('SELECT member_id,result FROM tasks WHERE requirement_id=? AND round_no=?').all(req.id,round-1);if(previous.length&&current.every(t=>!t.result?.trim()||previous.some(p=>p.member_id===t.member_id&&p.result?.trim()===t.result?.trim()))){this.addMessage(group.id,req.id,'system','Omega','本轮没有新增内容，讨论已结束。',{type:'discussion-no-progress'});return;}
        const participants=[...new Set(this.db.prepare('SELECT member_id FROM tasks WHERE requirement_id=? AND round_no=1').all(req.id).map(t=>t.member_id))].map(id=>group.members.find((m:Row)=>m.id===id)).filter(Boolean);
        if(count+participants.length>3000)return;
        for(const member of participants)append(member,`围绕用户问题继续讨论：${req.content.slice(0,3500)}\n只补充新的事实或不同意见，没有补充请回复 (pass)。`,current.map(t=>t.id),round+1,'read');
        this.addMessage(group.id,req.id,'system','Omega',`第 ${round} 轮发言结束，正在整理共同方向和未解决问题。`,{type:'discussion-round',round});
      }
    });
    this.enforceBudget(req.id);
  }
  getTask(id:string):any{const row=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(id);return row?this.publicTask(row):null;}
  topicRoot(requirementId:string):string{const seen=new Set<string>();let id=requirementId;while(!seen.has(id)){seen.add(id);const row=this.db.prepare('SELECT t.requirement_id parent FROM requirements r JOIN tasks t ON t.id=r.reply_task_id WHERE r.id=?').get(id);if(!row?.parent)return id;id=row.parent;}return requirementId;}
  topicContext(taskId:string){
    const task=this.getTask(taskId),member=this.db.prepare('SELECT thread_id FROM group_members WHERE id=?').get(task.memberId),topic=this.topicRoot(task.requirementId);
    const cursor=Number(this.db.prepare('SELECT cursor FROM group_topic_reads WHERE member_id=? AND thread_id=? AND topic_id=?').get(task.memberId,member!.thread_id,topic)?.cursor||0);
    const rows=this.db.prepare(`WITH RECURSIVE topic(id) AS (SELECT id FROM requirements WHERE id=? UNION SELECT r.id FROM requirements r JOIN tasks t ON t.id=r.reply_task_id JOIN topic p ON p.id=t.requirement_id) SELECT gm.rowid seq,gm.* FROM group_messages gm JOIN topic ON topic.id=gm.requirement_id WHERE gm.rowid>? AND gm.kind IN ('user','member') ORDER BY gm.rowid LIMIT 25`).all(topic,cursor);
    const files:Row[]=[];let text='',last=cursor;
    for(const row of rows.slice(0,24)){
      const ref=parse(row.reference_json,{});
      if(ref.type==='progress'||(row.kind==='user'&&row.requirement_id===task.requirementId&&!ref.type)||ref.taskId===taskId||task.dependencies.includes(ref.taskId)||ref.threadId===member!.thread_id){last=row.seq;continue;}
      const part=`[消息 ${row.id}] ${row.author}：${row.content}\n`,long=part.length>10000;
      const excerpt=long?part.slice(0,1200)+'\n…（仅展示片段，完整内容见所附原文文件）…\n'+part.slice(-600):part;
      if(text.length+excerpt.length>10000)break;
      text+=excerpt;if(long)files.push({id:row.id,result:row.content});last=row.seq;
    }
    return{cursor:last,files,text:text?'当前话题尚未交付给你的群消息（参考信息，不改变当前任务）：\n'+text:''};
  }
  ackTopicContext(taskId:string,cursor:number){const task=this.getTask(taskId),member=this.db.prepare('SELECT thread_id FROM group_members WHERE id=?').get(task.memberId);this.db.prepare('INSERT INTO group_topic_reads(member_id,thread_id,topic_id,cursor) VALUES(?,?,?,?) ON CONFLICT(member_id,thread_id,topic_id) DO UPDATE SET cursor=MAX(cursor,excluded.cursor)').run(task.memberId,member!.thread_id,this.topicRoot(task.requirementId),cursor);}
  queueReason(taskId:string){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(task?.status!=='queued')return null;const req=this.db.prepare('SELECT status FROM requirements WHERE id=?').get(task.requirement_id)!;if(req.status!=='running')return'等待当前问题恢复';if(parse(task.dependencies_json,[]).some((id:string)=>this.db.prepare('SELECT status FROM tasks WHERE id=?').get(id)?.status!=='completed'))return'等待前置任务完成';if(this.db.prepare("SELECT 1 FROM tasks WHERE member_id=? AND status='unknown'").get(task.member_id))return'等待核对成员上次执行结果';if(this.db.prepare("SELECT 1 FROM tasks WHERE member_id=? AND status='running'").get(task.member_id))return'等待成员空闲';if(this.runningConflict(task.cwd,null,task.access_mode))return'等待工作目录空闲';const group=this.db.prepare('SELECT limits_json FROM groups WHERE id=?').get(task.group_id);if(this.runningCount(task.group_id)>=parse(group?.limits_json,GROUP_LIMITS).maxConcurrency)return'等待并发名额';return this.externalQueueReason({...task,threadId:this.db.prepare('SELECT thread_id FROM group_members WHERE id=?').get(task.member_id)?.thread_id})||'等待调度';}
  recoverableTasks(){return this.db.prepare("SELECT t.*,m.thread_id,g.limits_json FROM tasks t JOIN group_members m ON m.id=t.member_id JOIN groups g ON g.id=t.group_id WHERE t.status='unknown' AND t.turn_id IS NOT NULL AND t.recovery_checked_at IS NULL AND m.active=1 ORDER BY t.updated_at").all().map(row=>({...this.publicTask(row),threadId:row.thread_id,limits:{...GROUP_LIMITS,...parse(row.limits_json,{})}}));}
  reattachTask(taskId:string){const task=this.db.prepare("SELECT requirement_id,group_id FROM tasks WHERE id=? AND status='unknown' AND turn_id IS NOT NULL AND recovery_checked_at IS NULL").get(taskId);if(!task)return false;const stamp=now();this.db.prepare("UPDATE tasks SET status='running',recovery_checked_at=?,error=NULL,updated_at=? WHERE id=? AND status='unknown'").run(stamp,stamp,taskId);this.refreshStatus(task.group_id);return true;}
  resumeRequirementIfRecoverable(requirementId:string){
    const req=this.db.prepare('SELECT group_id FROM requirements WHERE id=?').get(requirementId);if(!req)return false;
    if(this.db.prepare("SELECT 1 FROM tasks WHERE requirement_id=? AND status IN ('unknown','failed') LIMIT 1").get(requirementId))return false;
    const changed=this.db.prepare("UPDATE requirements SET status='running',pause_kind=NULL,error=NULL,updated_at=? WHERE id=? AND status='paused' AND pause_kind='recovery'").run(now(),requirementId);
    this.enforceBudget(requirementId);this.refreshStatus(req.group_id);return !!changed.changes;
  }
  deleteGroup(groupId:string){const group=this.getGroup(groupId);if(this.db.prepare("SELECT 1 FROM tasks WHERE group_id=? AND status='running' LIMIT 1").get(groupId))throw Object.assign(new Error('群组仍有任务正在执行，请先停止任务'),{status:409});this.db.prepare('DELETE FROM groups WHERE id=?').run(groupId);return{id:group.id,name:group.name,coordinatorThreadId:group.coordinatorThreadId,memberThreadIds:group.members.map((member:Row)=>member.threadId)};}
  addMember(groupId:string,input:Row){const group=this.getGroup(groupId);const id=randomUUID(),stamp=now(),memberCwd=input.cwd||group.cwd,values=[groupId,clean(input.threadId,'会话',100,true),clean(input.name,'成员名称',80,true),clean(input.role,'身份',80,true),clean(input.responsibilities,'职责',3000),clean(input.operations,'操作范围',2000),clean(input.skills,'擅长任务',2000),clean(memberCwd,'成员工作目录',2000,true),clean(input.projectName||path.basename(memberCwd),'项目名称',120),cleanAvatar(input.avatar)];try{this.db.prepare('INSERT INTO group_members(id,group_id,thread_id,name,role,responsibilities,operations,skills,cwd,project_name,avatar,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,1,?)').run(id,...values,stamp);}catch(error){if(!/UNIQUE/.test((error as Error).message))throw error;const old=this.db.prepare('SELECT * FROM group_members WHERE thread_id=?').get(input.threadId);if(!old||old.active)throw Object.assign(new Error('该会话已经加入了一个群组'),{status:409});this.db.prepare('UPDATE group_members SET group_id=?,name=?,role=?,responsibilities=?,operations=?,skills=?,cwd=?,project_name=?,avatar=?,active=1,created_at=? WHERE id=?').run(...values.filter((_,i)=>i!==1),stamp,old.id);}this.touch(groupId);this.addMessage(groupId,null,'system','Omega',`已添加成员：${values[2]}（${values[3]}），工作目录 ${values[7]}`,{threadId:input.threadId,memberId:id});return this.getGroup(groupId);}
  updateMember(groupId:string,memberId:string,input:Row,requirementId:string|null=null){const member=this.db.prepare('SELECT * FROM group_members WHERE id=? AND group_id=? AND active=1').get(memberId,groupId);if(!member)throw Object.assign(new Error('成员不存在'),{status:404});const threadId=clean(input.threadId||member.thread_id,'会话',100,true),cwd=clean(input.cwd||member.cwd,'成员工作目录',2000,true),name=clean(input.name,'成员名称',80,true),role=clean(input.role,'身份',80,true),projectName=clean(input.projectName||path.basename(cwd),'项目名称',120),responsibilities=clean(input.responsibilities,'职责',3000),operations=clean(input.operations,'操作范围',2000),skills=clean(input.skills,'擅长任务',2000),avatar=cleanAvatar(input.avatar===undefined?member.avatar:input.avatar),rebinding=threadId!==member.thread_id||cwd!==member.cwd;if(rebinding&&this.db.prepare("SELECT 1 FROM tasks WHERE member_id=? AND status IN ('running','reviewing','unknown','awaiting_input') LIMIT 1").get(memberId))throw Object.assign(new Error('该成员仍有执行中、待核对或待决策任务，请先处理或取消任务再更换会话或目录'),{status:409});try{this.transaction(()=>{this.db.prepare('UPDATE group_members SET thread_id=?,cwd=?,name=?,role=?,project_name=?,responsibilities=?,operations=?,skills=?,avatar=? WHERE id=?').run(threadId,cwd,name,role,projectName,responsibilities,operations,skills,avatar,memberId);if(rebinding)this.db.prepare("UPDATE tasks SET cwd=?,updated_at=? WHERE member_id=? AND status IN ('draft','queued','failed','unknown')").run(cwd,now(),memberId);});}catch(error){if(/UNIQUE/.test((error as Error).message))throw Object.assign(new Error('该会话已经加入了一个群组'),{status:409});throw error;}this.addMessage(groupId,null,'system','Omega',rebinding?`已将成员“${name}”重新绑定到会话 ${threadId}，工作目录 ${cwd}。`:`已更新成员：${name}（${role}）。`,{type:rebinding?'member-rebind':'member-update',memberId,threadId,previousThreadId:rebinding?member.thread_id:undefined});return this.getGroup(groupId,requirementId);}
  removeMember(groupId:string,memberId:string){if(this.db.prepare("SELECT 1 FROM tasks WHERE member_id=? AND status IN ('running','queued','reviewing','awaiting_input') LIMIT 1").get(memberId))throw Object.assign(new Error('该成员仍有待执行、执行中或等待决策的任务'),{status:409});const changed=this.db.prepare('UPDATE group_members SET active=0 WHERE id=? AND group_id=? AND active=1').run(memberId,groupId);if(!changed.changes)throw Object.assign(new Error('成员不存在'),{status:404});this.touch(groupId);this.addMessage(groupId,null,'system','Omega','成员已移出群组。');return this.getGroup(groupId);}
  threadBinding(threadId:string):any{const coordinator=this.db.prepare('SELECT id,name FROM groups WHERE coordinator_thread_id=?').get(threadId);if(coordinator)return{groupId:coordinator.id,groupName:coordinator.name,type:'coordinator'};const member=this.db.prepare('SELECT m.id member_id,m.group_id,g.name FROM group_members m JOIN groups g ON g.id=m.group_id WHERE m.thread_id=? AND m.active=1').get(threadId);return member?{groupId:member.group_id,groupName:member.name,type:'member',memberId:member.member_id}:null;}
  markThreadUnavailable(threadId:string):any{const binding=this.threadBinding(threadId);if(!binding)return null;if(binding.type==='coordinator'){for(const req of this.db.prepare("SELECT id FROM requirements WHERE group_id=? AND status NOT IN ('completed','accepted','cancelled','awaiting_acceptance')").all(binding.groupId))this.failPhase(req.id,'协调者会话已不可用，请恢复会话后继续');}else{for(const req of this.db.prepare("SELECT DISTINCT requirement_id id FROM tasks WHERE member_id=? AND status IN ('queued','running','reviewing')").all(binding.memberId))this.failPhase(req.id,'成员会话已不可用，请恢复会话后继续');}return binding;}
  createRequirement(groupId:string,input:Row):any{const group=this.getGroup(groupId);if(!group.members.length)throw new Error('请先添加至少一个会话成员');const replyTask=input.replyTaskId?this.getTask(input.replyTaskId):null;if(input.replyTaskId&&(!replyTask||replyTask.groupId!==groupId))throw new Error('引用的回答不属于该群组');const id=randomUUID(),stamp=now(),content=clean(input.content,'需求',12000,true),acceptance=clean(input.acceptance,'验收条件',6000),pastes=cleanPastes(input.pasteRefs),mentions=validateMentions(input.mentions,content,group.members);this.db.prepare('INSERT INTO requirements(id,group_id,content,acceptance,pastes_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,groupId,content,acceptance,json(pastes),'plan_drafting',stamp,stamp);this.db.prepare('UPDATE requirements SET images_json=?,mentions_json=? WHERE id=?').run(json(input.imageRefs||[]),json(mentions),id);if(replyTask)this.db.prepare('UPDATE requirements SET reply_task_id=? WHERE id=?').run(replyTask.id,id);this.refreshStatus(groupId);this.addMessage(groupId,id,'user','你',content,{acceptance,images:input.imageRefs||[],replyTaskId:replyTask?.id,pastedTexts:pastes,mentions});return{group:this.getGroup(groupId,id),requirement:this.getRequirement(id)};}
  setPlan(requirementId:string,summary:string,tasks:Row[],coordinatorTurnId:string|null,raw:string):any{const req=this.db.prepare('SELECT * FROM requirements WHERE id=?').get(requirementId);if(!req)throw new Error('需求单不存在');if(req.status!=='plan_drafting')return this.getGroup(req.group_id,requirementId);const group=this.getGroup(req.group_id,requirementId),stamp=now();if(!Array.isArray(tasks)||!tasks.length)throw new Error('协调者没有生成可执行任务');if(tasks.length>group.limits.maxTasks)throw new Error(`任务数超过群组上限 ${group.limits.maxTasks}`);const members=new Map<string,Row>(group.members.map((member:Row)=>[member.id,member]));const normalized:any[]=tasks.map((task,index)=>{const member=members.get(task.memberId);if(!member)throw new Error(`任务“${task.title||index+1}”没有有效负责人`);const indexes=Array.isArray(task.dependsOn)?task.dependsOn:[];for(const value of indexes)if(!Number.isInteger(value)||value<0||value>=index)throw new Error(`任务“${task.title||index+1}”包含无效依赖`);const title=clean(task.title,'任务名称',120,true),objective=clean(task.objective,'任务目标',5000,true);return{id:randomUUID(),memberId:member.id,title,objective,acceptance:clean(task.acceptance,'任务验收要求',3000),dependsOn:indexes,cwd:member.cwd,accessMode:accessMode(task.accessMode,title,objective)};});for(const task of normalized)task.dependencies=task.dependsOn.map((index:any)=>normalized[index].id);this.transaction(()=>{this.db.prepare('DELETE FROM tasks WHERE requirement_id=?').run(requirementId);const insert=this.db.prepare('INSERT INTO tasks(id,requirement_id,group_id,position,member_id,title,objective,acceptance,dependencies_json,cwd,access_mode,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');normalized.forEach((task,index)=>insert.run(task.id,requirementId,req.group_id,index,task.memberId,task.title,task.objective,task.acceptance,json(task.dependencies),task.cwd,task.accessMode,'draft',stamp,stamp));this.db.prepare("UPDATE requirements SET status='awaiting_confirmation',plan_json=?,coordinator_turn_id=?,error=NULL,updated_at=? WHERE id=?").run(json({summary,tasks:normalized}),coordinatorTurnId||null,stamp,requirementId);this.db.prepare('UPDATE groups SET summary=?,updated_at=? WHERE id=?').run(clean(summary,'群组摘要',12000),stamp,req.group_id);});this.refreshStatus(req.group_id);this.addMessage(req.group_id,requirementId,'coordinator','协调者',summary,{threadId:group.coordinatorThreadId,turnId:coordinatorTurnId,type:'plan'});return this.getGroup(req.group_id,requirementId);}
  setDirectPlan(requirementId:string,summary:string,tasks:Row[]){const group=this.setPlan(requirementId,summary,tasks,null,'direct mention');const latest=this.db.prepare('SELECT id,reference_json FROM group_messages WHERE requirement_id=? ORDER BY rowid DESC LIMIT 1').get(requirementId);if(parse(latest?.reference_json)?.type==='plan')this.db.prepare('DELETE FROM group_messages WHERE id=?').run(latest!.id);return this.getGroup(group.id,requirementId);}
  failPhase(requirementId:string,message:string,status='paused',pauseKind='execution'){const req=this.db.prepare('SELECT group_id FROM requirements WHERE id=?').get(requirementId);if(!req)return;this.db.prepare('UPDATE requirements SET status=?,pause_kind=CASE WHEN pause_kind=\'budget\' THEN pause_kind ELSE ? END,error=CASE WHEN pause_kind=\'budget\' THEN error ELSE ? END,updated_at=? WHERE id=? AND status NOT IN (\'cancelled\',\'completed\',\'accepted\')').run(status,pauseKind,String(message).slice(0,4000),now(),requirementId);this.refreshStatus(req.group_id);this.addMessage(req.group_id,requirementId,'system','Omega',`协作流程已暂停：${message}`);}
  confirmPlan(groupId:string,requirementId:string,automatic=false){const changed=this.db.prepare("UPDATE requirements SET status='running',error=NULL,updated_at=? WHERE id=? AND group_id=? AND status='awaiting_confirmation'").run(now(),requirementId,groupId);if(!changed.changes)throw Object.assign(new Error('当前计划不能确认，可能已在其他设备处理'),{status:409});this.db.prepare("UPDATE tasks SET status='queued',updated_at=? WHERE requirement_id=? AND status='draft'").run(now(),requirementId);this.refreshStatus(groupId);if(!automatic)this.addMessage(groupId,requirementId,'user','你','已确认执行计划。',{type:'plan-confirmation'});return this.getGroup(groupId,requirementId);}
  updateDraftTask(groupId:string,requirementId:string,input:Row){const req=this.db.prepare('SELECT status FROM requirements WHERE id=? AND group_id=?').get(requirementId,groupId);if(!req||req.status!=='awaiting_confirmation')throw Object.assign(new Error('只能修改等待确认的计划'),{status:409});const task=this.db.prepare('SELECT * FROM tasks WHERE id=? AND requirement_id=?').get(input.taskId,requirementId),member=this.db.prepare('SELECT * FROM group_members WHERE id=? AND group_id=? AND active=1').get(input.memberId||task?.member_id,groupId);if(!task)throw Object.assign(new Error('任务不存在'),{status:404});if(!member)throw new Error('请选择有效的负责人');const title=clean(input.title??task.title,'任务名称',120,true),objective=clean(input.objective??task.objective,'任务目标',5000,true),mode=accessMode(input.accessMode??task.access_mode,title,objective);this.db.prepare('UPDATE tasks SET member_id=?,cwd=?,access_mode=?,title=?,objective=?,acceptance=?,updated_at=? WHERE id=?').run(member.id,member.cwd,mode,title,objective,clean(input.acceptance??task.acceptance,'任务验收要求',3000),now(),task.id);this.touch(groupId);return this.getGroup(groupId,requirementId);}
  runnableTasks(groupId:string){const tasks=this.db.prepare("SELECT t.*,r.collaboration_mode,m.thread_id,m.name member_name,m.role member_role,m.responsibilities,m.operations,m.skills FROM tasks t JOIN requirements r ON r.id=t.requirement_id JOIN group_members m ON m.id=t.member_id WHERE t.group_id=? AND t.status='queued' AND r.status='running' AND m.active=1 ORDER BY r.created_at,t.position").all(groupId);const completed=new Set(this.db.prepare("SELECT id FROM tasks WHERE group_id=? AND status='completed'").all(groupId).map(row=>row.id));const busyMembers=new Set(this.db.prepare("SELECT member_id FROM tasks WHERE status IN ('running','unknown')").all().map(row=>row.member_id));const running=this.db.prepare("SELECT id,cwd,access_mode FROM tasks WHERE status IN ('running','unknown')").all();return tasks.filter(task=>(Number(task.round_no||1)===1||task.collaboration_mode!=='discussion'||!!this.db.prepare("SELECT 1 FROM discussion_reports WHERE requirement_id=? AND round_no=? AND status='completed'").get(task.requirement_id,task.round_no-1))&&parse(task.dependencies_json,[]).every((id:any)=>completed.has(id))&&!busyMembers.has(task.member_id)&&!running.some(other=>workspaceConflict(other.access_mode,task.access_mode)&&overlap(other.cwd,task.cwd)));}
  nextTask(requirementId:string){return this.db.prepare("SELECT * FROM tasks WHERE requirement_id=? AND status='queued' ORDER BY position LIMIT 1").get(requirementId);}
  nextReview(groupId:string){return this.db.prepare("SELECT t.* FROM tasks t JOIN requirements r ON r.id=t.requirement_id WHERE t.group_id=? AND t.status='reviewing' AND r.status='running' ORDER BY t.updated_at LIMIT 1").get(groupId);}
  nextPlan(groupId:string){return this.db.prepare("SELECT * FROM requirements WHERE group_id=? AND status='plan_drafting' ORDER BY created_at LIMIT 1").get(groupId);}
  nextFinalizable(groupId:string){return this.db.prepare("SELECT r.* FROM requirements r WHERE r.group_id=? AND r.status='running' AND r.collaboration_mode!='discussion' AND EXISTS(SELECT 1 FROM tasks t WHERE t.requirement_id=r.id) AND NOT EXISTS(SELECT 1 FROM tasks t WHERE t.requirement_id=r.id AND t.status!='completed') ORDER BY r.created_at LIMIT 1").get(groupId);}
  runningCount(groupId:string){return Number(this.db.prepare("SELECT COUNT(*) count FROM tasks WHERE group_id=? AND status='running'").get(groupId)?.count);}
  runningConflict(cwd:string,excludeGroupId:string|null=null,mode='write'){const rows=this.db.prepare("SELECT t.id task_id,t.group_id,g.name,t.cwd,t.access_mode FROM tasks t JOIN groups g ON g.id=t.group_id WHERE t.status IN ('running','unknown')").all();const hit=rows.find(row=>(!excludeGroupId||row.group_id!==excludeGroupId)&&workspaceConflict(row.access_mode,mode)&&overlap(row.cwd,cwd));return hit?{taskId:hit.task_id,groupId:hit.group_id,groupName:hit.name,cwd:hit.cwd,accessMode:hit.access_mode}:null;}
  startTask(taskId:string,dispatchId:string,turnId:string|null,timeoutMs=GROUP_LIMITS.taskTimeoutMinutes*60000){this.db.prepare('UPDATE requirements SET budget_started_at=COALESCE(budget_started_at,?) WHERE id=(SELECT requirement_id FROM tasks WHERE id=?)').run(now(),taskId);const stamp=now(),deadline=new Date(Date.now()+Math.max(1000,timeoutMs)).toISOString();const changed=this.db.prepare("UPDATE tasks SET status='running',dispatch_id=?,turn_id=?,attempt=attempt+1,started_at=?,deadline_at=?,recovery_checked_at=NULL,error=NULL,updated_at=? WHERE id=? AND status IN ('queued','unknown','failed')").run(dispatchId,turnId||null,stamp,deadline,stamp,taskId);if(!changed.changes)throw Object.assign(new Error('任务状态已发生变化'),{status:409});}
  setTaskTurn(taskId:string,turnId:string){this.db.prepare('UPDATE tasks SET turn_id=?,updated_at=? WHERE id=?').run(turnId,now(),taskId);}
  recordTaskResult(taskId:string,result:string,turnId:string|null){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(!task)throw new Error('任务不存在');this.db.prepare("UPDATE tasks SET status='reviewing',result=?,turn_id=COALESCE(?,turn_id),error=NULL,updated_at=? WHERE id=?").run(result,turnId||null,now(),taskId);this.db.prepare("DELETE FROM group_messages WHERE requirement_id=? AND json_extract(reference_json,'$.type')='progress' AND json_extract(reference_json,'$.taskId')=? AND content=?").run(task.requirement_id,taskId,String(result).slice(-12000));const member=this.db.prepare('SELECT * FROM group_members WHERE id=?').get(task.member_id);this.addMessage(task.group_id,task.requirement_id,'member',member?.name||'成员',result,{type:'delivery',taskId,threadId:member?.thread_id,turnId:turnId||task.turn_id});}
  recordTaskDecision(taskId:string,result:string,turnId:string|null,input:Row){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(!task)throw new Error('任务不存在');const stamp=now(),decision={id:randomUUID(),title:clean(input.title,'决策标题',120,true),question:clean(input.question,'决策问题',1000,true),options:input.options,allowOther:input.allowOther!==false,status:'pending',requestedAt:stamp};this.transaction(()=>{this.db.prepare("UPDATE tasks SET status='awaiting_input',result=?,turn_id=COALESCE(?,turn_id),decision_json=?,error=NULL,updated_at=? WHERE id=? AND status='running'").run(clean(result||decision.question,'成员说明',50000,true),turnId||null,json(decision),stamp,taskId);this.db.prepare('UPDATE requirements SET updated_at=? WHERE id=?').run(stamp,task.requirement_id);});this.db.prepare("DELETE FROM group_messages WHERE requirement_id=? AND json_extract(reference_json,'$.type')='progress' AND json_extract(reference_json,'$.taskId')=?").run(task.requirement_id,taskId);const member=this.db.prepare('SELECT * FROM group_members WHERE id=?').get(task.member_id);this.addMessage(task.group_id,task.requirement_id,'member',member?.name||'成员',result||decision.question,{type:'decision-request',taskId,threadId:member?.thread_id,turnId:turnId||task.turn_id,decision});this.refreshStatus(task.group_id);return this.getTask(taskId);}
  resolveDecision(groupId:string,taskId:string,input:Row){const row=this.db.prepare('SELECT * FROM tasks WHERE id=? AND group_id=?').get(taskId,groupId);if(!row)throw Object.assign(new Error('待决策任务不存在'),{status:404});const decision=parse(row.decision_json);if(row.status!=='awaiting_input'||decision?.status!=='pending')throw Object.assign(new Error('这个决策已经处理或任务状态已变化'),{status:409});if(input.decisionId!==decision.id)throw Object.assign(new Error('决策已更新，请关闭弹框后重新打开'),{status:409});const choiceId=clean(input.choiceId,'选择',60,true),option=decision.options?.find((item:Row)=>item.id===choiceId),other=choiceId==='other'&&decision.allowOther;if(!option&&!other)throw new Error('请选择有效方案');const custom=clean(input.custom,'其他方案',2000,other),note=clean(input.note,'补充要求',3000),label=other?custom:option.label,stamp=now(),resolved={...decision,status:'resolved',respondedAt:stamp,answer:{choiceId,label,note}};this.transaction(()=>{this.db.prepare("UPDATE tasks SET status='queued',dispatch_id=NULL,turn_id=NULL,decision_json=?,error=NULL,updated_at=? WHERE id=? AND status='awaiting_input'").run(json(resolved),stamp,taskId);this.db.prepare("UPDATE requirements SET status='running',pause_kind=NULL,error=NULL,updated_at=? WHERE id=? AND (status='running' OR (status='paused' AND pause_kind='recovery')) AND NOT EXISTS (SELECT 1 FROM tasks WHERE requirement_id=? AND status IN ('unknown','failed'))").run(stamp,row.requirement_id,row.requirement_id);const messages=this.db.prepare("SELECT id,reference_json FROM group_messages WHERE requirement_id=? AND json_extract(reference_json,'$.type')='decision-request' AND json_extract(reference_json,'$.taskId')=?").all(row.requirement_id,taskId);for(const message of messages){const reference=parse(message.reference_json,{});if(reference.decision?.id===decision.id)this.db.prepare('UPDATE group_messages SET reference_json=? WHERE id=?').run(json({...reference,decision:resolved}),message.id);}});this.refreshStatus(groupId);this.addMessage(groupId,row.requirement_id,'user','你',`决定：${label}${note?`\n补充要求：${note}`:''}`,{type:'decision-response',taskId,decisionId:decision.id,choiceId});return this.getGroup(groupId,row.requirement_id);}
  approveTask(taskId:string,review:string,reviewTurnId:string|null){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(!task)throw new Error('任务不存在');this.db.prepare("UPDATE tasks SET status='completed',completed_at=?,error=NULL,updated_at=? WHERE id=? AND status='reviewing'").run(now(),now(),taskId);this.addMessage(task.group_id,task.requirement_id,'coordinator','协调者',review||`任务“${task.title}”验证通过。`,{type:'task-review',taskId,turnId:reviewTurnId});}
  completeTask(taskId:string,result:string,turnId:string|null){const task=this.getTask(taskId);if(task?.status!=='reviewing')this.recordTaskResult(taskId,result,turnId);this.db.prepare("UPDATE tasks SET status='completed',completed_at=?,error=NULL,updated_at=? WHERE id=? AND status='reviewing'").run(now(),now(),taskId);}
  reworkTask(taskId:string,feedback:string,reviewTurnId:string|null){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(!task)throw new Error('任务不存在');const group=this.getGroup(task.group_id,task.requirement_id),rounds=Number(this.db.prepare('SELECT COALESCE(SUM(attempt),0) rounds FROM tasks WHERE requirement_id=?').get(task.requirement_id)?.rounds);if(task.attempt>group.limits.maxReworks||rounds>=group.limits.maxRounds)throw Object.assign(new Error('任务已经达到返工或调度轮数上限'),{status:409});this.db.prepare("UPDATE tasks SET status='queued',error=?,dispatch_id=NULL,turn_id=NULL,updated_at=? WHERE id=?").run(String(feedback).slice(0,4000),now(),taskId);this.addMessage(task.group_id,task.requirement_id,'coordinator','协调者',`任务“${task.title}”需要返工：${feedback}`,{type:'task-review',decision:'rework',taskId,turnId:reviewTurnId});}
  failTask(taskId:string,message:string,status='failed'){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(!task)return;this.db.prepare('UPDATE tasks SET status=?,error=?,updated_at=? WHERE id=?').run(status,String(message).slice(0,4000),now(),taskId);this.failPhase(task.requirement_id,`任务“${task.title}”${status==='unknown'?'结果待核对':'失败'}：${message}`,'paused',status==='unknown'?'recovery':'execution');}
  beginFinalize(requirementId:string,turnId:string|null=null){const req=this.db.prepare('SELECT group_id FROM requirements WHERE id=?').get(requirementId);if(!req)throw new Error('需求单不存在');const changed=this.db.prepare("UPDATE requirements SET status='finalizing',coordinator_turn_id=COALESCE(?,coordinator_turn_id),updated_at=? WHERE id=? AND status='running'").run(turnId,now(),requirementId);if(!changed.changes)throw Object.assign(new Error('需求状态已变化'),{status:409});this.refreshStatus(req.group_id);}
  completeDelivery(requirementId:string,delivery:string,turnId:string|null,announce=true){const req=this.db.prepare('SELECT group_id FROM requirements WHERE id=?').get(requirementId);if(!req)throw new Error('需求单不存在');this.db.prepare("UPDATE requirements SET status='completed',delivery=?,coordinator_turn_id=?,error=NULL,updated_at=? WHERE id=?").run(delivery,turnId||null,now(),requirementId);this.refreshStatus(req.group_id);const group=this.getGroup(req.group_id,requirementId);if(announce)this.addMessage(req.group_id,requirementId,'coordinator','协调者',delivery,{type:'delivery-report',threadId:group.coordinatorThreadId,turnId});}
  accept(groupId:string,requirementId:string){const changed=this.db.prepare("UPDATE requirements SET status='accepted',error=NULL,updated_at=? WHERE id=? AND group_id=? AND status='awaiting_acceptance'").run(now(),requirementId,groupId);if(!changed.changes)throw Object.assign(new Error('当前交付不能验收，可能已在其他设备处理'),{status:409});this.refreshStatus(groupId);this.addMessage(groupId,requirementId,'user','你','验收通过。',{type:'acceptance'});return this.getGroup(groupId,requirementId);}
  cancel(groupId:string,requirementId:string){const stamp=now(),changed=this.db.prepare("UPDATE requirements SET status='cancelled',error=NULL,updated_at=? WHERE id=? AND group_id=? AND status NOT IN ('completed','accepted','cancelled')").run(stamp,requirementId,groupId);if(!changed.changes)throw Object.assign(new Error('消息已经处理完成或取消'),{status:409});this.db.prepare("UPDATE tasks SET status='cancelled',error=NULL,updated_at=? WHERE requirement_id=? AND status NOT IN ('completed','cancelled')").run(stamp,requirementId);this.refreshStatus(groupId);this.addMessage(groupId,requirementId,'system','Omega','已取消这条消息及尚未完成的成员任务。',{type:'requirement-cancelled'});return this.getGroup(groupId,requirementId);}
  requestChanges(groupId:string,requirementId:string,input:Row){const feedback=clean(input.feedback,'修改意见',6000,true),req=this.db.prepare('SELECT * FROM requirements WHERE id=? AND group_id=?').get(requirementId,groupId);if(!req||req.status!=='awaiting_acceptance')throw Object.assign(new Error('当前交付不能发起返工'),{status:409});const group=this.getGroup(groupId,requirementId),member=group.members.find((m:Row)=>/开发|实现|engineer|developer/i.test(m.role))||group.members[0],position=Number(this.db.prepare('SELECT COALESCE(MAX(position),-1)+1 position FROM tasks WHERE requirement_id=?').get(requirementId)?.position),previous=this.db.prepare("SELECT id FROM tasks WHERE requirement_id=? AND status='completed' ORDER BY position").all(requirementId).map(row=>row.id),id=randomUUID();this.db.prepare('INSERT INTO tasks(id,requirement_id,group_id,position,member_id,title,objective,acceptance,dependencies_json,cwd,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,requirementId,groupId,position,member.id,'根据验收意见返工',feedback,req.acceptance,json(previous),member.cwd,'queued',now(),now());this.db.prepare("UPDATE requirements SET status='running',delivery=NULL,error=NULL,updated_at=? WHERE id=?").run(now(),requirementId);this.refreshStatus(groupId);this.addMessage(groupId,requirementId,'user','你',feedback,{type:'change-request'});return this.getGroup(groupId,requirementId);}
  reassignTask(groupId:string,taskId:string,memberId:string){const task=this.db.prepare('SELECT * FROM tasks WHERE id=? AND group_id=?').get(taskId,groupId),member=this.db.prepare('SELECT * FROM group_members WHERE id=? AND group_id=? AND active=1').get(memberId,groupId);if(!task||!member)throw Object.assign(new Error('任务或目标成员不存在'),{status:404});if(task.status!=='queued'||task.attempt>0||parse(task.decision_json))throw Object.assign(new Error('仅尚未执行的排队任务可以改派；已执行任务请在原会话继续或先取消'),{status:409});if(task.member_id===memberId)return this.getGroup(groupId,task.requirement_id);const previous=this.db.prepare('SELECT name FROM group_members WHERE id=?').get(task.member_id);this.transaction(()=>{this.db.prepare('UPDATE tasks SET member_id=?,cwd=?,updated_at=? WHERE id=?').run(memberId,member.cwd,now(),taskId);this.addMessage(groupId,task.requirement_id,'system','Omega',`手动改派：${previous?.name||'成员'} → ${member.name}；原问题与依赖保持不变。`,{type:'assignment',taskId,memberId,previousMemberId:task.member_id});});return this.getGroup(groupId,task.requirement_id);}
  retry(groupId:string,requirementId:string){const req=this.db.prepare('SELECT * FROM requirements WHERE id=? AND group_id=?').get(requirementId,groupId);if(req?.pause_kind==='budget')throw Object.assign(new Error('请通过调整预算继续，不能使用执行重试解除预算暂停'),{status:409});if(!req||req.status!=='paused')throw Object.assign(new Error('当前流程不需要重试'),{status:409});const failed=this.db.prepare("SELECT * FROM tasks WHERE requirement_id=? AND status IN ('failed','unknown') ORDER BY position LIMIT 1").get(requirementId);let needsPlanning=false;if(failed?.status==='unknown')throw Object.assign(new Error('请先核对原执行轮次，不能直接重发未知任务'),{status:409});if(failed)this.db.prepare("UPDATE tasks SET status='queued',dispatch_id=NULL,turn_id=NULL,error=NULL,updated_at=? WHERE id=?").run(now(),failed.id);const hasTasks=!!this.db.prepare('SELECT 1 FROM tasks WHERE requirement_id=? LIMIT 1').get(requirementId);if(hasTasks)this.db.prepare("UPDATE requirements SET status='running',error=NULL,updated_at=? WHERE id=?").run(now(),requirementId);else{needsPlanning=true;this.db.prepare("UPDATE requirements SET status='plan_drafting',pause_kind=NULL,error=NULL,updated_at=? WHERE id=?").run(now(),requirementId);}this.refreshStatus(groupId);return{group:this.getGroup(groupId,requirementId),needsPlanning};}
  addMessage(groupId:string,requirementId:string|null,kind:string,author:string,content:any,reference:Row|null=null){this.db.prepare('INSERT INTO group_messages(id,group_id,requirement_id,kind,author,content,reference_json,created_at) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),groupId,requirementId,kind,author,String(content).slice(0,50000),reference?json(reference):null,now());this.touch(groupId);}
}
