import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import path from 'node:path';

const now=()=>new Date().toISOString();
type Row=Record<string,any>;
interface Statement{all(...values:any[]):Row[];get(...values:any[]):Row|undefined;run(...values:any[]):{changes:number}}
interface StoreDb{exec(sql:string):void;prepare(sql:string):Statement;close():void}
const json=(value:any)=>JSON.stringify(value??null);
const parse=(value:any,fallback:any=null):any=>{try{return value==null||value===''?fallback:JSON.parse(value);}catch{return fallback;}};
const clean=(value:any,name:string,max=4000,required=false):string=>{value=typeof value==='string'?value.trim():value==null?'':null;if(value==null||value.length>max||/\u0000/.test(value))throw new Error(`${name}格式不正确或过长`);if(required&&!value)throw new Error(`请填写${name}`);return value;};
const cleanAvatar=(value:any)=>{value=clean(value,'头像',100000);if(!value||/^preset:(?:developer|designer|tester|analyst|operator|coordinator)$/.test(value)||/^data:image\/(?:png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(value))return value;throw new Error('头像格式不正确');};
const overlap=(a:string,b:string)=>{const left=path.resolve(a),right=path.resolve(b);return left===right||left.startsWith(right+path.sep)||right.startsWith(left+path.sep);};
const accessMode=(value:any,title='',objective='')=>{if(value==='read'||value==='write')return value;const content=`${title} ${objective}`;const writes=/修改|实现|开发|修复|新增|创建|删除|写入|更新(?:代码|文件|配置|依赖|数据库|实现)|升级|安装|部署|构建|提交|合并|重构|配置|生成|落地|编码|改造|write|edit|implement|develop|fix|create|delete|update\s+(?:code|files?|config|dependencies|database|implementation)|install|deploy|build|commit|merge|refactor/i,reads=/查询|统计|筛选|复核|审核|分析|调研|检查|核对|盘点|汇总|阅读|查看|确认|检索|query|search|review|audit|analy[sz]e|inspect|check|read|research|summari[sz]e/i;return reads.test(content)&&!writes.test(content)?'read':'write';};
const workspaceConflict=(leftMode:string,rightMode:string)=>leftMode!=='read'||rightMode!=='read';
const terminal=new Set(['completed','accepted','cancelled']);
const groupStatusPriority=['running','finalizing','plan_drafting','awaiting_confirmation','awaiting_acceptance','paused'];

export const GROUP_LIMITS=Object.freeze({maxTasks:8,maxReworks:2,maxRounds:12,taskTimeoutMinutes:45,maxConcurrency:3});

export class GroupStore{
  db:StoreDb;
  constructor(file:string){this.db=new DatabaseSync(file) as StoreDb;this.db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');this.migrate();}
  migrate(){
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS groups(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',cwd TEXT NOT NULL,constraints_text TEXT NOT NULL DEFAULT '',coordinator_thread_id TEXT NOT NULL,summary TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'idle',limits_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS group_members(id TEXT PRIMARY KEY,group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,thread_id TEXT NOT NULL UNIQUE,name TEXT NOT NULL,role TEXT NOT NULL,responsibilities TEXT NOT NULL DEFAULT '',operations TEXT NOT NULL DEFAULT '',skills TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS requirements(id TEXT PRIMARY KEY,group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,content TEXT NOT NULL,acceptance TEXT NOT NULL DEFAULT '',status TEXT NOT NULL,plan_json TEXT,delivery TEXT,coordinator_turn_id TEXT,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,requirement_id TEXT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,position INTEGER NOT NULL,member_id TEXT NOT NULL REFERENCES group_members(id),title TEXT NOT NULL,objective TEXT NOT NULL,acceptance TEXT NOT NULL DEFAULT '',dependencies_json TEXT NOT NULL DEFAULT '[]',cwd TEXT NOT NULL DEFAULT '',access_mode TEXT NOT NULL DEFAULT '',status TEXT NOT NULL,dispatch_id TEXT UNIQUE,turn_id TEXT,result TEXT,error TEXT,attempt INTEGER NOT NULL DEFAULT 0,started_at TEXT,completed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS group_messages(id TEXT PRIMARY KEY,group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,requirement_id TEXT REFERENCES requirements(id) ON DELETE CASCADE,kind TEXT NOT NULL,author TEXT NOT NULL,content TEXT NOT NULL,reference_json TEXT,created_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS group_messages_group_idx ON group_messages(group_id,created_at);
      CREATE INDEX IF NOT EXISTS tasks_requirement_idx ON tasks(requirement_id,position);
      CREATE INDEX IF NOT EXISTS tasks_status_idx ON tasks(status,member_id);
      CREATE INDEX IF NOT EXISTS requirements_group_idx ON requirements(group_id,created_at);
    `);
    this.addColumn('group_members','cwd',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('group_members','project_name',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('group_members','avatar',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('tasks','cwd',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('tasks','access_mode',"TEXT NOT NULL DEFAULT ''");
    this.addColumn('tasks','deadline_at','TEXT');
    this.addColumn('tasks','recovery_checked_at','TEXT');
    this.addColumn('requirements','reply_task_id','TEXT');
    this.db.exec("UPDATE requirements SET status='completed' WHERE status='awaiting_acceptance';");
    this.db.exec("UPDATE group_members SET cwd=(SELECT cwd FROM groups WHERE groups.id=group_members.group_id) WHERE cwd='';UPDATE tasks SET cwd=(SELECT cwd FROM group_members WHERE group_members.id=tasks.member_id) WHERE cwd='';");
    const unknownModes=this.db.prepare("SELECT id,title,objective FROM tasks WHERE access_mode='' OR access_mode IS NULL").all(),setMode=this.db.prepare('UPDATE tasks SET access_mode=? WHERE id=?');for(const task of unknownModes)setMode.run(accessMode('',task.title,task.objective),task.id);
    this.recoverInterrupted();this.repairKnownThreadFailures();this.refreshAllStatuses();
  }
  addColumn(table:string,column:string,type:string){try{this.db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${type}`);}catch(error){if(!/duplicate column/i.test((error as Error).message))throw error;}}
  recoverInterrupted(){const stamp=now();this.db.prepare("UPDATE tasks SET status='unknown',recovery_checked_at=NULL,error=COALESCE(error,'服务重启时任务仍在执行，正在核对原执行轮次'),updated_at=? WHERE status='running'").run(stamp);this.db.prepare("UPDATE requirements SET status='paused',error=COALESCE(error,'服务重启后正在核对未完成流程'),updated_at=? WHERE status IN ('plan_drafting','finalizing') OR id IN (SELECT requirement_id FROM tasks WHERE status='unknown')").run(stamp);}
  repairKnownThreadFailures(){const rows=this.db.prepare("SELECT id FROM tasks WHERE status='unknown' AND (lower(error) LIKE 'thread not found:%' OR lower(error) LIKE '%missing source rollout%' OR lower(error) LIKE '%does not exist%')").all();for(const row of rows)this.failTask(row.id,'成员会话不存在或已无法恢复，请编辑该成员并更换关联会话后重试','failed');}
  close(){this.db.close();}
  roomWindow(groupId:string,{after,question}:{after?:string|null;question?:string|null}={}){
    const cursor=question?this.db.prepare('SELECT rowid FROM group_messages WHERE group_id=? AND requirement_id=? ORDER BY rowid LIMIT 1').get(groupId,question):this.db.prepare('SELECT rowid FROM group_messages WHERE group_id=? AND id=?').get(groupId,after);
    if(!cursor)return [];
    return this.db.prepare('SELECT * FROM group_messages WHERE group_id=? AND rowid>=? ORDER BY rowid LIMIT 120').all(groupId,cursor.rowid+(question?0:1)).map(this.publicMessage);
  }
  roomMessages(groupId:string,before:string|null=null){
    const cursor=before?this.db.prepare('SELECT rowid FROM group_messages WHERE id=? AND group_id=?').get(before,groupId):null;
    return this.db.prepare('SELECT * FROM group_messages WHERE group_id=? AND rowid<? ORDER BY rowid DESC LIMIT 120').all(groupId,cursor?.rowid||Number.MAX_SAFE_INTEGER).reverse().map(this.publicMessage);
  }
  searchMessages(query:string,limit=40){const escaped=`%${query.replace(/[\\%_]/g,value=>'\\'+value)}%`;return this.db.prepare("SELECT gm.*,g.name group_name FROM group_messages gm JOIN groups g ON g.id=gm.group_id WHERE gm.content LIKE ? ESCAPE '\\' OR g.name LIKE ? ESCAPE '\\' ORDER BY gm.created_at DESC LIMIT ?").all(escaped,escaped,limit).map(row=>{const content=String(row.content).replace(/\s+/g,' '),at=content.toLowerCase().indexOf(query.toLowerCase()),start=Math.max(0,at<0?0:at-70);return{scope:'group',id:row.group_id,anchor:row.requirement_id||row.id,title:row.group_name,snippet:(start?'…':'')+content.slice(start,start+220)+(content.length>start+220?'…':''),updatedAt:row.created_at};});}
  unreadAnchor(threadId:string){const binding=this.threadBinding(threadId);if(!binding)return null;if(binding.type==='member')return this.db.prepare("SELECT requirement_id id FROM tasks WHERE member_id=? AND status IN ('running','reviewing') ORDER BY updated_at LIMIT 1").get(binding.memberId)?.id||null;return this.db.prepare("SELECT id FROM requirements WHERE group_id=? AND status IN ('plan_drafting','finalizing','running') ORDER BY updated_at LIMIT 1").get(binding.groupId)?.id||null;}
  taskProgress(threadId:string,turnId:string,itemId:string,content:string){
    const task=this.db.prepare("SELECT t.*,m.name FROM tasks t JOIN group_members m ON m.id=t.member_id WHERE m.thread_id=? AND t.status='running' AND (t.turn_id=? OR t.turn_id IS NULL) LIMIT 1").get(threadId,turnId);
    if(!task||!content)return null;
    const id=`progress:${task.id}:${turnId}:${itemId}`,reference={type:'progress',taskId:task.id,threadId,turnId};
    this.db.prepare('INSERT INTO group_messages(id,group_id,requirement_id,kind,author,content,reference_json,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET content=excluded.content').run(id,task.group_id,task.requirement_id,'member',task.name,String(content).slice(-12000),json(reference),now());
    return task.group_id;
  }
  transaction<T>(fn:()=>T){this.db.exec('BEGIN IMMEDIATE');try{const value=fn();this.db.exec('COMMIT');return value;}catch(error){this.db.exec('ROLLBACK');throw error;}}
  validateGroupInput(input:Row={}){const limits={...GROUP_LIMITS,...(input.limits||{})};if(!Number.isInteger(limits.maxTasks)||limits.maxTasks<1||limits.maxTasks>30)throw new Error('任务上限需为 1–30');if(!Number.isInteger(limits.maxReworks)||limits.maxReworks<0||limits.maxReworks>10)throw new Error('返工上限需为 0–10');if(!Number.isInteger(limits.maxRounds)||limits.maxRounds<1||limits.maxRounds>50)throw new Error('调度轮数需为 1–50');if(!Number.isInteger(limits.taskTimeoutMinutes)||limits.taskTimeoutMinutes<5||limits.taskTimeoutMinutes>720)throw new Error('单任务超时需为 5–720 分钟');if(!Number.isInteger(limits.maxConcurrency)||limits.maxConcurrency<1||limits.maxConcurrency>10)throw new Error('并发上限需为 1–10');return{name:clean(input.name,'群组名称',80,true),description:clean(input.description,'项目说明'),constraints:clean(input.constraints,'项目约束',8000),limits};}
  createGroup(input:Row,coordinatorThreadId:string,cwd:string){const id=randomUUID(),stamp=now(),v=this.validateGroupInput(input),row={id,name:v.name,description:v.description,cwd,constraints_text:v.constraints,coordinator_thread_id:coordinatorThreadId,summary:'',status:'idle',limits_json:json(v.limits),created_at:stamp,updated_at:stamp};this.db.prepare('INSERT INTO groups(id,name,description,cwd,constraints_text,coordinator_thread_id,summary,status,limits_json,created_at,updated_at) VALUES(@id,@name,@description,@cwd,@constraints_text,@coordinator_thread_id,@summary,@status,@limits_json,@created_at,@updated_at)').run(row);this.addMessage(id,null,'system','Omega',`群组“${row.name}”已创建，可从不同项目添加成员会话。`,{threadId:coordinatorThreadId});return this.getGroup(id);}
  setConcurrency(groupId:string,value:any,requirementId:string|null=null){const row=this.db.prepare('SELECT limits_json FROM groups WHERE id=?').get(groupId);if(!row)throw Object.assign(new Error('群组不存在'),{status:404});const maxConcurrency=Number(value);if(!Number.isInteger(maxConcurrency)||maxConcurrency<1||maxConcurrency>10)throw new Error('并发数需为 1–10');const limits={...GROUP_LIMITS,...parse(row.limits_json,{}),maxConcurrency};this.db.prepare('UPDATE groups SET limits_json=?,updated_at=? WHERE id=?').run(json(limits),now(),groupId);this.addMessage(groupId,null,'system','Omega',`群组并发数已调整为 ${maxConcurrency}。`,{type:'concurrency-setting',maxConcurrency});return this.getGroup(groupId,requirementId);}
  aggregateStatus(groupId:string){const rows=this.db.prepare("SELECT status FROM requirements WHERE group_id=? AND status NOT IN ('completed','accepted','cancelled')").all(groupId);if(!rows.length)return'idle';const statuses=new Set(rows.map(row=>row.status));return groupStatusPriority.find(status=>statuses.has(status))||'paused';}
  refreshStatus(groupId:string){const status=this.aggregateStatus(groupId);this.db.prepare('UPDATE groups SET status=?,updated_at=? WHERE id=?').run(status,now(),groupId);return status;}
  refreshAllStatuses(){for(const row of this.db.prepare('SELECT id FROM groups').all())this.refreshStatus(row.id);}
  touch(groupId:string){this.db.prepare('UPDATE groups SET updated_at=? WHERE id=?').run(now(),groupId);}
  listGroups(){return this.db.prepare(`SELECT g.*,(SELECT COUNT(*) FROM group_members m WHERE m.group_id=g.id AND m.active=1) member_count,(SELECT COUNT(*) FROM requirements r WHERE r.group_id=g.id) requirement_count,(SELECT COUNT(*) FROM requirements r WHERE r.group_id=g.id AND r.status NOT IN ('completed','accepted','cancelled')) open_requirement_count,(SELECT COUNT(*) FROM tasks t WHERE t.group_id=g.id AND t.status='running') running_tasks FROM groups g ORDER BY g.updated_at DESC`).all().map(row=>this.publicGroup(row,false));}
  publicGroup(row:Row|undefined,full=true,requirementId:string|null=null):any{if(!row)return null;const limits={...GROUP_LIMITS,...parse(row.limits_json,{})};const group:any={id:row.id,name:row.name,description:row.description,cwd:row.cwd,constraints:row.constraints_text,coordinatorThreadId:row.coordinator_thread_id,summary:row.summary,status:row.status,limits,createdAt:row.created_at,updatedAt:row.updated_at,memberCount:Number(row.member_count||0),requirementCount:Number(row.requirement_count||0),openRequirementCount:Number(row.open_requirement_count||0),runningTasks:Number(row.running_tasks||0)};if(!full)return group;group.members=this.db.prepare('SELECT * FROM group_members WHERE group_id=? AND active=1 ORDER BY created_at').all(row.id).map(this.publicMember);const reqRows=this.db.prepare('SELECT * FROM requirements WHERE group_id=? ORDER BY created_at DESC LIMIT 50').all(row.id);group.requirements=reqRows.map(req=>{const value=this.publicRequirement(req,true);delete value.delivery;delete value.plan;value.tasks=value.tasks.map(({result,...task}:Row)=>task);return value;});const selected=requirementId?reqRows.find(req=>req.id===requirementId):reqRows[0];group.requirement=selected?this.publicRequirement(selected,true):null;group.requirementCount=reqRows.length;group.openRequirementCount=reqRows.filter(req=>!terminal.has(req.status)).length;group.runningTasks=Number(this.db.prepare("SELECT COUNT(*) count FROM tasks WHERE group_id=? AND status='running'").get(row.id)?.count);group.messages=this.roomMessages(row.id);return group;}
  publicMember=(row:Row)=>({id:row.id,groupId:row.group_id,threadId:row.thread_id,name:row.name,role:row.role,avatar:row.avatar||'',responsibilities:row.responsibilities,operations:row.operations,skills:row.skills,cwd:row.cwd,projectName:row.project_name,active:!!row.active,createdAt:row.created_at});
  publicMessage=(row:Row)=>({id:row.id,groupId:row.group_id,requirementId:row.requirement_id,kind:row.kind,author:row.author,content:row.content,reference:parse(row.reference_json),createdAt:row.created_at});
  publicTask=(row:Row)=>({id:row.id,requirementId:row.requirement_id,groupId:row.group_id,position:row.position,memberId:row.member_id,title:row.title,objective:row.objective,acceptance:row.acceptance,dependencies:parse(row.dependencies_json,[]),cwd:row.cwd,accessMode:accessMode(row.access_mode,row.title,row.objective),status:row.status,dispatchId:row.dispatch_id,turnId:row.turn_id,result:row.result,error:row.error,attempt:row.attempt,startedAt:row.started_at,deadlineAt:row.deadline_at,completedAt:row.completed_at,createdAt:row.created_at,updatedAt:row.updated_at});
  publicRequirement(row:Row,withTasks=false):any{const value:any={id:row.id,groupId:row.group_id,content:row.content,acceptance:row.acceptance,replyTaskId:row.reply_task_id,status:row.status,plan:parse(row.plan_json),delivery:row.delivery,coordinatorTurnId:row.coordinator_turn_id,error:row.error,createdAt:row.created_at,updatedAt:row.updated_at};if(withTasks)value.tasks=this.db.prepare('SELECT * FROM tasks WHERE requirement_id=? ORDER BY position').all(row.id).map(this.publicTask);return value;}
  getGroup(id:string,requirementId:string|null=null):any{const row=this.db.prepare('SELECT * FROM groups WHERE id=?').get(id);if(!row)throw Object.assign(new Error('群组不存在'),{status:404});return this.publicGroup(row,true,requirementId);}
  getRequirement(id:string):any{const row=this.db.prepare('SELECT * FROM requirements WHERE id=?').get(id);return row?this.publicRequirement(row,true):null;}
  getTask(id:string):any{const row=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(id);return row?this.publicTask(row):null;}
  recoverableTasks(){return this.db.prepare("SELECT t.*,m.thread_id,g.limits_json FROM tasks t JOIN group_members m ON m.id=t.member_id JOIN groups g ON g.id=t.group_id WHERE t.status='unknown' AND t.turn_id IS NOT NULL AND t.recovery_checked_at IS NULL AND m.active=1 ORDER BY t.updated_at").all().map(row=>({...this.publicTask(row),threadId:row.thread_id,limits:{...GROUP_LIMITS,...parse(row.limits_json,{})}}));}
  reattachTask(taskId:string){const task=this.db.prepare("SELECT requirement_id,group_id FROM tasks WHERE id=? AND status='unknown' AND turn_id IS NOT NULL AND recovery_checked_at IS NULL").get(taskId);if(!task)return false;const stamp=now();this.db.prepare("UPDATE tasks SET status='running',recovery_checked_at=?,error=NULL,updated_at=? WHERE id=? AND status='unknown'").run(stamp,stamp,taskId);this.db.prepare("UPDATE requirements SET status='running',error=NULL,updated_at=? WHERE id=? AND status='paused'").run(stamp,task.requirement_id);this.refreshStatus(task.group_id);return true;}
  resumeRequirementIfRecoverable(requirementId:string){const req=this.db.prepare('SELECT group_id FROM requirements WHERE id=?').get(requirementId);if(!req)return false;const unresolved=this.db.prepare("SELECT 1 FROM tasks WHERE requirement_id=? AND status IN ('unknown','failed') LIMIT 1").get(requirementId);if(unresolved)return false;this.db.prepare("UPDATE requirements SET status='running',error=NULL,updated_at=? WHERE id=? AND status='paused'").run(now(),requirementId);this.refreshStatus(req.group_id);return true;}
  deleteGroup(groupId:string){const group=this.getGroup(groupId);if(this.db.prepare("SELECT 1 FROM tasks WHERE group_id=? AND status='running' LIMIT 1").get(groupId))throw Object.assign(new Error('群组仍有任务正在执行，请先停止任务'),{status:409});this.db.prepare('DELETE FROM groups WHERE id=?').run(groupId);return{id:group.id,name:group.name,coordinatorThreadId:group.coordinatorThreadId,memberThreadIds:group.members.map((member:Row)=>member.threadId)};}
  addMember(groupId:string,input:Row){const group=this.getGroup(groupId);const id=randomUUID(),stamp=now(),memberCwd=input.cwd||group.cwd,values=[groupId,clean(input.threadId,'会话',100,true),clean(input.name,'成员名称',80,true),clean(input.role,'身份',80,true),clean(input.responsibilities,'职责',3000),clean(input.operations,'操作范围',2000),clean(input.skills,'擅长任务',2000),clean(memberCwd,'成员工作目录',2000,true),clean(input.projectName||path.basename(memberCwd),'项目名称',120),cleanAvatar(input.avatar)];try{this.db.prepare('INSERT INTO group_members(id,group_id,thread_id,name,role,responsibilities,operations,skills,cwd,project_name,avatar,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,1,?)').run(id,...values,stamp);}catch(error){if(!/UNIQUE/.test((error as Error).message))throw error;const old=this.db.prepare('SELECT * FROM group_members WHERE thread_id=?').get(input.threadId);if(!old||old.active)throw Object.assign(new Error('该会话已经加入了一个群组'),{status:409});this.db.prepare('UPDATE group_members SET group_id=?,name=?,role=?,responsibilities=?,operations=?,skills=?,cwd=?,project_name=?,avatar=?,active=1,created_at=? WHERE id=?').run(...values.filter((_,i)=>i!==1),stamp,old.id);}this.touch(groupId);this.addMessage(groupId,null,'system','Omega',`已添加成员：${values[2]}（${values[3]}），工作目录 ${values[7]}`,{threadId:input.threadId,memberId:id});return this.getGroup(groupId);}
  updateMember(groupId:string,memberId:string,input:Row,requirementId:string|null=null){const member=this.db.prepare('SELECT * FROM group_members WHERE id=? AND group_id=? AND active=1').get(memberId,groupId);if(!member)throw Object.assign(new Error('成员不存在'),{status:404});const threadId=clean(input.threadId||member.thread_id,'会话',100,true),cwd=clean(input.cwd||member.cwd,'成员工作目录',2000,true),name=clean(input.name,'成员名称',80,true),role=clean(input.role,'身份',80,true),projectName=clean(input.projectName||path.basename(cwd),'项目名称',120),responsibilities=clean(input.responsibilities,'职责',3000),operations=clean(input.operations,'操作范围',2000),skills=clean(input.skills,'擅长任务',2000),avatar=cleanAvatar(input.avatar===undefined?member.avatar:input.avatar),rebinding=threadId!==member.thread_id||cwd!==member.cwd;if(rebinding&&this.db.prepare("SELECT 1 FROM tasks WHERE member_id=? AND status IN ('running','reviewing') LIMIT 1").get(memberId))throw Object.assign(new Error('该成员仍有执行中或待审核任务，暂不能更换会话'),{status:409});try{this.transaction(()=>{this.db.prepare('UPDATE group_members SET thread_id=?,cwd=?,name=?,role=?,project_name=?,responsibilities=?,operations=?,skills=?,avatar=? WHERE id=?').run(threadId,cwd,name,role,projectName,responsibilities,operations,skills,avatar,memberId);if(rebinding)this.db.prepare("UPDATE tasks SET cwd=?,updated_at=? WHERE member_id=? AND status IN ('draft','queued','failed','unknown')").run(cwd,now(),memberId);});}catch(error){if(/UNIQUE/.test((error as Error).message))throw Object.assign(new Error('该会话已经加入了一个群组'),{status:409});throw error;}this.addMessage(groupId,null,'system','Omega',rebinding?`已将成员“${name}”重新绑定到会话 ${threadId}，工作目录 ${cwd}。`:`已更新成员：${name}（${role}）。`,{type:rebinding?'member-rebind':'member-update',memberId,threadId,previousThreadId:rebinding?member.thread_id:undefined});return this.getGroup(groupId,requirementId);}
  removeMember(groupId:string,memberId:string){if(this.db.prepare("SELECT 1 FROM tasks WHERE member_id=? AND status IN ('running','queued','reviewing') LIMIT 1").get(memberId))throw Object.assign(new Error('该成员仍有待执行、执行中或待审核任务'),{status:409});const changed=this.db.prepare('UPDATE group_members SET active=0 WHERE id=? AND group_id=? AND active=1').run(memberId,groupId);if(!changed.changes)throw Object.assign(new Error('成员不存在'),{status:404});this.touch(groupId);this.addMessage(groupId,null,'system','Omega','成员已移出群组。');return this.getGroup(groupId);}
  threadBinding(threadId:string):any{const coordinator=this.db.prepare('SELECT id,name FROM groups WHERE coordinator_thread_id=?').get(threadId);if(coordinator)return{groupId:coordinator.id,groupName:coordinator.name,type:'coordinator'};const member=this.db.prepare('SELECT m.id member_id,m.group_id,g.name FROM group_members m JOIN groups g ON g.id=m.group_id WHERE m.thread_id=? AND m.active=1').get(threadId);return member?{groupId:member.group_id,groupName:member.name,type:'member',memberId:member.member_id}:null;}
  markThreadUnavailable(threadId:string):any{const binding=this.threadBinding(threadId);if(!binding)return null;if(binding.type==='coordinator'){for(const req of this.db.prepare("SELECT id FROM requirements WHERE group_id=? AND status NOT IN ('completed','accepted','cancelled','awaiting_acceptance')").all(binding.groupId))this.failPhase(req.id,'协调者会话已不可用，请恢复会话后继续');}else{for(const req of this.db.prepare("SELECT DISTINCT requirement_id id FROM tasks WHERE member_id=? AND status IN ('queued','running','reviewing')").all(binding.memberId))this.failPhase(req.id,'成员会话已不可用，请恢复会话后继续');}return binding;}
  createRequirement(groupId:string,input:Row):any{const group=this.getGroup(groupId);if(!group.members.length)throw new Error('请先添加至少一个会话成员');const replyTask=input.replyTaskId?this.getTask(input.replyTaskId):null;if(input.replyTaskId&&(!replyTask||replyTask.groupId!==groupId))throw new Error('引用的回答不属于该群组');const id=randomUUID(),stamp=now(),content=clean(input.content,'需求',12000,true),acceptance=clean(input.acceptance,'验收条件',6000);this.db.prepare('INSERT INTO requirements(id,group_id,content,acceptance,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,groupId,content,acceptance,'plan_drafting',stamp,stamp);if(replyTask)this.db.prepare('UPDATE requirements SET reply_task_id=? WHERE id=?').run(replyTask.id,id);this.refreshStatus(groupId);this.addMessage(groupId,id,'user','你',content,{acceptance,replyTaskId:replyTask?.id});return{group:this.getGroup(groupId,id),requirement:this.getRequirement(id)};}
  setPlan(requirementId:string,summary:string,tasks:Row[],coordinatorTurnId:string|null,raw:string):any{const req=this.db.prepare('SELECT * FROM requirements WHERE id=?').get(requirementId);if(!req)throw new Error('需求单不存在');if(req.status!=='plan_drafting')return this.getGroup(req.group_id,requirementId);const group=this.getGroup(req.group_id,requirementId),stamp=now();if(!Array.isArray(tasks)||!tasks.length)throw new Error('协调者没有生成可执行任务');if(tasks.length>group.limits.maxTasks)throw new Error(`任务数超过群组上限 ${group.limits.maxTasks}`);const members=new Map<string,Row>(group.members.map((member:Row)=>[member.id,member]));const normalized:any[]=tasks.map((task,index)=>{const member=members.get(task.memberId);if(!member)throw new Error(`任务“${task.title||index+1}”没有有效负责人`);const indexes=Array.isArray(task.dependsOn)?task.dependsOn:[];for(const value of indexes)if(!Number.isInteger(value)||value<0||value>=index)throw new Error(`任务“${task.title||index+1}”包含无效依赖`);const title=clean(task.title,'任务名称',120,true),objective=clean(task.objective,'任务目标',5000,true);return{id:randomUUID(),memberId:member.id,title,objective,acceptance:clean(task.acceptance,'任务验收要求',3000),dependsOn:indexes,cwd:member.cwd,accessMode:accessMode(task.accessMode,title,objective)};});for(const task of normalized)task.dependencies=task.dependsOn.map((index:any)=>normalized[index].id);this.transaction(()=>{this.db.prepare('DELETE FROM tasks WHERE requirement_id=?').run(requirementId);const insert=this.db.prepare('INSERT INTO tasks(id,requirement_id,group_id,position,member_id,title,objective,acceptance,dependencies_json,cwd,access_mode,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');normalized.forEach((task,index)=>insert.run(task.id,requirementId,req.group_id,index,task.memberId,task.title,task.objective,task.acceptance,json(task.dependencies),task.cwd,task.accessMode,'draft',stamp,stamp));this.db.prepare("UPDATE requirements SET status='awaiting_confirmation',plan_json=?,coordinator_turn_id=?,error=NULL,updated_at=? WHERE id=?").run(json({summary,tasks:normalized}),coordinatorTurnId||null,stamp,requirementId);this.db.prepare('UPDATE groups SET summary=?,updated_at=? WHERE id=?').run(clean(summary,'群组摘要',12000),stamp,req.group_id);});this.refreshStatus(req.group_id);this.addMessage(req.group_id,requirementId,'coordinator','协调者',summary,{threadId:group.coordinatorThreadId,turnId:coordinatorTurnId,type:'plan'});return this.getGroup(req.group_id,requirementId);}
  setDirectPlan(requirementId:string,summary:string,tasks:Row[]){const group=this.setPlan(requirementId,summary,tasks,null,'direct mention');const latest=this.db.prepare('SELECT id,reference_json FROM group_messages WHERE requirement_id=? ORDER BY rowid DESC LIMIT 1').get(requirementId);if(parse(latest?.reference_json)?.type==='plan')this.db.prepare('DELETE FROM group_messages WHERE id=?').run(latest!.id);return this.getGroup(group.id,requirementId);}
  failPhase(requirementId:string,message:string,status='paused'){const req=this.db.prepare('SELECT group_id FROM requirements WHERE id=?').get(requirementId);if(!req)return;this.db.prepare('UPDATE requirements SET status=?,error=?,updated_at=? WHERE id=?').run(status,String(message).slice(0,4000),now(),requirementId);this.refreshStatus(req.group_id);this.addMessage(req.group_id,requirementId,'system','Omega',`协作流程已暂停：${message}`);}
  confirmPlan(groupId:string,requirementId:string,automatic=false){const changed=this.db.prepare("UPDATE requirements SET status='running',error=NULL,updated_at=? WHERE id=? AND group_id=? AND status='awaiting_confirmation'").run(now(),requirementId,groupId);if(!changed.changes)throw Object.assign(new Error('当前计划不能确认，可能已在其他设备处理'),{status:409});this.db.prepare("UPDATE tasks SET status='queued',updated_at=? WHERE requirement_id=? AND status='draft'").run(now(),requirementId);this.refreshStatus(groupId);if(!automatic)this.addMessage(groupId,requirementId,'user','你','已确认执行计划。',{type:'plan-confirmation'});return this.getGroup(groupId,requirementId);}
  updateDraftTask(groupId:string,requirementId:string,input:Row){const req=this.db.prepare('SELECT status FROM requirements WHERE id=? AND group_id=?').get(requirementId,groupId);if(!req||req.status!=='awaiting_confirmation')throw Object.assign(new Error('只能修改等待确认的计划'),{status:409});const task=this.db.prepare('SELECT * FROM tasks WHERE id=? AND requirement_id=?').get(input.taskId,requirementId),member=this.db.prepare('SELECT * FROM group_members WHERE id=? AND group_id=? AND active=1').get(input.memberId||task?.member_id,groupId);if(!task)throw Object.assign(new Error('任务不存在'),{status:404});if(!member)throw new Error('请选择有效的负责人');const title=clean(input.title??task.title,'任务名称',120,true),objective=clean(input.objective??task.objective,'任务目标',5000,true),mode=accessMode(input.accessMode??task.access_mode,title,objective);this.db.prepare('UPDATE tasks SET member_id=?,cwd=?,access_mode=?,title=?,objective=?,acceptance=?,updated_at=? WHERE id=?').run(member.id,member.cwd,mode,title,objective,clean(input.acceptance??task.acceptance,'任务验收要求',3000),now(),task.id);this.touch(groupId);return this.getGroup(groupId,requirementId);}
  runnableTasks(groupId:string){const tasks=this.db.prepare("SELECT t.*,m.thread_id,m.name member_name,m.role member_role,m.responsibilities,m.operations,m.skills FROM tasks t JOIN requirements r ON r.id=t.requirement_id JOIN group_members m ON m.id=t.member_id WHERE t.group_id=? AND t.status='queued' AND r.status='running' AND m.active=1 ORDER BY r.created_at,t.position").all(groupId);const completed=new Set(this.db.prepare("SELECT id FROM tasks WHERE group_id=? AND status='completed'").all(groupId).map(row=>row.id));const busyMembers=new Set(this.db.prepare("SELECT member_id FROM tasks WHERE status='running'").all().map(row=>row.member_id));const running=this.db.prepare("SELECT id,cwd,access_mode FROM tasks WHERE status='running'").all();return tasks.filter(task=>parse(task.dependencies_json,[]).every((id:any)=>completed.has(id))&&!busyMembers.has(task.member_id)&&!running.some(other=>workspaceConflict(other.access_mode,task.access_mode)&&overlap(other.cwd,task.cwd)));}
  nextTask(requirementId:string){return this.db.prepare("SELECT * FROM tasks WHERE requirement_id=? AND status='queued' ORDER BY position LIMIT 1").get(requirementId);}
  nextReview(groupId:string){return this.db.prepare("SELECT t.* FROM tasks t JOIN requirements r ON r.id=t.requirement_id WHERE t.group_id=? AND t.status='reviewing' AND r.status='running' ORDER BY t.updated_at LIMIT 1").get(groupId);}
  nextPlan(groupId:string){return this.db.prepare("SELECT * FROM requirements WHERE group_id=? AND status='plan_drafting' ORDER BY created_at LIMIT 1").get(groupId);}
  nextFinalizable(groupId:string){return this.db.prepare("SELECT r.* FROM requirements r WHERE r.group_id=? AND r.status='running' AND EXISTS(SELECT 1 FROM tasks t WHERE t.requirement_id=r.id) AND NOT EXISTS(SELECT 1 FROM tasks t WHERE t.requirement_id=r.id AND t.status!='completed') ORDER BY r.created_at LIMIT 1").get(groupId);}
  runningCount(groupId:string){return Number(this.db.prepare("SELECT COUNT(*) count FROM tasks WHERE group_id=? AND status='running'").get(groupId)?.count);}
  runningConflict(cwd:string,excludeGroupId:string|null=null,mode='write'){const rows=this.db.prepare("SELECT t.id task_id,t.group_id,g.name,t.cwd,t.access_mode FROM tasks t JOIN groups g ON g.id=t.group_id WHERE t.status='running'").all();const hit=rows.find(row=>(!excludeGroupId||row.group_id!==excludeGroupId)&&workspaceConflict(row.access_mode,mode)&&overlap(row.cwd,cwd));return hit?{taskId:hit.task_id,groupId:hit.group_id,groupName:hit.name,cwd:hit.cwd,accessMode:hit.access_mode}:null;}
  startTask(taskId:string,dispatchId:string,turnId:string|null,timeoutMs=GROUP_LIMITS.taskTimeoutMinutes*60000){const stamp=now(),deadline=new Date(Date.now()+Math.max(1000,timeoutMs)).toISOString();const changed=this.db.prepare("UPDATE tasks SET status='running',dispatch_id=?,turn_id=?,attempt=attempt+1,started_at=?,deadline_at=?,recovery_checked_at=NULL,error=NULL,updated_at=? WHERE id=? AND status IN ('queued','unknown','failed')").run(dispatchId,turnId||null,stamp,deadline,stamp,taskId);if(!changed.changes)throw Object.assign(new Error('任务状态已发生变化'),{status:409});}
  setTaskTurn(taskId:string,turnId:string){this.db.prepare('UPDATE tasks SET turn_id=?,updated_at=? WHERE id=?').run(turnId,now(),taskId);}
  recordTaskResult(taskId:string,result:string,turnId:string|null){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(!task)throw new Error('任务不存在');this.db.prepare("UPDATE tasks SET status='reviewing',result=?,turn_id=COALESCE(?,turn_id),error=NULL,updated_at=? WHERE id=?").run(result,turnId||null,now(),taskId);this.db.prepare("DELETE FROM group_messages WHERE requirement_id=? AND json_extract(reference_json,'$.type')='progress' AND json_extract(reference_json,'$.taskId')=? AND content=?").run(task.requirement_id,taskId,String(result).slice(-12000));const member=this.db.prepare('SELECT * FROM group_members WHERE id=?').get(task.member_id);this.addMessage(task.group_id,task.requirement_id,'member',member?.name||'成员',result,{type:'delivery',taskId,threadId:member?.thread_id,turnId:turnId||task.turn_id});}
  approveTask(taskId:string,review:string,reviewTurnId:string|null){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(!task)throw new Error('任务不存在');this.db.prepare("UPDATE tasks SET status='completed',completed_at=?,error=NULL,updated_at=? WHERE id=? AND status='reviewing'").run(now(),now(),taskId);this.addMessage(task.group_id,task.requirement_id,'coordinator','协调者',review||`任务“${task.title}”验证通过。`,{type:'task-review',taskId,turnId:reviewTurnId});}
  completeTask(taskId:string,result:string,turnId:string|null){const task=this.getTask(taskId);if(task?.status!=='reviewing')this.recordTaskResult(taskId,result,turnId);this.db.prepare("UPDATE tasks SET status='completed',completed_at=?,error=NULL,updated_at=? WHERE id=? AND status='reviewing'").run(now(),now(),taskId);}
  reworkTask(taskId:string,feedback:string,reviewTurnId:string|null){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(!task)throw new Error('任务不存在');const group=this.getGroup(task.group_id,task.requirement_id),rounds=Number(this.db.prepare('SELECT COALESCE(SUM(attempt),0) rounds FROM tasks WHERE requirement_id=?').get(task.requirement_id)?.rounds);if(task.attempt>group.limits.maxReworks||rounds>=group.limits.maxRounds)throw Object.assign(new Error('任务已经达到返工或调度轮数上限'),{status:409});this.db.prepare("UPDATE tasks SET status='queued',error=?,dispatch_id=NULL,turn_id=NULL,updated_at=? WHERE id=?").run(String(feedback).slice(0,4000),now(),taskId);this.addMessage(task.group_id,task.requirement_id,'coordinator','协调者',`任务“${task.title}”需要返工：${feedback}`,{type:'task-review',decision:'rework',taskId,turnId:reviewTurnId});}
  failTask(taskId:string,message:string,status='failed'){const task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(!task)return;this.db.prepare('UPDATE tasks SET status=?,error=?,updated_at=? WHERE id=?').run(status,String(message).slice(0,4000),now(),taskId);this.failPhase(task.requirement_id,`任务“${task.title}”${status==='unknown'?'结果待核对':'失败'}：${message}`);}
  beginFinalize(requirementId:string,turnId:string|null=null){const req=this.db.prepare('SELECT group_id FROM requirements WHERE id=?').get(requirementId);if(!req)throw new Error('需求单不存在');const changed=this.db.prepare("UPDATE requirements SET status='finalizing',coordinator_turn_id=COALESCE(?,coordinator_turn_id),updated_at=? WHERE id=? AND status='running'").run(turnId,now(),requirementId);if(!changed.changes)throw Object.assign(new Error('需求状态已变化'),{status:409});this.refreshStatus(req.group_id);}
  completeDelivery(requirementId:string,delivery:string,turnId:string|null,announce=true){const req=this.db.prepare('SELECT group_id FROM requirements WHERE id=?').get(requirementId);if(!req)throw new Error('需求单不存在');this.db.prepare("UPDATE requirements SET status='completed',delivery=?,coordinator_turn_id=?,error=NULL,updated_at=? WHERE id=?").run(delivery,turnId||null,now(),requirementId);this.refreshStatus(req.group_id);const group=this.getGroup(req.group_id,requirementId);if(announce)this.addMessage(req.group_id,requirementId,'coordinator','协调者',delivery,{type:'delivery-report',threadId:group.coordinatorThreadId,turnId});}
  accept(groupId:string,requirementId:string){const changed=this.db.prepare("UPDATE requirements SET status='accepted',error=NULL,updated_at=? WHERE id=? AND group_id=? AND status='awaiting_acceptance'").run(now(),requirementId,groupId);if(!changed.changes)throw Object.assign(new Error('当前交付不能验收，可能已在其他设备处理'),{status:409});this.refreshStatus(groupId);this.addMessage(groupId,requirementId,'user','你','验收通过。',{type:'acceptance'});return this.getGroup(groupId,requirementId);}
  cancel(groupId:string,requirementId:string){if(this.db.prepare("SELECT 1 FROM tasks WHERE requirement_id=? AND status='running'").get(requirementId))throw Object.assign(new Error('仍有任务执行中，请先停止对应会话'),{status:409});const changed=this.db.prepare("UPDATE requirements SET status='cancelled',updated_at=? WHERE id=? AND group_id=? AND status NOT IN ('accepted','cancelled')").run(now(),requirementId,groupId);if(!changed.changes)throw Object.assign(new Error('需求单不能取消'),{status:409});this.db.prepare("UPDATE tasks SET status='cancelled',updated_at=? WHERE requirement_id=? AND status IN ('draft','queued','failed','unknown')").run(now(),requirementId);this.refreshStatus(groupId);return this.getGroup(groupId,requirementId);}
  requestChanges(groupId:string,requirementId:string,input:Row){const feedback=clean(input.feedback,'修改意见',6000,true),req=this.db.prepare('SELECT * FROM requirements WHERE id=? AND group_id=?').get(requirementId,groupId);if(!req||req.status!=='awaiting_acceptance')throw Object.assign(new Error('当前交付不能发起返工'),{status:409});const group=this.getGroup(groupId,requirementId),member=group.members.find((m:Row)=>/开发|实现|engineer|developer/i.test(m.role))||group.members[0],position=Number(this.db.prepare('SELECT COALESCE(MAX(position),-1)+1 position FROM tasks WHERE requirement_id=?').get(requirementId)?.position),previous=this.db.prepare("SELECT id FROM tasks WHERE requirement_id=? AND status='completed' ORDER BY position").all(requirementId).map(row=>row.id),id=randomUUID();this.db.prepare('INSERT INTO tasks(id,requirement_id,group_id,position,member_id,title,objective,acceptance,dependencies_json,cwd,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,requirementId,groupId,position,member.id,'根据验收意见返工',feedback,req.acceptance,json(previous),member.cwd,'queued',now(),now());this.db.prepare("UPDATE requirements SET status='running',delivery=NULL,error=NULL,updated_at=? WHERE id=?").run(now(),requirementId);this.refreshStatus(groupId);this.addMessage(groupId,requirementId,'user','你',feedback,{type:'change-request'});return this.getGroup(groupId,requirementId);}
  retry(groupId:string,requirementId:string){const req=this.db.prepare('SELECT * FROM requirements WHERE id=? AND group_id=?').get(requirementId,groupId);if(!req||req.status!=='paused')throw Object.assign(new Error('当前流程不需要重试'),{status:409});const failed=this.db.prepare("SELECT * FROM tasks WHERE requirement_id=? AND status IN ('failed','unknown') ORDER BY position LIMIT 1").get(requirementId);let needsPlanning=false;if(failed)this.db.prepare("UPDATE tasks SET status='queued',dispatch_id=NULL,turn_id=NULL,error=NULL,updated_at=? WHERE id=?").run(now(),failed.id);const hasTasks=!!this.db.prepare('SELECT 1 FROM tasks WHERE requirement_id=? LIMIT 1').get(requirementId);if(hasTasks)this.db.prepare("UPDATE requirements SET status='running',error=NULL,updated_at=? WHERE id=?").run(now(),requirementId);else{needsPlanning=true;this.db.prepare("UPDATE requirements SET status='plan_drafting',error=NULL,updated_at=? WHERE id=?").run(now(),requirementId);}this.refreshStatus(groupId);return{group:this.getGroup(groupId,requirementId),needsPlanning};}
  addMessage(groupId:string,requirementId:string|null,kind:string,author:string,content:any,reference:Row|null=null){this.db.prepare('INSERT INTO group_messages(id,group_id,requirement_id,kind,author,content,reference_json,created_at) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),groupId,requirementId,kind,author,String(content).slice(0,50000),reference?json(reference):null,now());this.touch(groupId);}
}
