import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import path from 'node:path';
const FIELDS=['totalTokens','inputTokens','cachedInputTokens','cacheWriteInputTokens','outputTokens','reasoningOutputTokens'] as const;
type Totals=Record<(typeof FIELDS)[number],number|null>;
interface RecordValue{threadId:string;turnId:string;status?:string;startedAt:number|null;completedAt?:number|null;durationMs?:number|null;observedTime?:boolean;base:Totals|null;usage:Totals|null;lastTotal?:Totals}
interface EventValue{method:string;params?:Record<string,any>}
const number=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null;
const totals=(value:Record<string,unknown>|null|undefined):Totals|null=>value&&FIELDS.every(key=>number(value[key])!==null||!['inputTokens','outputTokens','totalTokens'].includes(key))?Object.fromEntries(FIELDS.map(key=>[key,number(value[key])])) as Totals:null;
const milliseconds=(value:unknown)=>number(value)===null?null:(value as number)*1000;
export class TurnMetrics{
  directory:string;now:()=>number;cache=new Map<string,RecordValue>();latest=new Map<string,Totals>();
  constructor(directory:string,now=Date.now){this.directory=directory;this.now=now;}
  async initialize(){await mkdir(this.directory,{recursive:true,mode:0o700});}
  file(threadId:string,turnId:string){if(![threadId,turnId].every(value=>typeof value==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(value)))throw Error('Invalid metric identifier');return path.join(this.directory,threadId+'__'+turnId+'.json');}
  remember<T>(map:Map<string,T>,key:string,value:T){map.delete(key);map.set(key,value);if(map.size>256){const oldest=map.keys().next().value;if(oldest!==undefined)map.delete(oldest);}}
  seed(threadId:string){this.remember(this.latest,threadId,Object.fromEntries(FIELDS.map(key=>[key,0])) as Totals);}
  async read(threadId:string,turnId:string):Promise<RecordValue|null>{const file=this.file(threadId,turnId);if(this.cache.has(file)){const record=this.cache.get(file)!;this.remember(this.cache,file,record);return record;}try{const record=JSON.parse(await readFile(file,'utf8')) as RecordValue;this.remember(this.cache,file,record);return record;}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return null;throw error;}}
  async observe(event:EventValue){const{method,params:p={}}=event;if(!['turn/started','turn/completed','thread/tokenUsage/updated'].includes(method))return null;const turnId=p.turn?.id||p.turnId,threadId=p.threadId;if(typeof threadId!=='string'||typeof turnId!=='string')return null;let record=await this.read(threadId,turnId);const previous=record?JSON.stringify(record):null;if(method==='turn/started'){if(!record)record={threadId,turnId,status:'inProgress',startedAt:milliseconds(p.turn.startedAt)??this.now(),observedTime:milliseconds(p.turn.startedAt)===null,base:this.latest.get(threadId)||null,usage:null};}else if(method==='thread/tokenUsage/updated'){const total=totals(p.tokenUsage?.total);if(!total)return null;if(record?.base){const floor=record.lastTotal||record.base,reset=FIELDS.some(key=>total[key]!==null&&floor[key]!==null&&total[key]!<floor[key]!);if(reset){record.base=null;record.usage=null;}else record.usage=Object.fromEntries(FIELDS.map(key=>[key,total[key]!==null&&record!.base![key]!==null?total[key]!-record!.base![key]!:null])) as Totals;}if(record)record.lastTotal=total;this.remember(this.latest,threadId,total);if(!record)return null;}else{record||={threadId,turnId,startedAt:milliseconds(p.turn.startedAt),base:null,usage:null};record.status=p.turn.status;record.completedAt=milliseconds(p.turn.completedAt)??this.now();record.durationMs=number(p.turn.durationMs)??(record.startedAt!==null?Math.max(0,record.completedAt-record.startedAt):null);}if(previous!==JSON.stringify(record)){const file=this.file(threadId,turnId);await writeFile(file+'.tmp',JSON.stringify(record),{mode:0o600});await rename(file+'.tmp',file);this.remember(this.cache,file,record);}return{threadId,turnId,metrics:this.present(record)};}
  present(record:RecordValue|null,turn:Record<string,any>={}){const running=(turn.status||record?.status)==='inProgress',started=milliseconds(turn.startedAt)??record?.startedAt??null,completed=milliseconds(turn.completedAt)??record?.completedAt??null,durationMs=number(turn.durationMs)??record?.durationMs??(!running&&started!==null&&completed!==null?Math.max(0,completed-started):null),elapsedMs=running&&started!==null?Math.max(0,this.now()-started):durationMs;return{running,elapsedMs:elapsedMs??null,durationMs:durationMs??null,observedTime:!!record?.observedTime,usage:record?.usage||null};}
  async view(threadId:string,turn:{id:string}&Record<string,any>){return this.present(await this.read(threadId,turn.id),turn);}
}
