import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import path from 'node:path';
interface Settings{model:string|null;effort:string|null;revision:number}
interface Model{model:string;displayName:string;description:string;supportedReasoningEfforts:Array<{reasoningEffort:string}>;defaultReasoningEffort:string|null;inputModalities:string[]}
interface Page{data?:Array<Partial<Model>&{hidden?:boolean}>;nextCursor?:string}
type Request=(method:string,params:Record<string,unknown>)=>Promise<Page>;
const fail=(message:string,status=400)=>Object.assign(new Error(message),{status});
export class ModelSettings{
  directory:string;request:Request;queue:Promise<unknown>=Promise.resolve();catalog:{time:number;models:Model[]}|null=null;inflight:Promise<Model[]>|null=null;
  constructor(directory:string,request:Request){this.directory=directory;this.request=request;}
  async initialize(){await mkdir(this.directory,{recursive:true,mode:0o700});}
  file(id:string){if(typeof id!=='string'||!/^[a-f0-9-]{36}$/i.test(id))throw fail('无效的会话 ID');return path.join(this.directory,id+'.json');}
  async read(id:string):Promise<Settings>{try{return JSON.parse(await readFile(this.file(id),'utf8')) as Settings;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;return{model:null,effort:null,revision:0};}}
  async models(force=false):Promise<Model[]>{if(!force&&this.catalog&&Date.now()-this.catalog.time<60000)return this.catalog.models;if(this.inflight)return this.inflight;this.inflight=(async()=>{const models:Model[]=[],cursors=new Set<string>();let cursor:string|undefined;do{const page=await this.request('model/list',{limit:100,includeHidden:false,...(cursor?{cursor}:{})});if(!Array.isArray(page.data))throw fail('模型列表暂不可用，请稍后重试',503);for(const value of page.data){if(value.hidden||typeof value.model!=='string'||models.some(item=>item.model===value.model))continue;models.push({model:value.model,displayName:value.displayName||value.model,description:value.description||'',supportedReasoningEfforts:(value.supportedReasoningEfforts||[]).filter(item=>typeof item.reasoningEffort==='string') as Array<{reasoningEffort:string}>,defaultReasoningEffort:value.defaultReasoningEffort||null,inputModalities:value.inputModalities||['text','image']});}cursor=page.nextCursor;if(cursor&&cursors.has(cursor))throw fail('模型列表分页异常',503);if(cursor)cursors.add(cursor);if(cursors.size>20)throw fail('模型列表过大',503);}while(cursor);this.catalog={time:Date.now(),models};return models;})();try{return await this.inflight;}finally{this.inflight=null;}}
  async resolve(settings:Pick<Settings,'model'|'effort'>,hasImages=false){if(settings.model===null){if(settings.effort!==null)throw fail('请先选择模型，再设置推理等级');return{};}const model=(await this.models()).find(value=>value.model===settings.model);if(!model)throw fail('此模型已不在可用列表中，请重新选择');const effort=settings.effort??model.defaultReasoningEffort;if(effort!==null&&!model.supportedReasoningEfforts.some(value=>value.reasoningEffort===effort))throw fail('该模型不支持所选推理等级，请重新选择');if(hasImages&&!model.inputModalities.includes('image'))throw fail('所选模型不支持图片，请切换模型或移除图片');return{model:model.model,...(effort!==null?{effort}:{})};}
  save(id:string,settings:Pick<Settings,'model'|'effort'>,expectedRevision:number,check:()=>void|Promise<void>=()=>{}){const operation=this.queue.then(async()=>{this.file(id);if(!settings||!(settings.model===null||typeof settings.model==='string')||!(settings.effort===null||typeof settings.effort==='string'))throw fail('无效的模型设置');const current=await this.read(id);if(!Number.isSafeInteger(expectedRevision)||current.revision!==expectedRevision)throw fail('设置已在其他设备修改，请重新打开后再保存',409);await this.resolve(settings);await check();const next={model:settings.model,effort:settings.effort,revision:current.revision+1};await writeFile(this.file(id)+'.tmp',JSON.stringify(next),{mode:0o600});await rename(this.file(id)+'.tmp',this.file(id));return next;});this.queue=operation.catch(()=>{});return operation;}
}
