import {test} from 'node:test';
import assert from 'node:assert/strict';
import {GroupStore} from '../groups-store.mjs';
import {GroupOrchestrator,memberTaskPrompt} from '../group-orchestrator.mjs';

function fixture(input={}){const store=new GroupStore(':memory:');let group=store.createGroup({name:'预算'},'coord','/work');for(const name of ['开发','测试'])group=store.addMember(group.id,{threadId:name,name,role:name,cwd:'/work/'+name});const o=new GroupOrchestrator({store,isThreadActive:()=>false,startTurn:async()=>({turn:{id:'unused'}}),waitTurn:async()=>({status:'completed'}),readTurnText:async()=>''});o.suspend(group.id);const req=o.submit(group.id,{content:'@开发 检查版本',collaborationMode:'handoff',maxRounds:1,...input}).requirement;const finish=()=>{const task=store.getRequirement(req.id).tasks[0];store.startTask(task.id,'d','t');o.finishMemberTurn(task.id,`已查明版本<omega-handoff>${JSON.stringify({tasks:[{memberId:group.members[1].id,objective:'复核版本'}]})}</omega-handoff>`,'t');};return{store,group,o,req,finish};}

test('round limit retains pending handoff; extending resumes without repeating completed work',()=>{const f=fixture();try{f.finish();const req=f.store.getRequirement(f.req.id);assert.equal(req.status,'paused');assert.equal(req.tasks.length,2);assert.equal(req.tasks[0].status,'completed');assert.equal(f.store.runnableTasks(f.group.id).length,0);f.store.extendBudget(f.group.id,req.id,{maxRounds:3,maxMinutes:0,maxTokens:0});assert.equal(f.store.runnableTasks(f.group.id)[0].id,req.tasks[1].id);assert.equal(f.store.getTask(req.tasks[0].id).attempt,1);}finally{f.store.close()}});

test('token snapshots are monotonic, do not double count and pause subsequent work',()=>{const f=fixture({maxRounds:10,maxTokens:100});try{f.finish();f.store.observeUsage('开发','t',90);f.store.observeUsage('开发','t',90);assert.equal(f.store.budgetUsage(f.req.id).tokens,90);f.store.observeUsage('开发','t',110);f.store.observeUsage('开发','t',80);assert.equal(f.store.budgetUsage(f.req.id).tokens,110);assert.equal(f.store.getRequirement(f.req.id).status,'paused');assert.throws(()=>f.store.extendBudget(f.group.id,f.req.id,{maxRounds:10,maxTokens:100,maxMinutes:0}),/仍不足/);f.store.extendBudget(f.group.id,f.req.id,{maxRounds:10,maxTokens:200,maxMinutes:0});assert.equal(f.store.getRequirement(f.req.id).status,'running');}finally{f.store.close()}});

test('elapsed budget blocks later dispatch while missing token data remains explicitly unknown',()=>{const f=fixture({maxRounds:10,maxMinutes:1,maxTokens:100});try{f.finish();assert.equal(f.store.budgetUsage(f.req.id).tokens,null);f.store.db.prepare('UPDATE requirements SET budget_started_at=? WHERE id=?').run(new Date(Date.now()-120000).toISOString(),f.req.id);f.store.enforceBudget(f.req.id);assert.match(f.store.getRequirement(f.req.id).error,/时间预算/);}finally{f.store.close()}});

test('public task dependency and access fields generate compact read-only handoff prompts',()=>{const f=fixture();try{f.finish();const req=f.store.getRequirement(f.req.id),task=req.tasks[1],member=f.group.members[1];const prompt=memberTaskPrompt(f.group,req,member,task);assert.match(prompt,/已查明版本/);assert.match(prompt,/只读，直接回复/);assert.ok(prompt.length<2500);assert.deepEqual(task.dependencies,[req.tasks[0].id]);}finally{f.store.close()}});

test('sibling project directories execute concurrently despite identical responsibility descriptions',()=>{const f=fixture();try{const second=f.o.submit(f.group.id,{content:'@测试 修改项目'}).requirement;f.store.startTask(f.req.tasks[0].id,'d','t');assert.ok(f.store.runnableTasks(f.group.id).some(t=>t.id===second.tasks[0].id));assert.equal(f.store.runningConflict('/work/测试',null,'write'),null);assert.ok(f.store.runningConflict('/work',null,'write'));}finally{f.store.close()}});

test('discussion ends when every member repeats their previous answer',()=>{const f=fixture();try{const req=f.o.submit(f.group.id,{content:'比较方案',collaborationMode:'discussion',maxRounds:10}).requirement;for(let round=1;round<=2;round++){const tasks=f.store.getRequirement(req.id).tasks.filter(t=>t.round===round);for(const task of tasks){f.store.startTask(task.id,'d'+task.id,'t'+task.id);f.o.finishMemberTurn(task.id,'仍建议原方案','t'+task.id);}}assert.equal(f.store.getRequirement(req.id).tasks.length,4);assert.ok(f.store.getGroup(f.group.id).messages.some(m=>m.reference?.type==='discussion-no-progress'));}finally{f.store.close()}});

test('dispatch uses member project directory, not coordinator parent directory',async()=>{const f=fixture();try{let execution;f.o.startTurn=async(_thread,_prompt,_id,value)=>{execution=value;return{turn:{id:'t'}}};f.o.readTurnText=async()=>'已完成';await f.o.dispatchTask(f.group.id,f.store.runnableTasks(f.group.id)[0]);assert.equal(execution.cwd,'/work/开发');assert.equal(execution.accessMode,'read');}finally{f.store.close()}});
