import {test} from 'node:test';
import assert from 'node:assert/strict';
import {GroupStore} from '../groups-store.mjs';
import {GroupOrchestrator} from '../group-orchestrator.mjs';
import {findTurn} from '../src/server/turn-lookup.ts';

function fixture(){const store=new GroupStore(':memory:');let group=store.createGroup({name:'恢复边界'},'coord','/work');for(const name of ['开发','测试'])group=store.addMember(group.id,{threadId:name,name,role:name,cwd:'/work/'+name});let starts=0;const o=new GroupOrchestrator({store,isThreadActive:()=>false,startTurn:async()=>{starts++;return{turn:{id:'turn'}}},waitTurn:async()=>({status:'completed'}),readTurnText:async()=>'完成结果',inspectTurn:async()=>({id:'turn',status:'completed'})});o.suspend(group.id);return{store,group,o,starts:()=>starts};}

test('old questions dispatch and finalize independently of the 50-row display window',async()=>{const f=fixture();try{const old=f.o.submit(f.group.id,{content:'@开发 查询老问题'}).requirement;f.store.db.prepare('UPDATE requirements SET created_at=? WHERE id=?').run('2000-01-01',old.id);for(let i=0;i<60;i++)f.o.submit(f.group.id,{content:'@测试 查询 '+i});assert.equal(f.store.getGroup(f.group.id).requirements.length,50);const selected=f.store.getGroup(f.group.id,old.id);assert.equal(selected.requirement.id,old.id);assert.ok(selected.requirements.some(r=>r.id===old.id));assert.equal(selected.requirementCount,61);assert.equal(selected.openRequirementCount,61);await f.o.dispatchTask(f.group.id,f.store.runnableTasks(f.group.id).find(t=>t.id===old.tasks[0].id));await f.o.finalize(f.group.id,old.id);assert.equal(f.store.getRequirement(old.id).status,'completed');assert.equal(f.starts(),1);const other=f.store.createGroup({name:'其它'},'coord2','/other');assert.equal(f.store.getGroup(other.id,old.id).requirement,null);}finally{f.store.close()}});

test('turn lookup finds older pages and refuses repeating cursors',async()=>{const calls=[];const turn=await findTurn({request:async(_method,p)=>{calls.push(p.cursor);return p.cursor?{data:[{id:'old',status:'completed'}],nextCursor:null}:{data:[{id:'latest'}],nextCursor:'page2'}}},'thread','old');assert.equal(turn.id,'old');assert.deepEqual(calls,[null,'page2']);await assert.rejects(findTurn({request:async()=>({data:[],nextCursor:'loop'})},'thread','old'),/游标异常/);assert.equal(await findTurn({request:async()=>({data:[],nextCursor:null})},'thread','absent'),null);});

test('expired deadline does not hide a completed original turn',async()=>{const f=fixture();try{const req=f.o.submit(f.group.id,{content:'@开发 查询'}).requirement,task=req.tasks[0];f.store.startTask(task.id,'d','turn');f.store.db.prepare('UPDATE tasks SET deadline_at=? WHERE id=?').run('2000-01-01',task.id);f.store.recoverInterrupted();await f.o.resume();assert.equal(f.store.getTask(task.id).status,'completed');assert.equal(f.starts(),0);}finally{f.store.close()}});

test('expired still-running turn remains unknown without restarting execution',async()=>{const f=fixture();try{const req=f.o.submit(f.group.id,{content:'@开发 查询'}).requirement,task=req.tasks[0];f.store.startTask(task.id,'d','turn');f.store.db.prepare('UPDATE tasks SET deadline_at=? WHERE id=?').run('2000-01-01',task.id);f.o.inspectTurn=async()=>({id:'turn',status:'inProgress'});f.store.recoverInterrupted();await f.o.resume();assert.equal(f.store.getTask(task.id).status,'unknown');assert.equal(f.store.getRequirement(req.id).pauseKind,'recovery');assert.equal(f.starts(),0);}finally{f.store.close()}});

test('budget pause survives restart recovery and requires explicit budget extension',async()=>{const f=fixture();try{const req=f.o.submit(f.group.id,{content:'@开发 @测试 查询',maxTokens:1}).requirement,task=req.tasks[0];f.store.startTask(task.id,'d','turn');f.store.observeUsage('开发','turn',2);assert.equal(f.store.getRequirement(req.id).pauseKind,'budget');f.store.recoverInterrupted();await f.o.resume();assert.equal(f.store.getTask(task.id).status,'completed');assert.equal(f.store.getRequirement(req.id).status,'paused');assert.equal(f.store.getRequirement(req.id).pauseKind,'budget');assert.equal(f.store.runnableTasks(f.group.id).length,0);assert.throws(()=>f.store.retry(f.group.id,req.id),/调整预算/);f.store.extendBudget(f.group.id,req.id,{maxRounds:3,maxTokens:10,maxMinutes:0});assert.equal(f.store.getRequirement(req.id).status,'running');assert.equal(f.store.getRequirement(req.id).pauseKind,null);}finally{f.store.close()}});

test('pause classification does not depend on error wording',()=>{const f=fixture();try{const req=f.o.submit(f.group.id,{content:'@开发 查询'}).requirement;f.store.failPhase(req.id,'已达到某个外部服务的错误条件');assert.equal(f.store.getRequirement(req.id).pauseKind,'execution');f.store.extendBudget(f.group.id,req.id,{maxRounds:3,maxTokens:0,maxMinutes:0});assert.equal(f.store.getRequirement(req.id).status,'paused');f.store.resumeRequirementIfRecoverable(req.id);assert.equal(f.store.getRequirement(req.id).status,'paused');}finally{f.store.close()}});

test('answering a decision cannot release a simultaneous budget pause',()=>{const f=fixture();try{const req=f.o.submit(f.group.id,{content:'@开发 @测试 查询',maxTokens:1}).requirement,task=req.tasks[0];f.store.startTask(task.id,'d','turn');f.store.observeUsage('开发','turn',2);f.store.recordTaskDecision(task.id,'请决定','turn',{title:'选择',question:'选哪个？',options:[{id:'a',label:'方案 A'}]});const decision=f.store.getTask(task.id).decision;f.store.resolveDecision(f.group.id,task.id,{decisionId:decision.id,choiceId:'a'});assert.equal(f.store.getTask(task.id).status,'queued');assert.equal(f.store.getRequirement(req.id).status,'paused');assert.equal(f.store.getRequirement(req.id).pauseKind,'budget');assert.equal(f.store.runnableTasks(f.group.id).length,0);}finally{f.store.close()}});
