import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {GroupStore} from '../groups-store.mjs';
import {GroupOrchestrator} from '../group-orchestrator.mjs';

function fixture(){const store=new GroupStore(':memory:');let group=store.createGroup({name:'可靠协作'},'coord','/work');for(const name of ['开发','测试'])group=store.addMember(group.id,{threadId:name,name,role:name,cwd:`/work/${name}`});let starts=0;const o=new GroupOrchestrator({store,isThreadActive:()=>false,startTurn:async()=>{starts++;return{turn:{id:'new'}}},waitTurn:async()=>({status:'completed'}),readTurnText:async()=>'已完成',lookupDispatch:id=>id==='saved'?'original':null});o.suspend(group.id);const req=o.submit(group.id,{content:'@开发 查询版本'}).requirement;return{store,group,o,req,task:req.tasks[0],starts:()=>starts};}

test('unknown work reserves its member but unrelated members can still proceed',()=>{const f=fixture();try{f.store.startTask(f.task.id,'uncertain',null);f.store.recoverInterrupted();const same=f.o.submit(f.group.id,{content:'@开发 查询另一个版本'}).requirement;const other=f.o.submit(f.group.id,{content:'@测试 查询版本'}).requirement;assert.match(f.store.getTask(same.tasks[0].id).queueReason,/核对/);const ids=f.store.runnableTasks(f.group.id).map(t=>t.id);assert.ok(!ids.includes(same.tasks[0].id));assert.ok(ids.includes(other.tasks[0].id));}finally{f.store.close()}});

test('question panel receives decision, reassignment and recovery actions',()=>{const source=readFileSync(new URL('../client/src/group-room.ts',import.meta.url),'utf8');assert.match(source,/decide:onDecision/);assert.match(source,/action:'reassign'/);assert.match(source,/action:'retry'/);const client=readFileSync(new URL('../client/src/groups.ts',import.meta.url),'utf8');assert.match(client,/decisionId:target.decision.id/);});

test('restart recovers acknowledged dispatch without starting another turn',async()=>{const f=fixture();try{f.store.startTask(f.task.id,'saved',null);f.store.recoverInterrupted();await f.o.resume();assert.equal(f.store.getTask(f.task.id).status,'completed');assert.equal(f.store.getTask(f.task.id).turnId,'original');assert.equal(f.starts(),0);}finally{f.store.close()}});

test('unknown unacknowledged dispatch cannot be blindly retried',async()=>{const f=fixture();try{f.store.startTask(f.task.id,'uncertain',null);f.store.recoverInterrupted();await assert.rejects(f.o.retry(f.group.id,f.req.id),/不能安全重发/);assert.throws(()=>f.store.retry(f.group.id,f.req.id),/不能直接重发/);assert.equal(f.store.getTask(f.task.id).dispatchId,'uncertain');assert.equal(f.starts(),0);}finally{f.store.close()}});

test('queued reassignment preserves task and dependency identity and records an audit message',()=>{const f=fixture();try{f.store.reassignTask(f.group.id,f.task.id,f.group.members[1].id);const task=f.store.getTask(f.task.id);assert.equal(task.memberId,f.group.members[1].id);assert.equal(task.cwd,'/work/测试');assert.equal(task.objective,f.task.objective);assert.deepEqual(task.dependencies,f.task.dependencies);assert.ok(f.store.getGroup(f.group.id).messages.some(m=>m.reference?.type==='assignment'));f.store.startTask(task.id,'d','t');assert.throws(()=>f.store.reassignTask(f.group.id,task.id,f.group.members[0].id),/仅尚未执行/);}finally{f.store.close()}});

test('stale and double decision submissions cannot queue another execution',()=>{const f=fixture();try{f.store.startTask(f.task.id,'d','t');f.store.recordTaskDecision(f.task.id,'请选择','t',{title:'实现方案',question:'选哪个？',options:[{id:'a',label:'方案 A'},{id:'b',label:'方案 B'}]});const decision=f.store.getTask(f.task.id).decision;assert.throws(()=>f.store.resolveDecision(f.group.id,f.task.id,{decisionId:'old',choiceId:'a'}),/决策已更新/);f.store.resolveDecision(f.group.id,f.task.id,{decisionId:decision.id,choiceId:'a'});assert.equal(f.store.getTask(f.task.id).memberId,f.task.memberId);assert.equal(f.store.getTask(f.task.id).status,'queued');assert.throws(()=>f.store.resolveDecision(f.group.id,f.task.id,{decisionId:decision.id,choiceId:'a'}),/已经处理/);f.store.startTask(f.task.id,'new','new-turn');f.o.finishMemberTurn(f.task.id,'迟到结果','t');assert.equal(f.store.getTask(f.task.id).status,'running');}finally{f.store.close()}});
