import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {GroupStore} from '../groups-store.mjs';
import {GroupOrchestrator} from '../group-orchestrator.mjs';
import {handoffFiles} from '../src/server/handoff-files.ts';

test('unknown execution cannot be rebound to another thread before reconciliation',async()=>{const f=await fixture();try{f.store.failTask(f.task.id,'连接中断','unknown');const member=f.group.members[0];assert.throws(()=>f.store.updateMember(f.group.id,member.id,{...member,threadId:'replacement'}),/待核对/);f.store.updateMember(f.group.id,member.id,{...member,name:'更新名称'});assert.equal(f.store.getGroup(f.group.id).members[0].threadId,member.threadId);}finally{await f.close()}});

test('cancellation during file preparation never dispatches or consumes context',async()=>{const f=await fixture();try{const original=f.o.handoffFiles;f.o.handoffFiles=async tasks=>{f.store.cancel(f.group.id,f.req.id);return original(tasks)};await f.o.dispatchTask(f.group.id,f.store.runnableTasks(f.group.id).find(t=>t.id===f.task.id));assert.equal(f.starts(),0);assert.equal(f.store.getTask(f.task.id).status,'cancelled');assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM group_topic_reads').get().n,0);assert.equal(f.o.runningTasks.size,0);}finally{await f.close()}});

test('stale cancelled dispatch releases scheduler tracking without starting',async()=>{const f=await fixture();try{const raw=f.store.runnableTasks(f.group.id).find(t=>t.id===f.task.id);f.store.cancel(f.group.id,f.req.id);await f.o.dispatchTask(f.group.id,raw);assert.equal(f.starts(),0);assert.equal(f.o.runningTasks.size,0);assert.equal(f.store.getTask(f.task.id).status,'cancelled');}finally{await f.close()}});

async function fixture(){const dir=await mkdtemp(path.join(tmpdir(),'omega-topic-context-')),store=new GroupStore(':memory:');let group=store.createGroup({name:'话题'},'coord','/work');group=store.addMember(group.id,{threadId:'owner',name:'开发',role:'开发',cwd:'/work/project'});let starts=0,prompt='';const o=new GroupOrchestrator({store,isThreadActive:()=>false,startTurn:async(_thread,text)=>{starts++;prompt=text;return{turn:{id:'turn'}}},waitTurn:async()=>({status:'completed'}),readTurnText:async()=>'完成',handoffFiles:tasks=>handoffFiles(dir,tasks)});o.suspend(group.id);const first=o.submit(group.id,{content:'@开发 原问题'}).requirement;const long='开头要求\n'+'细节'.repeat(6000)+'\n中间必须保留的参数\n'+'资料'.repeat(6000)+'\n末尾约束';store.addMessage(group.id,first.id,'member','其他成员',long);store.addMessage(group.id,first.id,'user','你','后续补充');const req=o.submit(group.id,{content:'继续处理',replyTaskId:first.tasks[0].id}).requirement,task=req.tasks[0];return{store,o,group,req,task,long,starts:()=>starts,prompt:()=>prompt,close:async()=>{store.close();await rm(dir,{recursive:true,force:true})}};}

test('long topic messages include complete files and following short messages; acknowledge only after dispatch',async()=>{const f=await fixture();try{const raw=f.store.topicContext(f.task.id);assert.equal(raw.files.length,1);assert.equal(raw.files[0].result,f.long);assert.ok(raw.text.length<10000);assert.match(raw.text,/后续补充/);const context=await f.o.prepareTopicContext(f.task.id);const file=JSON.parse(context.text.match(/完整原文文件：(.*)/)[1]);assert.equal(await readFile(file,'utf8'),f.long);assert.equal(f.store.topicContext(f.task.id).cursor,raw.cursor);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM group_topic_reads').get().n,0);await f.o.dispatchTask(f.group.id,f.store.runnableTasks(f.group.id).find(t=>t.id===f.task.id));assert.equal(f.starts(),1);assert.ok(f.prompt().includes(file));assert.equal(f.store.topicContext(f.task.id).files.length,0);assert.equal(f.store.getTask(f.task.id).status,'completed');}finally{await f.close()}});

test('file failure never starts the model or advances the cursor, and remains retryable',async()=>{const f=await fixture();try{f.o.handoffFiles=async()=>{throw Error('磁盘写入失败')};await f.o.dispatchTask(f.group.id,f.store.runnableTasks(f.group.id).find(t=>t.id===f.task.id));assert.equal(f.starts(),0);assert.equal(f.store.getTask(f.task.id).status,'failed');assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM group_topic_reads').get().n,0);assert.equal(f.store.topicContext(f.task.id).files[0].result,f.long);f.store.retry(f.group.id,f.req.id);assert.equal(f.store.getTask(f.task.id).status,'queued');}finally{await f.close()}});

test('missing file references and unacknowledged turn starts cannot consume long messages',async()=>{const f=await fixture();try{const original=f.o.handoffFiles;f.o.handoffFiles=async()=>({});await assert.rejects(f.o.prepareTopicContext(f.task.id),/未准备好/);f.o.handoffFiles=original;f.o.startTurn=async()=>{throw Error('连接中断')};await f.o.dispatchTask(f.group.id,f.store.runnableTasks(f.group.id).find(t=>t.id===f.task.id));assert.equal(f.store.getTask(f.task.id).status,'unknown');assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM group_topic_reads').get().n,0);assert.equal(f.store.topicContext(f.task.id).files[0].result,f.long);}finally{await f.close()}});
