import {useEffect,useState} from 'react';
type Automation={id:string;name:string;threadId:string;lastStatus:string};
const labels:Record<string,string>={waiting:'等待会话空闲',running:'执行中',completed:'成功',failed:'失败',cancelled:'取消',unknown:'结果待核对'};
const date=(value:string|null)=>value?new Date(value).toLocaleString():'—';
export function AutomationHistory({automations}:{automations:Automation[]}){
  const [id,setId]=useState(automations[0]?.id||''),[before,setBefore]=useState<number|null>(null),[page,setPage]=useState<any>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!id&&automations.length)setId(automations[0].id)},[automations,id]);
  useEffect(()=>{let alive=true,loading=false;setPage(null);const load=async()=>{if(!id||loading||document.hidden)return;loading=true;try{const result=await window.omegaProductApi?.(`automation-runs?id=${encodeURIComponent(id)}${before?`&before=${before}`:''}`);if(alive){setPage(result);setError('')}}catch(e){if(alive)setError(String(e))}finally{loading=false}};void load();const timer=setInterval(load,5000);return()=>{alive=false;clearInterval(timer)}},[id,before,revision]);
  const act=async(action:string,expectedRunId:string)=>{if(busy)return;setBusy(true);try{await window.omegaProductApi?.('automations',{id,action,expectedRunId});setRevision(n=>n+1)}catch(e){setError(String(e))}finally{setBusy(false)}};
  return <section className="automation-history"><h3>自动化运行历史</h3><p>从此版本开始记录；升级前没有独立运行记录，不补造历史。结果以原会话为准，不额外调用模型生成摘要。</p><div className="work-actions"><select aria-label="选择自动化历史" value={id} onChange={e=>{setId(e.target.value);setBefore(null)}}><option value="">选择自动化</option>{automations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={()=>setRevision(n=>n+1)}>刷新记录</button></div>{error&&<p role="alert">{error}</p>}{page?.items?.length===0&&<p>暂无本页运行记录。</p>}{page?.items?.map((run:any)=><article className="work-card" key={run.id}><strong>{labels[run.status]||run.status} · {run.manual?'手动运行':'计划运行'}</strong><p>计划：{date(run.scheduled_at)}<br/>开始：{date(run.started_at)}<br/>结束：{date(run.finished_at)}</p><small>运行 ID：{run.id}<br/>会话：{run.thread_id}<br/>轮次：{run.turn_id||'尚未确认'}</small>{run.error&&<p>{run.error}</p>}<div className="work-actions"><button onClick={()=>{void window.omegaNavigation?.openThread(run.thread_id,run.turn_id||undefined);window.dispatchEvent(new Event('omega:close-control-center'))}}>打开原会话</button>{run.status==='unknown'&&<button disabled={busy} onClick={()=>void act('reconcile',run.id)}>核对原轮次</button>}{run.status==='waiting'&&<button disabled={busy} onClick={()=>void act('cancelWaiting',run.id)}>取消排队</button>}</div></article>)}<div className="work-actions"><button disabled={!before} onClick={()=>setBefore(null)}>最新记录</button><button disabled={!page?.nextCursor} onClick={()=>setBefore(page.nextCursor)}>更早记录</button></div></section>;
}
