import {MAX_MESSAGE_IMAGES} from '../../src/shared/attachment-limits.js';
import {CopyMessage} from './CopyMessage.js';
import {splitImageText} from '../../src/shared/inline-images.js';
import {useEffect,useLayoutEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import DOMPurify from 'dompurify';
import {marked} from 'marked';

export interface ChatItem{inlineImages?:boolean;id:string;type:string;status?:string;pageText?:string;text?:string;aggregatedOutput?:string;command?:string;changes?:Array<{path:string;diff?:string}>;summary?:string[];content?:unknown[];images?:Array<{id:string;expiresAt:number}>;totalLength?:number;offset?:number;deferred?:boolean;open?:boolean}
type ImageRef={id:string;expiresAt:number};
type Turn={id:string;label:string};
interface TimelineModel{items:ChatItem[];active:boolean;metrics:string;historyMode:boolean;history:{outline:Turn[];selectedTurn:string|null;hasOlder:boolean;hasNewer:boolean}}
interface TimelineActions{fullText(item:ChatItem):Promise<string>;itemText(item:ChatItem):string;toggle(item:ChatItem,open:boolean):void;page(item:ChatItem,offset:number):void;loadImage(ref:ImageRef,thumb:boolean,signal:AbortSignal):Promise<Blob>;selectTurn(index:number):void;previous():void;next():void;latest():void}
const viewport={follow:true,listeners:new Set<()=>void>(),set(value:boolean){if(this.follow===value)return;this.follow=value;for(const listener of this.listeners)listener()},subscribe(listener:()=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener)},snapshot(){return this.follow}};
const useFollowLatest=()=>useSyncExternalStore(viewport.subscribe.bind(viewport),viewport.snapshot.bind(viewport),viewport.snapshot.bind(viewport));
const toolName:Record<string,string>={commandExecution:'命令执行',fileChange:'文件修改',reasoning:'思考过程',mcpToolCall:'插件工具',webSearch:'网页搜索',imageGeneration:'图片生成'};

export function renderMarkdown(text:string){const template=document.createElement('template');template.innerHTML=DOMPurify.sanitize(marked.parse(text,{gfm:true,breaks:false}) as string,{ALLOWED_TAGS:['p','br','hr','h1','h2','h3','h4','h5','h6','strong','em','del','blockquote','ul','ol','li','pre','code','a','table','thead','tbody','tr','th','td','input'],ALLOWED_ATTR:['href','title','class','start','align','type','checked','disabled']});for(const link of template.content.querySelectorAll('a')){const href=link.getAttribute('href')||'';if(!/^(https?:\/\/|mailto:|#)/i.test(href))link.removeAttribute('href');else if(!href.startsWith('#')){link.target='_blank';link.rel='noopener noreferrer'}}for(const input of template.content.querySelectorAll('input')){input.type='checkbox';input.disabled=true}for(const table of template.content.querySelectorAll('table')){const wrapper=document.createElement('div');wrapper.className='table-scroll';table.replaceWith(wrapper);wrapper.append(table)}for(const pre of template.content.querySelectorAll('pre')){const code=pre.querySelector('code');if(!code)continue;const wrapper=document.createElement('div');wrapper.className='code-block';const bar=document.createElement('div');bar.className='code-toolbar';const language=document.createElement('span');language.textContent=[...code.classList].find(name=>name.startsWith('language-'))?.slice(9)||'text';const copy=document.createElement('button');copy.type='button';copy.className='react-code-copy';copy.textContent='复制';bar.append(language,copy);pre.replaceWith(wrapper);wrapper.append(bar,pre)}return template.innerHTML}
function HistoryImage({value,index,actions,open}:{value:ImageRef;index:number;actions:TimelineActions;open(ref:ImageRef):void}){const[url,setUrl]=useState(''),[loading,setLoading]=useState(false),[failure,setFailure]=useState(''),resource=useRef<{controller:AbortController;url:string}|null>(null),expired=Date.now()>=value.expiresAt;useEffect(()=>()=>{resource.current?.controller.abort();if(resource.current?.url)URL.revokeObjectURL(resource.current.url)},[]);const activate=async()=>{if(expired)return;if(url){open(value);return}const controller=new AbortController();resource.current?.controller.abort();resource.current={controller,url:''};setLoading(true);setFailure('');try{const blob=await actions.loadImage(value,true,controller.signal);if(controller.signal.aborted)return;const next=URL.createObjectURL(blob);resource.current.url=next;setUrl(next)}catch(error){if(!controller.signal.aborted)setFailure(error instanceof Error?error.message:String(error))}finally{if(!controller.signal.aborted)setLoading(false)}};return <button type="button" className="history-image" disabled={expired||loading} title={url?'点击查看大图':''} aria-label={expired?`图片 ${index+1} 已过期`:`查看图片 ${index+1}`} onClick={()=>void activate()}>{url?<img src={url} alt={`图片 ${index+1}，点击查看大图`}/>:failure|| (expired?'图片已过期（保留 7 天）':loading?'加载缩略图…':`查看图片 ${index+1}`)}</button>}
function ImageGallery({values,actions,open}:{values:ImageRef[];actions:TimelineActions;open(ref:ImageRef):void}){return <div className="message-images">{values.slice(0,MAX_MESSAGE_IMAGES).map((value,index)=><HistoryImage value={value} index={index} actions={actions} open={open} key={value.id}/>)}</div>}
function ImageViewer({value,actions,close}:{value:ImageRef|null;actions:TimelineActions;close():void}){const dialog=useRef<HTMLDialogElement>(null),[url,setUrl]=useState(''),[status,setStatus]=useState('');useEffect(()=>{if(!value){if(dialog.current?.open)dialog.current.close();setUrl('');setStatus('');return}const controller=new AbortController();let objectUrl='';setUrl('');setStatus('正在加载图片…');if(!dialog.current?.open)dialog.current?.showModal();void actions.loadImage(value,false,controller.signal).then(blob=>{if(controller.signal.aborted)return;objectUrl=URL.createObjectURL(blob);setUrl(objectUrl);setStatus('图片自上传起保留 7 天')},error=>{if(!controller.signal.aborted)setStatus(error instanceof Error?error.message:String(error))});return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl)}},[value?.id,actions.loadImage]);return <dialog ref={dialog} id="image-viewer" aria-label="查看图片" onClose={close}><button id="image-view-close" type="button" className="secondary" onClick={()=>dialog.current?.close()}>关闭</button><p id="image-view-status" role="status">{status}</p><img id="image-view" alt="图片预览" src={url||undefined} hidden={!url}/></dialog>}
function OrderedUserText({text,images,actions,open}:{text:string;images:ImageRef[];actions:TimelineActions;open(ref:ImageRef):void}){return <>{splitImageText(text,images.map(image=>image.id)).map((part,index)=>part.type==='text'?<span key={index}>{part.text}</span>:<HistoryImage key={index} value={images.find(image=>image.id===part.id)!} index={images.findIndex(image=>image.id===part.id)} actions={actions} open={open}/>)}</>}
function ChatMessage({item,actions,openImage}:{item:ChatItem;actions:TimelineActions;openImage(ref:ImageRef):void}){const isUser=item.type==='userMessage',html=useMemo(()=>isUser?'':renderMarkdown(actions.itemText(item)),[item,isUser,actions]);return <article data-item-id={item.id} className={`message ${isUser?'user':'assistant'}`}><span className="role">{isUser?'你':'Ω OMEGA'}</span>{isUser?<div className="bubble ordered-user-content"><OrderedUserText text={actions.itemText(item)} images={item.images||[]} actions={actions} open={openImage}/></div>:<div className="bubble copy-reply"><div className="markdown-body" dangerouslySetInnerHTML={{__html:html}} onClick={event=>{const button=(event.target as Element).closest<HTMLButtonElement>('.react-code-copy');if(!button)return;const code=button.closest('.code-block')?.querySelector('code')?.textContent||'';void navigator.clipboard.writeText(code).then(()=>{button.textContent='已复制'},()=>{button.textContent='请选中复制'})}}/><CopyMessage read={()=>actions.fullText(item)}/></div>}{!!item.images?.length&&!item.inlineImages&&!actions.itemText(item).includes('[OmegaImage:')&&<ImageGallery values={item.images} actions={actions} open={openImage}/>} {(item.totalLength||0)>12000&&<div className="message-pages"><button disabled={(item.offset||0)<=0} onClick={()=>actions.page(item,(item.offset||0)-12000)}>上一段</button><button disabled={(item.offset||0)+12000>=(item.totalLength||0)} onClick={()=>actions.page(item,(item.offset||0)+12000)}>下一段</button></div>}</article>}
function ToolItem({item,actions}:{item:ChatItem;actions:TimelineActions}){return <details data-item-id={item.id} className="tool-disclosure" open={item.open} onToggle={event=>actions.toggle(item,event.currentTarget.open)}><summary>{toolName[item.type]||'执行详情'}{item.status&&` · ${item.status}`}</summary><pre>{item.deferred?'点击展开加载内容':actions.itemText(item)}</pre>{!item.deferred&&(item.totalLength||0)>12000&&<div className="message-pages"><button disabled={(item.offset||0)<=0} onClick={()=>actions.page(item,(item.offset||0)-12000)}>上一段</button><button disabled={(item.offset||0)+12000>=(item.totalLength||0)} onClick={()=>actions.page(item,(item.offset||0)+12000)}>下一段</button></div>}</details>}
function Timeline({model,actions,area}:{model:TimelineModel;actions:TimelineActions;area:HTMLElement}){const follow=useFollowLatest(),[viewer,setViewer]=useState<ImageRef|null>(null);useEffect(()=>{const onScroll=()=>viewport.set(area.scrollHeight-area.scrollTop-area.clientHeight<60);area.addEventListener('scroll',onScroll,{passive:true});return()=>area.removeEventListener('scroll',onScroll)},[area]);useLayoutEffect(()=>{if(follow)area.scrollTop=area.scrollHeight},[area,model.items,model.metrics,model.active,follow]);const groups:ChatItem[][]=[];for(const item of model.items){if(!groups.length||item.type==='userMessage')groups.push([]);groups.at(-1)!.push(item)}return <>{groups.map((group,index)=><section className="exchange" key={group[0]?.id||index}>{group.map(item=>['userMessage','agentMessage'].includes(item.type)?<ChatMessage key={item.id} item={item} actions={actions} openImage={setViewer}/>:<ToolItem key={item.id} item={item} actions={actions}/>)}</section>)}{model.metrics&&<div id="turn-metrics" className="turn-metrics" aria-label="本轮统计">{model.metrics}</div>}{model.active&&!model.historyMode&&<div className="omega-typing" role="status" aria-label="Omega 正在处理"><span className="typing-avatar">Ω</span><span className="typing-bubble"><span className="typing-label">OMEGA 正在处理</span><span className="typing-dots"><i/><i/><i/></span></span></div>}{!model.items.length&&<p className="chat-empty">在下方发送消息，开始新的工作。</p>}<ImageViewer value={viewer} actions={actions} close={()=>setViewer(null)}/></>}
function Latest({model,actions}:{model:TimelineModel;actions:TimelineActions}){const follow=useFollowLatest();return <button id="floating-latest" hidden={follow||(!model.items.length&&!model.historyMode)} onClick={()=>{viewport.set(true);actions.latest()}}>↓ 回到最新</button>}
export function installChatTimeline(){const area=document.getElementById('messages'),latest=document.querySelector<HTMLElement>('.latest-bar');if(!area||!latest)return;const root:Root=createRoot(area),latestRoot=createRoot(latest);window.omegaReactChat={render:(model:TimelineModel,actions:TimelineActions)=>{root.render(<Timeline model={model} actions={actions} area={area}/>);latestRoot.render(<Latest model={model} actions={actions}/>)},followLatest:()=>viewport.set(true)};window.dispatchEvent(new Event('omega:react-chat-ready'))}
