import {useEffect,useLayoutEffect,useMemo,useSyncExternalStore} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import DOMPurify from 'dompurify';
import {marked} from 'marked';

export interface ChatItem{id:string;type:string;status?:string;pageText?:string;text?:string;aggregatedOutput?:string;command?:string;changes?:Array<{path:string;diff?:string}>;summary?:string[];content?:unknown[];images?:Array<{id:string;expiresAt:number}>;totalLength?:number;offset?:number;deferred?:boolean;open?:boolean}
type Turn={id:string;label:string};
interface TimelineModel{items:ChatItem[];active:boolean;metrics:string;historyMode:boolean;history:{outline:Turn[];selectedTurn:string|null;hasOlder:boolean;hasNewer:boolean}}
interface TimelineActions{itemText(item:ChatItem):string;toggle(item:ChatItem,open:boolean):void;page(item:ChatItem,offset:number):void;attachImages(item:ChatItem,slot:HTMLElement):void;selectTurn(index:number):void;previous():void;next():void;latest():void}
const viewport={follow:true,listeners:new Set<()=>void>(),set(value:boolean){if(this.follow===value)return;this.follow=value;for(const listener of this.listeners)listener()},subscribe(listener:()=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener)},snapshot(){return this.follow}};
const useFollowLatest=()=>useSyncExternalStore(viewport.subscribe.bind(viewport),viewport.snapshot.bind(viewport),viewport.snapshot.bind(viewport));
const toolName:Record<string,string>={commandExecution:'命令执行',fileChange:'文件修改',reasoning:'思考过程',mcpToolCall:'插件工具',webSearch:'网页搜索',imageGeneration:'图片生成'};

export function renderMarkdown(text:string){const template=document.createElement('template');template.innerHTML=DOMPurify.sanitize(marked.parse(text,{gfm:true,breaks:false}) as string,{ALLOWED_TAGS:['p','br','hr','h1','h2','h3','h4','h5','h6','strong','em','del','blockquote','ul','ol','li','pre','code','a','table','thead','tbody','tr','th','td','input'],ALLOWED_ATTR:['href','title','class','start','align','type','checked','disabled']});for(const link of template.content.querySelectorAll('a')){const href=link.getAttribute('href')||'';if(!/^(https?:\/\/|mailto:|#)/i.test(href))link.removeAttribute('href');else if(!href.startsWith('#')){link.target='_blank';link.rel='noopener noreferrer'}}for(const input of template.content.querySelectorAll('input')){input.type='checkbox';input.disabled=true}for(const table of template.content.querySelectorAll('table')){const wrapper=document.createElement('div');wrapper.className='table-scroll';table.replaceWith(wrapper);wrapper.append(table)}for(const pre of template.content.querySelectorAll('pre')){const code=pre.querySelector('code');if(!code)continue;const wrapper=document.createElement('div');wrapper.className='code-block';const bar=document.createElement('div');bar.className='code-toolbar';const language=document.createElement('span');language.textContent=[...code.classList].find(name=>name.startsWith('language-'))?.slice(9)||'text';const copy=document.createElement('button');copy.type='button';copy.className='react-code-copy';copy.textContent='复制';bar.append(language,copy);pre.replaceWith(wrapper);wrapper.append(bar,pre)}return template.innerHTML}
function ChatMessage({item,actions}:{item:ChatItem;actions:TimelineActions}){const isUser=item.type==='userMessage',html=useMemo(()=>isUser?'':renderMarkdown(actions.itemText(item)),[item,isUser,actions]);useLayoutEffect(()=>{const slot=document.querySelector<HTMLElement>(`[data-react-images="${CSS.escape(item.id)}"]`);if(slot&&item.images?.length)actions.attachImages(item,slot)},[item,actions]);return <article data-item-id={item.id} className={`message ${isUser?'user':'assistant'}`}><span className="role">{isUser?'你':'Ω OMEGA'}</span>{isUser?<div className="bubble">{actions.itemText(item)}</div>:<div className="bubble markdown-body" dangerouslySetInnerHTML={{__html:html}} onClick={event=>{const button=(event.target as Element).closest<HTMLButtonElement>('.react-code-copy');if(!button)return;const code=button.closest('.code-block')?.querySelector('code')?.textContent||'';void navigator.clipboard.writeText(code).then(()=>{button.textContent='已复制'},()=>{button.textContent='请选中复制'})}}/>}<div data-react-images={item.id}/>{(item.totalLength||0)>12000&&<div className="message-pages"><button disabled={(item.offset||0)<=0} onClick={()=>actions.page(item,(item.offset||0)-12000)}>上一段</button><button disabled={(item.offset||0)+12000>=(item.totalLength||0)} onClick={()=>actions.page(item,(item.offset||0)+12000)}>下一段</button></div>}</article>}
function ToolItem({item,actions}:{item:ChatItem;actions:TimelineActions}){return <details data-item-id={item.id} className="tool-disclosure" open={item.open} onToggle={event=>actions.toggle(item,event.currentTarget.open)}><summary>{toolName[item.type]||'执行详情'}{item.status&&` · ${item.status}`}</summary><pre>{item.deferred?'点击展开加载内容':actions.itemText(item)}</pre>{!item.deferred&&(item.totalLength||0)>12000&&<div className="message-pages"><button disabled={(item.offset||0)<=0} onClick={()=>actions.page(item,(item.offset||0)-12000)}>上一段</button><button disabled={(item.offset||0)+12000>=(item.totalLength||0)} onClick={()=>actions.page(item,(item.offset||0)+12000)}>下一段</button></div>}</details>}
function Timeline({model,actions,area}:{model:TimelineModel;actions:TimelineActions;area:HTMLElement}){const follow=useFollowLatest();useEffect(()=>{const onScroll=()=>viewport.set(area.scrollHeight-area.scrollTop-area.clientHeight<60);area.addEventListener('scroll',onScroll,{passive:true});return()=>area.removeEventListener('scroll',onScroll)},[area]);useLayoutEffect(()=>{if(follow)area.scrollTop=area.scrollHeight},[area,model.items,model.metrics,model.active,follow]);const groups:ChatItem[][]=[];for(const item of model.items){if(!groups.length||item.type==='userMessage')groups.push([]);groups.at(-1)!.push(item)}return <>{groups.map((group,index)=><section className="exchange" key={group[0]?.id||index}>{group.map(item=>['userMessage','agentMessage'].includes(item.type)?<ChatMessage key={item.id} item={item} actions={actions}/>:<ToolItem key={item.id} item={item} actions={actions}/>)}</section>)}{model.metrics&&<div id="turn-metrics" className="turn-metrics" aria-label="本轮统计">{model.metrics}</div>}{model.active&&!model.historyMode&&<div className="omega-typing" role="status" aria-label="Omega 正在处理"><span className="typing-avatar">Ω</span><span className="typing-bubble"><span className="typing-label">OMEGA 正在处理</span><span className="typing-dots"><i/><i/><i/></span></span></div>}{!model.items.length&&<p className="chat-empty">在下方发送消息，开始新的工作。</p>}</>}
function History({model,actions,close}:{model:TimelineModel;actions:TimelineActions;close():void}){const index=model.history.outline.findIndex(turn=>turn.id===model.history.selectedTurn);return <><label htmlFor="history-select">选择问答位置</label><select id="history-select" aria-label="选择历史问答" value={index<0?'':String(index)} onChange={event=>{actions.selectTurn(Number(event.target.value));close()}} disabled={!model.history.outline.length}>{model.history.outline.map((turn,itemIndex)=><option value={itemIndex} key={turn.id}>{itemIndex+1}. {turn.label}</option>)}</select><div className="history-menu-actions"><button id="prev-exchange" disabled={index<0||(index===0&&!model.history.hasOlder)} onClick={()=>{actions.previous();close()}}>上一组问答</button><button id="next-exchange" disabled={index<0||(index===model.history.outline.length-1&&!model.history.hasNewer)} onClick={()=>{actions.next();close()}}>下一组问答</button></div><button id="jump-latest" onClick={()=>{viewport.set(true);actions.latest();close()}}>回到最新</button></>}
function Latest({model,actions}:{model:TimelineModel;actions:TimelineActions}){const follow=useFollowLatest();return <button id="floating-latest" hidden={follow||(!model.items.length&&!model.historyMode)} onClick={()=>{viewport.set(true);actions.latest()}}>↓ 回到最新</button>}
export function installChatTimeline(){const area=document.getElementById('messages'),history=document.querySelector<HTMLElement>('.history-nav'),latest=document.querySelector<HTMLElement>('.latest-bar'),header=document.querySelector<HTMLElement>('main>header'),headerTitle=header?.querySelector<HTMLElement>('.header-title'),mobileNew=document.getElementById('mobile-new');if(!area||!history||!latest||!header||!headerTitle||!mobileNew)return;const threadMeta=document.createElement('div');threadMeta.className='thread-header-meta';headerTitle.append(threadMeta);const threadMore=document.createElement('details');threadMore.id='thread-more';threadMore.hidden=true;const summary=document.createElement('summary');summary.textContent='更多';summary.setAttribute('aria-label','会话更多操作');const menu=document.createElement('div');menu.className='thread-more-menu';history.classList.add('thread-history-menu');menu.append(history);threadMore.append(summary,menu);header.insertBefore(threadMore,mobileNew);const close=()=>{threadMore.open=false};document.addEventListener('click',event=>{if(threadMore.open&&!threadMore.contains(event.target as Node))close()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&threadMore.open){close();summary.focus()}});const root:Root=createRoot(area),historyRoot=createRoot(history),latestRoot=createRoot(latest);window.omegaReactChat={render:(model:TimelineModel,actions:TimelineActions)=>{const index=model.history.outline.findIndex(turn=>turn.id===model.history.selectedTurn),turn=model.history.outline[index],label=turn?.label.replace(/\s+/g,' ').trim();threadMeta.textContent=turn?`${model.historyMode?'正在查看历史':'最新问答'} · ${index+1}. ${label}`:'当前会话';threadMore.hidden=!model.history.outline.length;root.render(<Timeline model={model} actions={actions} area={area}/>);historyRoot.render(<History model={model} actions={actions} close={close}/>);latestRoot.render(<Latest model={model} actions={actions}/>)},followLatest:()=>viewport.set(true)};window.dispatchEvent(new Event('omega:react-chat-ready'))}
