import {useEffect,useMemo,useState} from 'react';
import {SystemPanel} from './SystemPanel.js';

type Tab='automations'|'integrations'|'operations'|'system';
type Thread={id:string;name?:string;preview?:string;cwd?:string};
type Schedule={kind:'interval';minutes:number}|{kind:'daily';time:string;timezone:string};
type Automation={id:string;name:string;threadId:string;prompt:string;schedule:Schedule;enabled:boolean;nextRunAt:string|null;lastRunAt:string|null;lastTurnId:string|null;lastStatus:string;lastError:string|null};
type Result<T>={ok:boolean;data?:T;error?:string};
type AppInfo={id:string;name:string;description?:string|null;isEnabled:boolean;isAccessible:boolean};
type InstalledApp={id:string;enabled:boolean;callable:boolean};
type McpServer={name:string;runtimeStatus?:string|null;authStatus?:string;tools?:Record<string,unknown>;toolsError?:string|null};
type Plugin={id:string;name:string;installed:boolean;enabled:boolean;version?:string|null;localVersion?:string|null};
type Marketplace={name:string;path?:string|null;plugins:Plugin[]};
type Integrations={apps:Result<{data:AppInfo[]}>;installed:Result<{apps:InstalledApp[]}>;mcp:Result<{data:McpServer[]}>;plugins:Result<{marketplaces:Marketplace[]}>};

const call=<T,>(route:string,data?:unknown)=>{if(!window.omegaProductApi)throw new Error('Omega 客户端尚未就绪');return window.omegaProductApi<T>(route,data);};
const when=(value:string|null)=>value?new Date(value).toLocaleString():'—';
const requestId=()=>{if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=[...bytes].map(value=>value.toString(16).padStart(2,'0')).join('');return`${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;};
const statusName:Record<string,string>={idle:'未执行',running:'执行中',completed:'已完成',failed:'失败',connected:'已连接',authenticationRequired:'需要登录',notStarted:'未启动',starting:'连接中',disabled:'已停用',cancelled:'已取消'};

export function ControlCenter(){
  const [open,setOpen]=useState(false),[tab,setTab]=useState<Tab>('automations'),[busy,setBusy]=useState(''),[notice,setNotice]=useState('');
  const [threads,setThreads]=useState<Thread[]>([]),[automations,setAutomations]=useState<Automation[]>([]),[integrations,setIntegrations]=useState<Integrations|null>(null);
  const [name,setName]=useState(''),[threadId,setThreadId]=useState(''),[prompt,setPrompt]=useState(''),[scheduleKind,setScheduleKind]=useState<'interval'|'daily'>('interval'),[minutes,setMinutes]=useState(60),[dailyTime,setDailyTime]=useState('09:00');
  const [operationKind,setOperationKind]=useState<'browser'|'computer'>('browser'),[operationThread,setOperationThread]=useState(''),[operationPrompt,setOperationPrompt]=useState('');
  const refresh=async()=>{setNotice('');try{const [threadResult,automationResult]=await Promise.all([call<{data:Thread[]}>('rpc',{method:'thread/list',params:{limit:100,sourceKinds:[]}}),call<{automations:Automation[]}>('automations')]);setThreads(threadResult.data);setAutomations(automationResult.automations);setThreadId(value=>value||threadResult.data[0]?.id||'');setOperationThread(value=>value||threadResult.data[0]?.id||'');}catch(error){setNotice(error instanceof Error?error.message:String(error));}};
  const refreshIntegrations=async()=>{setBusy('integrations');try{setIntegrations(await call<Integrations>('integrations'));}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy('');}};
  useEffect(()=>{const show=()=>setOpen(true),desktop=(event:Event)=>{const detail=(event as CustomEvent<{command:string;value?:unknown}>).detail;if(detail.command==='control-center')setOpen(true);if(detail.command==='new-chat')document.querySelector<HTMLElement>('#new')?.click();if(detail.command==='new-group'){document.querySelector<HTMLElement>('#show-groups')?.click();setTimeout(()=>document.querySelector<HTMLElement>('#new-group')?.click(),0);}if(detail.command==='toggle-sidebar')document.querySelector<HTMLElement>('#menu-toggle')?.click();if(detail.command==='open-thread'&&typeof detail.value==='string')document.querySelector<HTMLElement>(`[data-thread-id="${CSS.escape(detail.value)}"] .thread-open`)?.click();};window.addEventListener('omega:open-control-center',show);window.addEventListener('omega:desktop-command',desktop);return()=>{window.removeEventListener('omega:open-control-center',show);window.removeEventListener('omega:desktop-command',desktop);};},[]);
  useEffect(()=>{if(open)void refresh();},[open]);useEffect(()=>{if(open&&tab==='integrations'&&!integrations)void refreshIntegrations();},[open,tab]);
  const installed=useMemo(()=>new Map((integrations?.installed.data?.apps||[]).map(item=>[item.id,item])),[integrations]);
  const run=async(label:string,operation:()=>Promise<unknown>,after=refresh)=>{setBusy(label);setNotice('');try{await operation();await after();setNotice('操作已完成');}catch(error){setNotice(error instanceof Error?error.message:String(error));}finally{setBusy('');}};
  const createAutomation=(event:React.FormEvent)=>{event.preventDefault();const schedule:Schedule=scheduleKind==='interval'?{kind:'interval',minutes}:{kind:'daily',time:dailyTime,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Shanghai'};void run('create',()=>call('automations',{action:'create',name,threadId,prompt,schedule,enabled:true}),async()=>{setName('');setPrompt('');await refresh();});};
  const submitOperation=(event:React.FormEvent)=>{event.preventDefault();const label=operationKind==='browser'?'浏览器操作':'电脑操作',submissionId=requestId();const text=`[Omega ${label}任务]\n${operationPrompt}\n\n只使用当前会话已经配置且获准的工具。涉及登录、发送、删除、购买、发布或其他外部副作用时必须先请求用户批准；完成后报告实际执行结果和未完成项。`;void run('operation',()=>call('rpc',{method:'turn/start',params:{threadId:operationThread,input:[{type:'text',text}]},submissionId}),async()=>{setOperationPrompt('');document.querySelector<HTMLElement>(`[data-thread-id="${CSS.escape(operationThread)}"] .thread-open`)?.click();setOpen(false);});};
  if(!open)return null;
  return <div className="omega-center-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false);}}><section className="omega-center" role="dialog" aria-modal="true" aria-label="Omega 控制中心"><header><div><small>OMEGA CONTROL CENTER</small><h2>工作控制中心</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="关闭">×</button></header><nav>{([['automations','自动化'],['integrations','连接与插件'],['operations','电脑与浏览器'],['system','系统与备份']] as const).map(([id,label])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>{notice&&<p className="omega-center-notice">{notice}</p>}<div className="omega-center-body">
    {tab==='automations'&&<div className="omega-center-grid"><form className="omega-center-form" onSubmit={createAutomation}><h3>新建自动化</h3><label>名称<input value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></label><label>目标会话<select value={threadId} onChange={e=>setThreadId(e.target.value)} required>{threads.map(thread=><option key={thread.id} value={thread.id}>{thread.name||thread.preview||'新会话'} · {thread.cwd||''}</option>)}</select></label><label>要执行的任务<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} required maxLength={12000} rows={6}/></label><div className="omega-center-schedule"><label>频率<select value={scheduleKind} onChange={e=>setScheduleKind(e.target.value as 'interval'|'daily')}><option value="interval">每隔一段时间</option><option value="daily">每天</option></select></label>{scheduleKind==='interval'?<label>分钟<input type="number" min={5} max={43200} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label>:<label>时间<input type="time" value={dailyTime} onChange={e=>setDailyTime(e.target.value)}/></label>}</div><button disabled={!!busy}>创建自动化</button></form><div className="omega-center-list"><div className="omega-center-section-title"><h3>自动化任务</h3><button onClick={()=>void refresh()}>刷新</button></div>{automations.length===0&&<p className="omega-empty">还没有自动化任务。</p>}{automations.map(item=><article key={item.id}><div><strong>{item.name}</strong><span className={`omega-state ${item.lastStatus}`}>{statusName[item.lastStatus]||item.lastStatus}</span></div><p>{item.prompt}</p><small>下次：{when(item.nextRunAt)} · 上次：{when(item.lastRunAt)}</small>{item.lastError&&<em>{item.lastError}</em>}<footer><button disabled={!!busy||item.lastStatus==='running'} onClick={()=>void run('run',()=>call('automations',{action:'run',id:item.id}))}>立即运行</button><button disabled={!!busy||item.lastStatus==='running'} onClick={()=>void run('toggle',()=>call('automations',{action:'update',id:item.id,enabled:!item.enabled}))}>{item.enabled?'暂停':'启用'}</button><button className="danger" disabled={!!busy||item.lastStatus==='running'} onClick={()=>{if(confirm(`删除自动化“${item.name}”？`))void run('delete',()=>call('automations',{action:'delete',id:item.id}));}}>删除</button></footer></article>)}</div></div>}
    {tab==='integrations'&&<div className="omega-integrations"><div className="omega-center-section-title"><div><h3>Codex Apps、插件与 MCP</h3><p>直接读取当前 App Server 的真实连接状态。</p></div><button disabled={!!busy} onClick={()=>void run('reload',()=>call('integrations',{action:'reloadMcp'}),refreshIntegrations)}>重新加载 MCP</button></div>{!integrations&&<p className="omega-empty">正在读取连接…</p>}{integrations&&<><h4>Apps</h4>{integrations.apps.ok?(integrations.apps.data?.data||[]).map(app=><article key={app.id}><div><strong>{app.name}</strong><span>{installed.get(app.id)?.callable?'可调用':app.isAccessible?'可使用':'不可用'}</span></div><p>{app.description||app.id}</p><button disabled={!!busy} onClick={()=>void run('app',()=>call('integrations',{action:'setAppEnabled',id:app.id,enabled:!app.isEnabled}),refreshIntegrations)}>{app.isEnabled?'停用':'启用'}</button></article>):<p className="omega-error">Apps：{integrations.apps.error}</p>}<h4>MCP 服务器</h4>{integrations.mcp.ok?(integrations.mcp.data?.data||[]).map(server=><article key={server.name}><div><strong>{server.name}</strong><span>{statusName[server.runtimeStatus||'']||server.runtimeStatus||'未知'}</span></div><p>{Object.keys(server.tools||{}).length} 个工具{server.toolsError?` · ${server.toolsError}`:''}</p>{['notLoggedIn','unknown'].includes(server.authStatus||'')&&<button disabled={!!busy} onClick={()=>void run('oauth',async()=>{const result=await call<{authorizationUrl?:string}>('integrations',{action:'oauthLogin',name:server.name});if(result.authorizationUrl)window.open(result.authorizationUrl,'_blank','noopener');},refreshIntegrations)}>连接账号</button>}</article>):<p className="omega-error">MCP：{integrations.mcp.error}</p>}<h4>插件市场（实验能力）</h4>{integrations.plugins.ok?(integrations.plugins.data?.marketplaces||[]).flatMap(market=>market.plugins.map(plugin=><article key={`${market.name}:${plugin.id}`}><div><strong>{plugin.name}</strong><span>{plugin.installed?'已安装':'未安装'}</span></div><p>{plugin.localVersion||plugin.version||plugin.id} · {market.name}</p><button disabled={!!busy} onClick={()=>{const verb=plugin.installed?'卸载':'安装';if(!confirm(`${verb}插件“${plugin.name}”？这会修改 Codex 配置。`))return;void run('plugin',()=>call('rpc',plugin.installed?{method:'plugin/uninstall',params:{pluginId:plugin.id},confirmUninstall:true}:{method:'plugin/install',params:{pluginName:plugin.name,...(market.path?{marketplacePath:market.path}:{remoteMarketplaceName:market.name}),installAttemptId:requestId()},confirmInstall:true}),refreshIntegrations);}}>{plugin.installed?'卸载':'安装'}</button></article>)):<p className="omega-error">插件目录：{integrations.plugins.error}</p>}</>}</div>}
    {tab==='operations'&&<div className="omega-operation"><div className="omega-operation-info"><h3>让现有会话操作电脑或浏览器</h3><p>任务直接发给所选会话，继续使用它原有上下文。Omega 不绕过 Codex 审批；实际可用能力取决于该会话已经连接的 MCP、App、Skill 和执行环境。</p><ul><li>浏览器：调研、打开页面、表单辅助、网页测试。</li><li>电脑：文件、应用和终端工作；外部副作用仍需批准。</li></ul></div><form className="omega-center-form" onSubmit={submitOperation}><label>操作类型<select value={operationKind} onChange={e=>setOperationKind(e.target.value as 'browser'|'computer')}><option value="browser">浏览器操作</option><option value="computer">电脑操作</option></select></label><label>执行会话<select value={operationThread} onChange={e=>setOperationThread(e.target.value)} required>{threads.map(thread=><option key={thread.id} value={thread.id}>{thread.name||thread.preview||'新会话'} · {thread.cwd||''}</option>)}</select></label><label>具体任务<textarea value={operationPrompt} onChange={e=>setOperationPrompt(e.target.value)} rows={9} maxLength={12000} required placeholder="例如：打开测试站点，检查移动端登录流程，把截图和问题汇总给我。"/></label><button disabled={!!busy}>发送到会话执行</button></form></div>}
    {tab==='system'&&<SystemPanel/>}
  </div></section></div>;
}
