import {useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {type ChatHeaderState,type GroupHeaderState,type WorkPanel,useAppState} from './AppState.js';
import {WorkPanelEntry} from './WorkPanels.js';

function PlusIcon(){return <svg className="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" aria-hidden><path d="M12 5v14M5 12h14"/></svg>}

function ChatMeta({model}:{model:ChatHeaderState}){const index=model.outline.findIndex(turn=>turn.id===model.selectedTurn),turn=model.outline[index],label=turn?.label.replace(/\s+/g,' ').trim();return <div className="thread-header-meta">{turn?`${model.historyMode?'正在查看历史':'最新问答'} · ${index+1}. ${label}`:'当前会话'}</div>}
function GroupMeta({model}:{model:GroupHeaderState}){return <div className="group-header-meta"><span className="status-pill" data-status={model.status}>{model.statusLabel}</span><span className="group-description">{model.description}</span><span className="group-availability">{model.availability}</span></div>}
function MobileWorkMenu({close}:{close():void}){const state=useAppState(),open=(panel:WorkPanel)=>{state.workPanelActions?.open(panel);close()};return <div className="mobile-work-menu" aria-label="工作入口"><button disabled={!state.authenticated||!state.workPanelActions} onClick={()=>open('project')}>项目</button><button disabled={!state.authenticated||!state.workPanelActions} onClick={()=>open('attention')}>待处理</button><button disabled={!state.authenticated||!state.workPanelActions} onClick={()=>open('repository')}>变更</button></div>}
function ChatMenu({model,close}:{model:ChatHeaderState|null;close():void}){const index=model?.outline.findIndex(turn=>turn.id===model.selectedTurn)??-1;return <div className="thread-more-menu"><MobileWorkMenu close={close}/>{model&&model.outline.length>0&&<div className="thread-history-menu"><label htmlFor="react-history-select">选择问答位置</label><select id="react-history-select" aria-label="选择历史问答" value={index<0?'':String(index)} onChange={event=>{model.actions.selectTurn(Number(event.target.value));close()}}>{model.outline.map((turn,itemIndex)=><option value={itemIndex} key={turn.id}>{itemIndex+1}. {turn.label}</option>)}</select><div className="history-menu-actions"><button disabled={index<0||(index===0&&!model.hasOlder)} onClick={()=>{model.actions.previous();close()}}>上一组问答</button><button disabled={index<0||(index===model.outline.length-1&&!model.hasNewer)} onClick={()=>{model.actions.next();close()}}>下一组问答</button></div><button className="jump-latest" onClick={()=>{model.actions.latest();close()}}>回到最新</button></div>}</div>}
function GroupMenu({model,close}:{model:GroupHeaderState;close():void}){const panelLabel=(name:string,open:boolean)=>model.mobile?`${open?'关闭':'打开'}${name}`:`${open?'折叠':'展开'}${name}`;return <div className="group-more-menu"><MobileWorkMenu close={close}/><button className="member-panel-toggle" onClick={()=>{model.actions.toggleMembers();close()}}>{panelLabel('成员栏',model.membersOpen)}</button><button className="task-panel-toggle" onClick={()=>{model.actions.toggleQuestions();close()}}>{panelLabel('问题定位栏',model.questionsOpen)}</button><label className="concurrency-control">同时执行任务数<select id="group-concurrency" aria-label="群组同时执行任务数" value={model.maxConcurrency} disabled={model.disabled} onChange={event=>model.actions.setConcurrency(Number(event.target.value))}>{Array.from({length:10},(_,index)=><option key={index+1} value={index+1}>{index+1}</option>)}</select></label><button disabled={model.disabled} onClick={()=>{model.actions.addMember();close()}}>＋ 添加成员</button><button className="group-delete" disabled={model.disabled} onClick={()=>{model.actions.deleteGroup();close()}}>删除群组</button></div>}
function ConversationTitle(){const state=useAppState(),group=state.mode==='groups',model=group?state.groupHeader:state.chatHeader;return <><span className="caption">持续办公 / {group?'群组':'会话'}</span><h1 id="title">{group?state.groupTitle:state.chatTitle}</h1>{model&&(group?<GroupMeta model={model as GroupHeaderState}/>:<ChatMeta model={model as ChatHeaderState}/>)}</>}
function HeaderActions(){const state=useAppState(),details=useRef<HTMLDetailsElement>(null),isGroup=state.mode==='groups',model=isGroup?state.groupHeader:state.chatHeader,emptyChat=!isGroup&&!(model as ChatHeaderState|null)?.outline.length,close=()=>{if(details.current)details.current.open=false};useEffect(()=>{const click=(event:MouseEvent)=>{if(details.current?.open&&!details.current.contains(event.target as Node))close()},key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&details.current?.open){close();details.current.querySelector<HTMLElement>('summary')?.focus()}};document.addEventListener('click',click);document.addEventListener('keydown',key);return()=>{document.removeEventListener('click',click);document.removeEventListener('keydown',key)}},[]);useEffect(close,[state.mode]);if(isGroup&&!model)return null;return <details ref={details} id={isGroup?'group-more':'thread-more'} data-empty={emptyChat?'true':undefined}><summary aria-label={isGroup?'群组更多操作':'会话更多操作'}>更多</summary>{isGroup?<GroupMenu model={model as GroupHeaderState} close={close}/>:<ChatMenu model={model as ChatHeaderState|null} close={close}/>}</details>}
function Devices(){const devices=useAppState().onlineDevices;return devices===null?null:<span>{devices} 台在线设备</span>}
function MobileNew(){const state=useAppState();return <button id="mobile-new" type="button" className="mobile-only icon-button" aria-label={state.mode==='groups'?'新建群组':'新建会话'} onClick={()=>state.shellActions?.newAction()}><PlusIcon/></button>}
export function installConversationHeader(){const header=document.querySelector<HTMLElement>('main>header'),title=header?.querySelector<HTMLElement>('.header-title'),devices=document.getElementById('devices'),mobileNewHost=document.getElementById('mobile-new-host');if(!header||!title||!devices||!mobileNewHost)return;const actionHost=document.createElement('div');actionHost.id='conversation-header-actions';header.insertBefore(actionHost,mobileNewHost);createRoot(title).render(<ConversationTitle/>);createRoot(devices).render(<Devices/>);createRoot(actionHost).render(<><WorkPanelEntry/><HeaderActions/></>);createRoot(mobileNewHost).render(<MobileNew/>)}
