import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';

type Option={value:string;label:string};
type Field={name:string;id?:string;label:string;type?:'text'|'password'|'textarea'|'select'|'checkbox'|'avatar';value?:string|boolean;placeholder?:string;required?:boolean;maxLength?:number;rows?:number;options?:Option[];help?:string;hidden?:boolean};
type DecisionOption={id:string;label:string;description?:string;recommended?:boolean};
type DecisionConfig={memberName:string;decision:{id:string;title:string;question:string;options:DecisionOption[];allowOther?:boolean};onSubmit(values:Record<string,any>):Promise<any>|any};
type Config={id:string;title:string;description?:string;kind?:'decision';decision?:DecisionConfig;fields?:Field[];submitLabel?:string;cancelLabel?:string;danger?:boolean;readOnly?:boolean;onChange?:(values:Record<string,any>,name:string,value:any)=>Record<string,any>|void;onSubmit?:(values:Record<string,any>)=>Promise<any>|any};
type Request={config:Config;resolve:(value:any)=>void};
type DialogName='connection'|'connectionInfo'|'accessKey'|'newThread'|'renameThread'|'deleteThread'|'createGroup'|'member'|'modelSettings'|'decision'|'budget';
const formIds:Record<string,string>={'setup':'connect-form','create':'create-form','create-group-dialog':'create-group-form','member-dialog':'member-form','key-settings':'key-form','rename-dialog':'rename-form','delete-dialog':'delete-form','model-dialog':'model-form'};
const cancelIds:Record<string,string>={'create':'create-cancel','create-group-dialog':'create-group-cancel','member-dialog':'member-cancel','key-settings':'key-cancel','rename-dialog':'rename-cancel','delete-dialog':'delete-cancel','model-dialog':'model-cancel'};
const submitIds:Record<string,string>={'key-settings':'save-key','rename-dialog':'rename-save','delete-dialog':'delete-confirm','model-dialog':'model-save'};
const errorIds:Record<string,string>={'key-settings':'key-error','rename-dialog':'rename-error','delete-dialog':'delete-error','model-dialog':'model-error'};
const presets:Option[]=[{value:'preset:developer',label:'💻 开发'},{value:'preset:designer',label:'🎨 设计'},{value:'preset:tester',label:'🧪 测试'},{value:'preset:analyst',label:'📊 分析'},{value:'preset:operator',label:'🛠 运维'},{value:'preset:coordinator',label:'🧭 协调'},{value:'',label:'首字头像'}];
function memberFields(member:any,threads:any[]):Field[]{return[{name:'threadId',id:'member-thread',label:'关联会话',type:'select',value:member.threadId,required:true,options:threads.map(thread=>({value:thread.id,label:`${thread.name||thread.preview||'新会话'} · ${thread.cwd||'未知目录'}`}))},{name:'avatar',id:'member-avatar',label:'成员头像',type:'avatar',value:member.avatar||''},{name:'name',id:'member-name',label:'成员名称',value:member.name,required:true,maxLength:80},{name:'role',id:'member-role',label:'身份定位',value:member.role,required:true,maxLength:80},{name:'projectName',id:'member-project',label:'项目名称',value:member.projectName||'',maxLength:120},{name:'cwd',id:'member-cwd',label:'实际工作目录',value:member.cwd||'',required:true,help:'选择实际项目子目录，用于执行和并发冲突判断；必须位于关联会话目录内。同一父目录下不同项目可并行。'},{name:'responsibilities',id:'member-responsibilities',label:'职责范围',help:'用于选择负责人，不作为目录锁；请明确负责哪些项目和工作。',type:'textarea',value:member.responsibilities||'',maxLength:3000},{name:'operations',id:'member-operations',label:'允许的操作范围',type:'textarea',value:member.operations||'',maxLength:2000},{name:'skills',id:'member-skills',label:'擅长任务',type:'textarea',value:member.skills||'',maxLength:2000}]}
function dialogConfig(name:DialogName,props:any):Config{switch(name){
  case'budget':return{id:'budget-dialog',title:'协作总预算',description:'到限后停止后续派发，不中断当前执行。时间从首次派发起计算，包含排队和等待；Token 仅统计成员已观测用量，缺失时无法严格限额。0 表示不限。',fields:[{name:'maxRounds',label:'总轮次上限（1–100）',value:String(props.requirement.maxRounds||3),required:true},{name:'maxMinutes',label:'总时间预算（分钟）',value:String(props.requirement.budget?.maxMinutes||0),required:true},{name:'maxTokens',label:'已观测 Token 总预算',value:String(props.requirement.budget?.maxTokens||0),required:true}],submitLabel:'保存并继续',onSubmit:props.onSubmit};
  case'connection':return{id:'setup',title:'欢迎来到 Omega',description:'输入服务器的个人访问密钥。它只会保存在当前设备的安全存储中。',fields:[{name:'accessKey',id:'token',label:'访问密钥',type:'password',required:true}],submitLabel:'连接 →',onSubmit:props.onSubmit};
  case'connectionInfo':return{id:'key-settings',title:'连接设置',description:'当前密钥由服务器环境变量管理，不能在页面中修改。',readOnly:true,submitLabel:'关闭'};
  case'accessKey':return{id:'key-settings',title:'修改访问密钥',description:'保存后立即生效，其他设备需要使用新密钥重新连接。',fields:[{name:'accessKey',id:'new-key',label:'新密钥',type:'password',required:true,value:'',help:'至少 8 位'}],submitLabel:'保存密钥',onSubmit:props.onSubmit};
  case'newThread':return{id:'create',title:'新建会话',description:'文件与执行结果保存在此服务器目录。',fields:[{name:'cwd',id:'cwd',label:'服务器工作目录',value:props.cwd,required:true}],submitLabel:'开始工作 →',onSubmit:props.onSubmit};
  case'renameThread':return{id:'rename-dialog',title:'重命名会话',description:'名称会同步到其他设备，不影响聊天内容。',fields:[{name:'name',id:'rename-name',label:'会话名称',value:props.name,required:true,maxLength:80}],submitLabel:'保存',onSubmit:async values=>{const next=String(values.name||'').trim();if(!next)throw Error('请输入 1–80 个字符的会话名称');return props.onSubmit({name:next})}};
  case'deleteThread':return{id:'delete-dialog',title:'删除会话？',description:`将删除“${props.name}”及其子会话的聊天记录。项目文件不会删除，操作无法在 Omega 中恢复。`,danger:true,submitLabel:'确认删除',onSubmit:props.onSubmit};
  case'createGroup':return{id:'create-group-dialog',title:'新建群组',description:'群组可以添加不同项目、不同工作目录中的会话。',fields:[{name:'name',id:'group-name',label:'群组名称',required:true,maxLength:80},{name:'description',id:'group-project',label:'项目说明',type:'textarea',maxLength:4000},{name:'cwd',id:'group-workdir',label:'服务器工作目录',value:props.cwd,required:true},{name:'constraints',id:'group-constraints',label:'项目约束',type:'textarea',maxLength:8000}],submitLabel:'创建群组',onSubmit:props.onSubmit};
  case'member':{const{member,threads}=props;return{id:'member-dialog',title:props.editing?'编辑成员':'添加会话成员',description:props.editing?'修改后的定位用于后续派发，不改写历史任务。':'成员沿用所选 Codex 会话的上下文和工作目录。',fields:memberFields(member,threads),onChange:(values,field,value)=>{if(field!=='threadId'||(props.editing&&value===member.threadId))return;const thread=threads.find((item:any)=>item.id===value);return{cwd:thread?.cwd||'',projectName:(thread?.cwd||'').split('/').filter(Boolean).at(-1)||'',...(!props.editing&&values.name?{}:{name:thread?.name||thread?.preview||''})}},submitLabel:props.editing?'保存修改':'添加成员',onSubmit:props.onSubmit}}
  case'modelSettings':return{id:'model-dialog',title:'模型设置',description:props.description,fields:[{name:'model',id:'model-select',label:'模型',type:'select',value:props.model||'',options:[{value:'',label:'跟随当前会话配置'},...props.models.map((model:any)=>({value:model.model,label:model.displayName}))]},{name:'effort',id:'effort-select',label:'推理等级',type:'select',value:props.effort||'',options:[{value:'',label:'模型默认'},...props.efforts]}],submitLabel:'保存',onSubmit:props.onSubmit};
  case'decision':return{id:'decision-dialog',title:'需要你的决定',kind:'decision',decision:props};
}}
async function avatarFile(file:File){
  if(!/^image\/(?:png|jpeg|webp)$/.test(file.type))throw Error('头像仅支持 PNG、JPEG 或 WebP');
  if(file.size>4*1024*1024)throw Error('头像图片不得超过 4 MB');
  const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;
  const context=canvas.getContext('2d');if(!context){bitmap.close();throw Error('无法处理头像')}
  const scale=Math.max(128/bitmap.width,128/bitmap.height),width=bitmap.width*scale,height=bitmap.height*scale;
  context.drawImage(bitmap,(128-width)/2,(128-height)/2,width,height);bitmap.close();
  const webp=canvas.toDataURL('image/webp',.82);
  if(webp.startsWith('data:image/webp;')&&webp.length<=100000)return webp;
  const jpeg=canvas.toDataURL('image/jpeg',.78);
  if(jpeg.length<=100000)return jpeg;
  throw Error('压缩后的头像仍然过大，请选择更简单的图片');
}
function FormModal({request,close}:{request:Request;close:(value:any)=>void}){const{config}=request,[values,setValues]=useState<Record<string,any>>(()=>Object.fromEntries((config.fields||[]).map(field=>[field.name,field.value??(field.type==='checkbox'?false:'')]))),[busy,setBusy]=useState(false),[error,setError]=useState(''),first=useRef<HTMLInputElement|null>(null),dialog=useRef<HTMLDialogElement|null>(null);useLayoutEffect(()=>dialog.current?.showModal(),[]);useEffect(()=>first.current?.focus(),[]);const change=(name:string,value:any)=>setValues(old=>{const next={...old,[name]:value};return{...next,...config.onChange?.(next,name,value)}});const submit=async(event:React.FormEvent)=>{event.preventDefault();if(config.readOnly)return close(null);setBusy(true);setError('');try{await config.onSubmit?.(values);close(values)}catch(value){setError(value instanceof Error?value.message:String(value));setBusy(false)}};return <dialog ref={dialog} id={config.id} className="react-form-dialog" onCancel={event=>{event.preventDefault();if(!busy)close(null)}}><form id={formIds[config.id]} onSubmit={submit}>
  <h2>{config.title}</h2>{config.description&&<p>{config.description}</p>}
  {(config.fields||[]).filter(field=>!field.hidden).map((field,index)=>{const fieldValue=String(values[field.name]||''),customAvatar=field.type==='avatar'&&fieldValue.startsWith('data:image/');return <label key={field.name}>{field.label}{field.type==='textarea'?<textarea id={field.id} rows={field.rows||3} maxLength={field.maxLength} required={field.required} placeholder={field.placeholder} value={fieldValue} onChange={e=>change(field.name,e.target.value)}/>:field.type==='select'?<select id={field.id} required={field.required} value={fieldValue} onChange={e=>change(field.name,e.target.value)}>{field.options?.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select>:field.type==='checkbox'?<input id={field.id} type="checkbox" checked={Boolean(values[field.name])} onChange={e=>change(field.name,e.target.checked)}/>:field.type==='avatar'?<div className="react-avatar-field"><select id={field.id} value={fieldValue} onChange={e=>change(field.name,e.target.value)}>{customAvatar&&<option value={fieldValue}>自定义头像</option>}{presets.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select><input id="member-avatar-file" type="file" accept="image/png,image/jpeg,image/webp" aria-label="上传头像" onChange={async e=>{const file=e.target.files?.[0];if(file)try{change(field.name,await avatarFile(file))}catch(value){setError(value instanceof Error?value.message:String(value))}}}/>{customAvatar&&<img id="member-avatar-preview" src={fieldValue} aria-label="头像预览"/>}</div>:<input ref={index===0?first:undefined} id={field.id} type={field.type||'text'} maxLength={field.maxLength} required={field.required} placeholder={field.placeholder} value={fieldValue} onChange={e=>change(field.name,e.target.value)}/>} {field.help&&<small>{field.help}</small>}</label>})}
  {error&&<p id={errorIds[config.id]} className="dialog-error" role="alert">{error}</p>}<div className="dialog-actions"><button id={cancelIds[config.id]} type="button" className="secondary" disabled={busy} onClick={()=>close(null)}>{config.cancelLabel||'取消'}</button><button id={submitIds[config.id]} type="submit" className={config.danger?'danger':''} disabled={busy}>{busy?'处理中…':config.submitLabel||(config.readOnly?'关闭':'保存')}</button></div>
  </form></dialog>}
function DecisionModal({request,close}:{request:Request;close:(value:any)=>void}){const config=request.config.decision!,decision=config.decision,initial=decision.options.find(option=>option.recommended)?.id||decision.options[0]?.id||'',dialog=useRef<HTMLDialogElement|null>(null),[choiceId,setChoiceId]=useState(initial),[custom,setCustom]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');useLayoutEffect(()=>dialog.current?.showModal(),[]);const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!choiceId||choiceId==='other'&&!custom.trim())return;setBusy(true);setError('');try{const value={decisionId:decision.id,choiceId,custom:custom.trim(),note:note.trim()};await config.onSubmit(value);close(value)}catch(value){setError(value instanceof Error?value.message:String(value));setBusy(false)}};return <dialog ref={dialog} id="decision-dialog" className="react-form-dialog decision-dialog" onCancel={event=>{event.preventDefault();if(!busy)close(null)}}><form onSubmit={submit}>
  <header><div><h2>需要你的决定</h2><p>回复给 <strong>@{config.memberName}</strong></p></div><button type="button" className="decision-close" aria-label="稍后处理" disabled={busy} onClick={()=>close(null)}>×</button></header>
  <section className="decision-context"><strong>{decision.title}</strong><p>{decision.question}</p></section>
  <fieldset className="decision-options"><legend>请选择一个方案</legend>{decision.options.map(option=><label className={`decision-option ${choiceId===option.id?'selected':''}`} key={option.id}><input type="radio" name="decision-choice" value={option.id} checked={choiceId===option.id} onChange={()=>setChoiceId(option.id)}/><span><strong>{option.label}{option.recommended&&<em>推荐</em>}</strong>{option.description&&<small>{option.description}</small>}</span></label>)}{decision.allowOther!==false&&<label className={`decision-option ${choiceId==='other'?'selected':''}`}><input type="radio" name="decision-choice" value="other" checked={choiceId==='other'} onChange={()=>setChoiceId('other')}/><span><strong>其他方案</strong><small>按你的方式继续处理</small></span></label>}</fieldset>
  {choiceId==='other'&&<label>你的方案<textarea rows={3} maxLength={2000} required value={custom} placeholder="说明希望采用的方案…" onChange={event=>setCustom(event.target.value)}/></label>}
  <label>补充要求（可选）<textarea rows={3} maxLength={3000} value={note} placeholder="补充范围、约束或注意事项…" onChange={event=>setNote(event.target.value)}/></label>
  {error&&<p className="dialog-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>close(null)}>稍后处理</button><button type="submit" disabled={busy||!choiceId||choiceId==='other'&&!custom.trim()}>{busy?'正在回复…':'确认并回复'}</button></div>
  </form></dialog>}
function Layer(){const[request,setRequest]=useState<Request|null>(null);useEffect(()=>{const open=(config:Config)=>new Promise(resolve=>setRequest({config,resolve}));window.omegaReactForms={open};window.omegaDialogs={open:(name,props)=>open(dialogConfig(name as DialogName,props))};window.dispatchEvent(new Event('omega:react-forms-ready'));window.dispatchEvent(new Event('omega:dialogs-ready'));return()=>{delete window.omegaReactForms;delete window.omegaDialogs}},[]);const close=(value:any)=>{request?.resolve(value);setRequest(null)};return request?(request.config.kind==='decision'?<DecisionModal key={request.config.decision?.decision.id} request={request} close={close}/>:<FormModal key={request.config.id+request.config.title} request={request} close={close}/>):null}
export function installFormLayer(){const native=Boolean((globalThis as any).__OMEGA_NATIVE__);for(const id of ['setup','key-settings'])if(!native)document.getElementById(id)?.remove();const host=document.createElement('div');host.id='omega-form-layer';host.dataset.reactOwned='true';document.body.append(host);createRoot(host).render(<Layer/>)}
