import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';

type Option={value:string;label:string};
type Field={name:string;id?:string;label:string;type?:'text'|'password'|'textarea'|'select'|'checkbox'|'avatar';value?:string|boolean;placeholder?:string;required?:boolean;maxLength?:number;rows?:number;options?:Option[];help?:string;hidden?:boolean};
type Config={id:string;title:string;description?:string;fields?:Field[];submitLabel?:string;cancelLabel?:string;danger?:boolean;readOnly?:boolean;onChange?:(values:Record<string,any>,name:string,value:any)=>Record<string,any>|void;onSubmit?:(values:Record<string,any>)=>Promise<any>|any};
type Request={config:Config;resolve:(value:any)=>void};
const formIds:Record<string,string>={'setup':'connect-form','create':'create-form','create-group-dialog':'create-group-form','member-dialog':'member-form','feedback-dialog':'feedback-form','task-dialog':'task-form','key-settings':'key-form','rename-dialog':'rename-form','delete-dialog':'delete-form','model-dialog':'model-form'};
const cancelIds:Record<string,string>={'create':'create-cancel','create-group-dialog':'create-group-cancel','member-dialog':'member-cancel','feedback-dialog':'feedback-cancel','task-dialog':'task-cancel','key-settings':'key-cancel','rename-dialog':'rename-cancel','delete-dialog':'delete-cancel','model-dialog':'model-cancel'};
const submitIds:Record<string,string>={'key-settings':'save-key','rename-dialog':'rename-save','delete-dialog':'delete-confirm','model-dialog':'model-save'};
const errorIds:Record<string,string>={'key-settings':'key-error','rename-dialog':'rename-error','delete-dialog':'delete-error','model-dialog':'model-error'};
const presets:Option[]=[{value:'preset:developer',label:'💻 开发'},{value:'preset:designer',label:'🎨 设计'},{value:'preset:tester',label:'🧪 测试'},{value:'preset:analyst',label:'📊 分析'},{value:'preset:operator',label:'🛠 运维'},{value:'preset:coordinator',label:'🧭 协调'},{value:'',label:'首字头像'}];
async function avatarFile(file:File){if(file.size>4*1024*1024)throw Error('头像图片不得超过 4 MB');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const context=canvas.getContext('2d');if(!context)throw Error('无法处理头像');const scale=Math.max(128/bitmap.width,128/bitmap.height),width=bitmap.width*scale,height=bitmap.height*scale;context.drawImage(bitmap,(128-width)/2,(128-height)/2,width,height);bitmap.close();return canvas.toDataURL('image/jpeg',.82)}
function FormModal({request,close}:{request:Request;close:(value:any)=>void}){const{config}=request,[values,setValues]=useState<Record<string,any>>(()=>Object.fromEntries((config.fields||[]).map(field=>[field.name,field.value??(field.type==='checkbox'?false:'')]))),[busy,setBusy]=useState(false),[error,setError]=useState(''),first=useRef<HTMLInputElement|null>(null),dialog=useRef<HTMLDialogElement|null>(null);useLayoutEffect(()=>dialog.current?.showModal(),[]);useEffect(()=>first.current?.focus(),[]);const change=(name:string,value:any)=>setValues(old=>{const next={...old,[name]:value};return{...next,...config.onChange?.(next,name,value)}});const submit=async(event:React.FormEvent)=>{event.preventDefault();if(config.readOnly)return close(null);setBusy(true);setError('');try{await config.onSubmit?.(values);close(values)}catch(value){setError(value instanceof Error?value.message:String(value));setBusy(false)}};return <dialog ref={dialog} id={config.id} className="react-form-dialog" onCancel={event=>{event.preventDefault();if(!busy)close(null)}}><form id={formIds[config.id]} onSubmit={submit}>
  <h2>{config.title}</h2>{config.description&&<p>{config.description}</p>}
  {(config.fields||[]).filter(field=>!field.hidden).map((field,index)=><label key={field.name}>{field.label}{field.type==='textarea'?<textarea id={field.id} rows={field.rows||3} maxLength={field.maxLength} required={field.required} placeholder={field.placeholder} value={String(values[field.name]||'')} onChange={e=>change(field.name,e.target.value)}/>:field.type==='select'?<select id={field.id} required={field.required} value={String(values[field.name]||'')} onChange={e=>change(field.name,e.target.value)}>{field.options?.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select>:field.type==='checkbox'?<input id={field.id} type="checkbox" checked={Boolean(values[field.name])} onChange={e=>change(field.name,e.target.checked)}/>:field.type==='avatar'?<div className="react-avatar-field"><select id={field.id} value={String(values[field.name]||'')} onChange={e=>change(field.name,e.target.value)}>{presets.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select><input id="member-avatar-file" type="file" accept="image/png,image/jpeg,image/webp" aria-label="上传头像" onChange={async e=>{const file=e.target.files?.[0];if(file)try{change(field.name,await avatarFile(file))}catch(value){setError(value instanceof Error?value.message:String(value))}}}/>{String(values[field.name]||'').startsWith('data:image/')&&<img id="member-avatar-preview" src={values[field.name]} aria-label="头像预览"/>}</div>:<input ref={index===0?first:undefined} id={field.id} type={field.type||'text'} maxLength={field.maxLength} required={field.required} placeholder={field.placeholder} value={String(values[field.name]||'')} onChange={e=>change(field.name,e.target.value)}/>} {field.help&&<small>{field.help}</small>}</label>)}
  {error&&<p id={errorIds[config.id]} className="dialog-error" role="alert">{error}</p>}<div className="dialog-actions"><button id={cancelIds[config.id]} type="button" className="secondary" disabled={busy} onClick={()=>close(null)}>{config.cancelLabel||'取消'}</button><button id={submitIds[config.id]} type="submit" className={config.danger?'danger':''} disabled={busy}>{busy?'处理中…':config.submitLabel||(config.readOnly?'关闭':'保存')}</button></div>
  </form></dialog>}
function Layer(){const[request,setRequest]=useState<Request|null>(null);useEffect(()=>{window.omegaReactForms={open:config=>new Promise(resolve=>setRequest({config,resolve}))};window.dispatchEvent(new Event('omega:react-forms-ready'));return()=>{delete window.omegaReactForms}},[]);const close=(value:any)=>{request?.resolve(value);setRequest(null)};return request?<FormModal key={request.config.id+request.config.title} request={request} close={close}/>:null}
export function installFormLayer(){const native=Boolean((globalThis as any).__OMEGA_NATIVE__);for(const id of ['setup','create','create-group-dialog','member-dialog','feedback-dialog','task-dialog','key-settings','rename-dialog','delete-dialog','model-dialog'])if(!native||!['setup','key-settings'].includes(id))document.getElementById(id)?.remove();const host=document.createElement('div');host.id='omega-form-layer';host.dataset.reactOwned='true';document.body.append(host);createRoot(host).render(<Layer/>)}
