import {useEffect,useState} from 'react';
import {flushSync} from 'react-dom';
import {createRoot} from 'react-dom/client';
import {createPortal} from 'react-dom';
import {appStore,useAppState} from './AppState.js';

type Member={id:string;threadId:string;name:string;role:string;avatar?:string;projectName?:string;cwd:string;responsibilities?:string};
type Decision={id:string;title:string;question:string;status:string;requestedAt?:string;answer?:{label:string}};
type Task={id:string;memberId:string;status:string;turnId?:string|null;attempt?:number;round?:number;title?:string;error?:string;queueReason?:string;decision?:Decision};
type Requirement={id:string;content:string;status:string;pauseKind?:'budget'|'recovery'|'execution'|null;taskCount?:number;tasksTruncated?:boolean;maxRounds?:number;budget?:{maxMinutes?:number;maxTokens?:number};budgetUsage?:{tokens:number|null};plan?:{summary?:string};createdAt?:string;updatedAt?:string;tasks?:Task[]};
type Message={requirementId?:string;kind:string;author:string};
type Layout={mobile:boolean;membersOpen:boolean;questionsOpen:boolean};
const preset:Record<string,string>={developer:'💻',designer:'🎨',tester:'🧪',analyst:'📊',operator:'🛠',coordinator:'🧭'};
const states:Record<string,string>={plan_drafting:'未回复',awaiting_confirmation:'未回复',running:'回复中',finalizing:'回复中',awaiting_acceptance:'已回复',accepted:'已回复',cancelled:'已取消',paused:'执行异常',queued:'未回复',completed:'已回复',failed:'执行异常',unknown:'需核对',reviewing:'回复中'};
const tickingRequirementStates=new Set(['plan_drafting','awaiting_confirmation','queued','running','reviewing','finalizing']);
let layout:Layout={mobile:matchMedia('(max-width:800px)').matches,membersOpen:false,questionsOpen:false};
const mergeWorkspace=(value:Record<string,unknown>)=>appStore.patch({groupWorkspace:{...(appStore.getSnapshot().groupWorkspace||{}),...value}});

function Avatar({member}:{member:Member}){if(member.avatar?.startsWith('data:image/'))return <img className="member-avatar" src={member.avatar} aria-hidden/>;return <span className="member-avatar" aria-hidden>{member.avatar?.startsWith('preset:')?preset[member.avatar.slice(7)]:(Array.from(member.name)[0]||'成')}</span>}
function Members({members=[],busy=new Set(),removable=false,coordinatorThreadId,coordinatorThreadName,coordinatorOwned=true,actions}:{members?:Member[];busy?:Set<string>;removable?:boolean;coordinatorThreadId?:string;coordinatorThreadName?:string;coordinatorOwned?:boolean;actions:any}){return <>{coordinatorThreadId&&<article className="member-card coordinator-card">
  <div className="member-card-head"><span className="member-avatar" aria-hidden>🧭</span><div className="member-identity"><strong>协调者</strong><span>规划 · 小结 · 归档</span></div></div>
  <small className="member-workspace">{coordinatorOwned?'Omega 专用会话':'你指定的会话'} · {coordinatorThreadName||coordinatorThreadId}</small>
  <div className="member-actions"><button type="button" className="member-edit" onClick={()=>actions.editCoordinator()}>指定会话</button><button type="button" className="link-button" onClick={()=>actions.open(coordinatorThreadId)}>打开会话</button></div>
  </article>}{members.map(member=><article className="member-card" key={member.id}>
  <div className="member-card-head"><Avatar member={member}/><div className="member-identity"><strong title={member.name}>{member.name}</strong><span title={member.role}>{member.role}</span></div></div>
  <small className="member-workspace">{busy.has(member.id)?'处理中':'空闲'} · {member.projectName||'未命名项目'} · {member.cwd}</small>
  {member.responsibilities&&<p>{member.responsibilities}</p>}
  <div className="member-actions"><button type="button" className="member-edit" onClick={()=>actions.edit(member)}>编辑</button><button type="button" className="link-button" onClick={()=>actions.open(member.threadId)}>打开会话</button>{removable&&<button type="button" className="member-remove" onClick={()=>actions.remove(member.id)}>移出群组</button>}</div>
  </article>)}</>}
type MemoryEntry={id:string;title:string;summary:string;openItems:string[];status:string;revision:number;updatedAt:string;detail?:Record<string,any>};
function GroupMemoryDialog({actions,close}:{actions:any;close():void}){
  const[items,setItems]=useState<MemoryEntry[]>([]),[entry,setEntry]=useState<MemoryEntry|null>(null),[history,setHistory]=useState<any[]>([]),[summary,setSummary]=useState(''),[openItems,setOpenItems]=useState(''),[status,setStatus]=useState('active'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[failure,setFailure]=useState('');
  useEffect(()=>{let live=true;actions.memoryList().then((value:any)=>{if(live)setItems(value.items||[])}).catch((error:Error)=>{if(live)setFailure(error.message)}).finally(()=>{if(live)setLoading(false)});const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();close()}};window.addEventListener('keydown',onKey);return()=>{live=false;window.removeEventListener('keydown',onKey)}},[]);
  async function select(id:string){setFailure('');try{const [result,revisions]=await Promise.all([actions.memoryGet(id),actions.memoryHistory(id)]);const next=result.entry as MemoryEntry;setEntry(next);setSummary(next.summary);setOpenItems(next.openItems.join('\n'));setStatus(next.status);setHistory(revisions.items||[])}catch(error){setFailure((error as Error).message)}}
  async function save(){if(!entry)return;setSaving(true);setFailure('');try{const result=await actions.memorySave({id:entry.id,revision:entry.revision,summary,openItems:openItems.split('\n').map(line=>line.trim()).filter(Boolean),status});const next=result.entry as MemoryEntry;setEntry(next);setItems(value=>value.map(item=>item.id===next.id?next:item));setHistory((await actions.memoryHistory(next.id)).items||[])}catch(error){setFailure((error as Error).message)}finally{setSaving(false)}}
  async function more(){if(!items.length)return;try{const result=await actions.memoryList(items.at(-1)?.id);setItems(value=>[...value,...(result.items||[])]);if(!(result.items||[]).length)setFailure('没有更早的档案了')}catch(error){setFailure((error as Error).message)}}
  return createPortal(<div className="group-memory-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="group-memory-dialog" role="dialog" aria-modal="true" aria-label="群组档案"><header><div><h2>群组档案</h2><small>自动归档是线索，不是已确认事实；修改保留版本记录。</small></div><button type="button" onClick={close} aria-label="关闭">×</button></header><div className="group-memory-body"><nav aria-label="归档问题">{loading?<p>正在读取…</p>:items.length?items.map(item=><button type="button" key={item.id} className={entry?.id===item.id?'selected':''} onClick={()=>select(item.id)}><strong>{item.title}</strong><small>{item.status==='stale'?'已标记过时':'可供检索'} · {new Date(item.updatedAt).toLocaleString()}</small></button>):<p>暂无群组档案。已完成的问题会由协调者整理。</p>}{items.length>=30&&<button type="button" onClick={more}>加载更早记录</button>}</nav><main>{entry?<><h3>{entry.title}</h3><label>摘要<textarea value={summary} maxLength={1800} rows={7} onChange={event=>setSummary(event.target.value)}/></label><label>未完成 / 待核实事项（每行一项，最多 10 项）<textarea value={openItems} rows={5} onChange={event=>setOpenItems(event.target.value)}/></label><label>状态<select value={status} onChange={event=>setStatus(event.target.value)}><option value="active">可供后续检索</option><option value="stale">已过时，不再注入上下文</option></select></label><button type="button" disabled={saving} onClick={save}>保存修正</button><details><summary>原始问题与成员结果</summary><pre>{JSON.stringify(entry.detail,null,2)}</pre></details><details><summary>修订记录（{history.length}）</summary>{history.map(item=><article key={item.revision}><strong>第 {item.revision} 版</strong> · {item.actor} · {new Date(item.createdAt).toLocaleString()}<pre>{JSON.stringify(item.snapshot,null,2)}</pre></article>)}</details></>:<p>选择一条档案查看、纠正或标记过时。完整问答与讨论报告仅在这里按需读取，不会整体塞进后续会话。</p>}</main></div>{failure&&<p className="group-memory-error" role="alert">{failure}</p>}</section></div>,document.body);
}
function elapsed(start?:string,end?:string){const value=Date.parse(end||new Date().toISOString())-Date.parse(start||'');if(!Number.isFinite(value))return'—';const seconds=Math.max(0,Math.floor(value/1000));if(seconds<60)return`${seconds} 秒`;const minutes=Math.floor(seconds/60);return minutes<60?`${minutes} 分 ${seconds%60} 秒`:`${Math.floor(minutes/60)} 小时 ${minutes%60} 分`;}
function Questions({requirements=[],messages=[],members=[],actions,onFocus}:{requirements?:Requirement[];messages?:Message[];members?:Member[];actions:any;onFocus():void}){const[,tick]=useState(0);useEffect(()=>{const id=setInterval(()=>tick(value=>value+1),1000);return()=>clearInterval(id)},[]);return <>{requirements.map((requirement,index)=>{const ticking=tickingRequirementStates.has(requirement.status),responders=[...new Set(messages.filter(message=>message.requirementId===requirement.id&&['member','coordinator'].includes(message.kind)).map(message=>message.author))],task=requirement.tasks?.find(item=>item.status==='awaiting_input'&&item.decision?.status==='pending'),decision=task?.decision,member=task&&members.find(item=>item.id===task.memberId),missingRollout=requirement.tasks?.some(item=>item.status==='unknown'&&!item.turnId&&/^no rollout found for thread id [0-9a-f-]+$/i.test(item.error||''));return <article className="task-card question-card" data-status={decision?'awaiting_input':requirement.status} key={requirement.id}>
  <button type="button" className="question-link" onClick={()=>{actions.focus(requirement.id);onFocus()}}><span className="question-number">{requirements.length-index}</span>{decision?.title||requirement.content.slice(0,120)}</button>
  <div className="question-meta"><span className="question-state">{decision?'待你决策':(requirement.status==='paused'?({budget:'等待追加预算',recovery:'等待核对结果',execution:'执行异常'}[requirement.pauseKind||'execution']):states[requirement.status])||'未回复'}</span><span>·</span><time className="question-duration">{decision?`等待 ${elapsed(decision.requestedAt)}`:elapsed(requirement.createdAt,ticking?undefined:(requirement.updatedAt||requirement.createdAt))}</time></div>
  {requirement.tasks?.filter(item=>item.status==='awaiting_input'&&item.decision?.status==='pending').map(item=><button key={item.id} type="button" className="question-decide" onClick={()=>{actions.decide({taskId:item.id,requirementId:requirement.id,memberName:members.find(m=>m.id===item.memberId)?.name||'成员',decision:item.decision});onFocus()}}>{members.find(m=>m.id===item.memberId)?.name||'成员'}：{item.decision?.title} · 去决策</button>)}
  {!!responders.length&&<small className="question-responders">{responders.join('、')}</small>}
  {requirement.status==='paused'&&requirement.pauseKind!=='budget'&&<button type="button" onClick={()=>{if(!requirement.tasks?.some(item=>item.status==='failed')||window.confirm('重新执行失败任务？已有的文件修改不会回滚，请先核对执行结果。'))actions.retry(requirement.id)}}>{missingRollout?'重试未派发任务':requirement.pauseKind==='recovery'?'核对原执行':'重试失败任务'}</button>}
  <details><summary>分配与执行详情</summary>{requirement.tasksTruncated&&<small>共 {requirement.taskCount} 项，仅展示待执行前 120 项和最近 80 项；完整回复可在聊天中翻阅。</small>}<small>已观测 Token：{requirement.budgetUsage?.tokens??'暂无数据'}</small>{['running','paused'].includes(requirement.status)&&<button type="button" onClick={()=>actions.budget(requirement)}>调整预算 / 继续</button>}{requirement.plan?.summary&&<p>{requirement.plan.summary}</p>}{requirement.tasks?.map(item=><div key={item.id}><small className="question-responders">{members.find(member=>member.id===item.memberId)?.name||'成员'} · 第 {item.round||1} 轮 · {item.queueReason||states[item.status]||item.status}{item.title?` · ${item.title}`:''}</small>{item.error&&<small>{item.error}</small>}{item.status==='queued'&&!item.attempt&&!item.decision&&<label>改派给 <select aria-label="改派负责人" value={item.memberId} onChange={event=>actions.reassign(item.id,event.target.value)}>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}</div>)}</details>
  </article>})}</>}

function saved(side:'members'|'tasks'){try{return localStorage.getItem(`omega-group-${side}-collapsed`)!=='1'}catch{return true}}
function GroupWorkspace(){const workspace=useAppState().groupWorkspace||{},[mobile,setMobile]=useState(()=>matchMedia('(max-width:800px)').matches),[membersOpen,setMembersOpen]=useState(()=>!matchMedia('(max-width:800px)').matches&&saved('members')),[questionsOpen,setQuestionsOpen]=useState(()=>!matchMedia('(max-width:800px)').matches&&saved('tasks')),[memoryGroup,setMemoryGroup]=useState<string|null>(null);
  const closePanels=()=>{if(mobile){setMembersOpen(false);setQuestionsOpen(false)}};
  const toggle=(side:'members'|'tasks')=>{if(mobile){setMembersOpen(value=>side==='members'?!value:false);setQuestionsOpen(value=>side==='tasks'?!value:false);return}if(side==='members')setMembersOpen(value=>{try{localStorage.setItem('omega-group-members-collapsed',value?'1':'0')}catch{}return!value});else setQuestionsOpen(value=>{try{localStorage.setItem('omega-group-tasks-collapsed',value?'1':'0')}catch{}return!value})};
  useEffect(()=>{const query=matchMedia('(max-width:800px)'),change=()=>{setMobile(query.matches);setMembersOpen(query.matches?false:saved('members'));setQuestionsOpen(query.matches?false:saved('tasks'))};query.addEventListener('change',change);return()=>query.removeEventListener('change',change)},[]);
  useEffect(()=>{const handler=(event:Event)=>toggle((event as CustomEvent<'members'|'tasks'>).detail);window.addEventListener('omega:toggle-group-panel',handler);return()=>window.removeEventListener('omega:toggle-group-panel',handler)},[mobile]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&mobile&&(membersOpen||questionsOpen)){event.preventDefault();closePanels()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[mobile,membersOpen,questionsOpen]);
  useEffect(()=>{const host=document.getElementById('group-view');if(!host)return;host.classList.toggle('members-collapsed',!membersOpen);host.classList.toggle('tasks-collapsed',!questionsOpen);if(mobile&&(membersOpen||questionsOpen))host.dataset.mobilePanel=membersOpen?'members':'tasks';else delete host.dataset.mobilePanel;layout={mobile,membersOpen,questionsOpen};const header=appStore.getSnapshot().groupHeader;if(header&&(header.mobile!==mobile||header.membersOpen!==membersOpen||header.questionsOpen!==questionsOpen))appStore.patch({groupHeader:{...header,mobile,membersOpen,questionsOpen}})},[mobile,membersOpen,questionsOpen]);
  const members=workspace.membersModel?.members||[],questions=workspace.questionsModel?.requirements||[];
  return <div className="group-columns">
    <aside className="group-panel"><div className="panel-title"><h2>成员</h2><span>{members.length+(workspace.membersModel?.coordinatorThreadId?1:0)} 位</span><button type="button" className="mobile-panel-close" onClick={closePanels}>关闭</button></div><div id="group-members" data-react-owned="true"><Members {...workspace.membersModel} actions={workspace.memberActions||{}}/></div><div className="summary-card"><h3>群组摘要</h3><p>{workspace.summary||'协调者会持续整理目标、约束和进度。'}</p>{workspace.active&&<button type="button" onClick={()=>setMemoryGroup(workspace.membersModel?.groupId||null)}>查看群组档案</button>}</div></aside>
    <button type="button" className="group-panel-backdrop" aria-label="关闭侧栏" onClick={closePanels}/>
    <section className="group-center"><div id="group-timeline" aria-live="polite"></div><form id="requirement-form" hidden={!workspace.active}></form></section>
    <aside className="group-panel task-panel"><div className="panel-title"><h2>问题定位</h2><span>{questions.length?`${questions.length} 个问题`:''}</span><button type="button" className="mobile-panel-close" onClick={closePanels}>关闭</button></div><div id="group-tasks" data-react-owned="true"><Questions {...workspace.questionsModel} members={members} actions={workspace.questionActions||{}} onFocus={closePanels}/></div></aside>
    {memoryGroup===workspace.membersModel?.groupId&&<GroupMemoryDialog key={memoryGroup} actions={workspace.memberActions} close={()=>setMemoryGroup(null)}/>}
  </div>}

export function installGroupPanels(){const host=document.getElementById('group-view');if(!host)return;host.dataset.reactOwned='true';flushSync(()=>createRoot(host).render(<GroupWorkspace/>));window.omegaReactGroupPanels={
  renderMembers:(model,actions)=>mergeWorkspace({membersModel:model,memberActions:actions,summary:model.summary,active:model.active}),
  renderQuestions:(model,actions)=>mergeWorkspace({questionsModel:model,questionActions:actions}),
  toggle:(side)=>window.dispatchEvent(new CustomEvent('omega:toggle-group-panel',{detail:side})),
  getLayout:()=>layout,
};window.dispatchEvent(new Event('omega:react-group-panels-ready'))}
