import {CopyMessage} from './CopyMessage.js';
import {GroupImage,GroupImageLoader} from './GroupImage.js';
import {splitImageText,imageSafeSlice} from '../../src/shared/inline-images.js';
import {forwardRef,useEffect,useImperativeHandle,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {renderMarkdown} from './ChatTimeline.js';

type DecisionOption={id:string;label:string;description?:string;recommended?:boolean};
type Decision={id:string;title:string;question:string;options:DecisionOption[];allowOther?:boolean;status:'pending'|'resolved';requestedAt?:string;respondedAt?:string;answer?:{choiceId:string;label:string;note?:string}};
type Message={id:string;kind:string;author:string;content:string;createdAt:string;requirementId?:string;reference?:Record<string,any>};
type Member={id:string;name:string;avatar?:string};
type Task={id:string;memberId:string;status:string;round?:number;decision?:Decision};
type Requirement={id:string;content:string;status:string;collaborationMode?:string;maxRounds?:number;pastedTexts?:any[];tasks?:Task[]};
interface Model{group:{id?:string;members:Member[]};messages:Message[];requirements:Requirement[];active:Requirement[]}
interface Actions{loadImage(ref:{id:string;expiresAt:number},thumb:boolean,signal:AbortSignal):Promise<Blob>;loadWindow(query:string):Promise<Message[]>;select(id:string):void;openThread(id:string):void;reply(value:{taskId:string;name:string}):void;decide(value:{taskId:string;requirementId:string;memberName:string;decision:Decision}):void;cancel(value:Requirement):Promise<void>;report(message:string):void}
interface RoomHandle{focus(id:string):Promise<boolean>;clear():void;returnToLatest():void}
type WindowState={groupId:string;messages:Message[];historical:boolean;more:boolean};

const preset:Record<string,string>={developer:'💻',designer:'🎨',tester:'🧪',analyst:'📊',operator:'🛠',coordinator:'🧭'};
function Avatar({value,name}:{value?:string;name:string}){if(value?.startsWith('data:image/'))return <img className="chat-avatar" aria-hidden src={value}/>;const icon=value?.startsWith('preset:')?preset[value.slice(7)]:undefined;return <span className="chat-avatar" aria-hidden>{icon||Array.from(name)[0]?.toUpperCase()||'Ω'}</span>}
function Content({message}:{message:Message}){const[limit,setLimit]=useState(6000),rich=['member','coordinator'].includes(message.kind),body=imageSafeSlice(message.content,0,limit),html=useMemo(()=>rich?renderMarkdown(body):'',[body,rich]);return <div className={rich?'copy-reply':undefined}>{rich?<div className="markdown-body" dangerouslySetInnerHTML={{__html:html}}/>:<div className="group-message-text">{splitImageText(body,(message.reference?.images||[]).map((i:any)=>i.id)).map((part,index)=>part.type==='text'?part.text:<GroupImage key={index} image={message.reference!.images.find((i:any)=>i.id===part.id)}/>)}</div>}{rich&&<CopyMessage read={()=>message.content}/>}{limit<message.content.length&&<button className="reference-link" onClick={()=>setLimit(value=>value+6000)}>展开后续内容</button>}</div>}
function LazyContent({message}:{message:Message}){const host=useRef<HTMLDivElement>(null),[visible,setVisible]=useState(false),height=useRef(96);useEffect(()=>{const node=host.current;if(!node)return;const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)height.current=Math.max(48,node.getBoundingClientRect().height);setVisible(entry.isIntersecting);}},{root:node.closest('#group-timeline'),rootMargin:'600px'});observer.observe(node);return()=>observer.disconnect()},[]);return <div ref={host} style={visible?undefined:{minHeight:height.current}}>{visible?<Content message={message}/>:<span className="message-placeholder">消息内容 · 滚动到此处加载</span>}</div>}
function ProgressContent({message,running}:{message:Message;running:boolean}){const[open,setOpen]=useState(false);return <details onToggle={event=>setOpen(event.currentTarget.open)}><summary>{running?'正在处理…':'处理进度'} · 展开详情</summary>{open&&<LazyContent message={message}/>}</details>}
function DecisionRequest({task,requirementId,memberName,actions}:{task:Task;requirementId:string;memberName:string;actions:Actions}){const decision=task.decision;if(!decision)return null;if(decision.status==='resolved')return <div className="decision-request resolved"><span>已决策</span><strong>{decision.answer?.label||'已回复'}</strong>{decision.answer?.note&&<small>{decision.answer.note}</small>}</div>;return <div className="decision-request pending"><div><span>需要你的决定</span><strong>{decision.title}</strong><small>{decision.question}</small></div><button type="button" onClick={()=>actions.decide({taskId:task.id,requirementId,memberName,decision})}>去决策</button></div>}

const Timeline=forwardRef<RoomHandle,{model:Model;actions:Actions;area:HTMLElement}>(({model,actions,area},ref)=>{
  const[windowState,setWindowState]=useState<WindowState|null>(null),[followLatest,setFollowLatest]=useState(true),[focusRevision,setFocusRevision]=useState(0),[cancelling,setCancelling]=useState<string|null>(null),focusId=useRef<string|null>(null),focusDone=useRef<((value:boolean)=>void)|null>(null),scrollTarget=useRef<'top'|'bottom'|null>('bottom'),highlightTimer=useRef<ReturnType<typeof setTimeout>|null>(null),highlighted=useRef<HTMLElement|null>(null);
  const requestSequence=useRef(0),activeGroup=useRef(model.group.id);activeGroup.current=model.group.id;
  const groupId=model.group.id||'',state=windowState?.groupId===groupId?windowState:null,messages=(state?.historical?state.messages:model.messages).slice(-120),historical=state?.historical||false,more=state?.more??true;
  useEffect(()=>{const onScroll=()=>setFollowLatest(!historical&&area.scrollHeight-area.scrollTop-area.clientHeight<70);area.addEventListener('scroll',onScroll,{passive:true});return()=>area.removeEventListener('scroll',onScroll)},[area,historical]);
  useEffect(()=>()=>{if(highlightTimer.current)clearTimeout(highlightTimer.current);highlighted.current?.classList.remove('room-highlight')},[]);
  useLayoutEffect(()=>{if(focusId.current){const target=[...area.querySelectorAll<HTMLElement>('[data-message-id]')].find(node=>node.dataset.requirementId===focusId.current);if(target){target.scrollIntoView({block:'center'});if(highlightTimer.current)clearTimeout(highlightTimer.current);highlighted.current?.classList.remove('room-highlight');highlighted.current=target;target.classList.add('room-highlight');highlightTimer.current=setTimeout(()=>{target.classList.remove('room-highlight');if(highlighted.current===target)highlighted.current=null;highlightTimer.current=null},1500);focusId.current=null;focusDone.current?.(true);focusDone.current=null;return}}if(scrollTarget.current==='top')area.scrollTop=0;else if(scrollTarget.current==='bottom'||(!historical&&followLatest))area.scrollTop=area.scrollHeight;scrollTarget.current=null},[area,messages,historical,followLatest,focusRevision]);
  const load=async(query:string,target:'top'|'bottom')=>{const sequence=++requestSequence.current;try{const next=await actions.loadWindow(query);if(sequence!==requestSequence.current||activeGroup.current!==groupId)return false;if(!next.length){actions.report('没有更多消息');return false}scrollTarget.current=target;setWindowState({groupId,messages:next,historical:true,more:next.length===120});setFollowLatest(false);return true}catch(value){actions.report(value instanceof Error?value.message:String(value));return false}};
  const returnToLatest=()=>{requestSequence.current++;scrollTarget.current='bottom';setWindowState(null);setFollowLatest(true)};
  const focusVisible=(id:string)=>{actions.select(id);focusId.current=id;scrollTarget.current=null;setFocusRevision(value=>value+1)};
  useImperativeHandle(ref,()=>({
    async focus(id){actions.select(id);if(messages.some(message=>message.requirementId===id)){focusVisible(id);return true}focusId.current=id;const promise=new Promise<boolean>(resolve=>{focusDone.current=resolve});if(!await load(`question=${encodeURIComponent(id)}`,'top')){focusId.current=null;focusDone.current?.(false);focusDone.current=null;return false}return promise},
    clear(){requestSequence.current++;focusId.current=null;focusDone.current?.(false);focusDone.current=null;setWindowState(null);setFollowLatest(true)},
    returnToLatest,
  }),[messages,groupId]);
  const tasks=new Map(model.requirements.flatMap(item=>item.tasks||[]).map(item=>[item.id,item])),requirements=new Map(model.requirements.map(item=>[item.id,item]));
  // A task can emit many progress messages. Its running state belongs only to
  // the newest message, not every historical update associated with that task.
  const latestTaskMessages=new Map<string,string>();
  for(const message of model.messages)if(message.reference?.taskId)latestTaskMessages.set(message.reference.taskId,message.id);
  return <>
    {more&&messages.length===120&&<button className="room-history" onClick={()=>void load(`before=${encodeURIComponent(messages[0]?.id||'')}`,'bottom')}>加载更早消息</button>}
    {!messages.length&&<p className="group-empty">向群组提出问题，成员会在这里回复。</p>}
    {messages.map(message=>{const task=tasks.get(message.reference?.taskId||''),requirement=requirements.get(message.requirementId||''),member=message.kind==='member'?model.group.members.find(item=>item.id===(message.reference?.memberId||task?.memberId))||model.group.members.find(item=>item.name===message.author):undefined,cancelable=message.kind==='user'&&!message.reference?.type&&requirement&&!['completed','accepted','cancelled'].includes(requirement.status);return <article key={message.id} data-message-id={message.id} data-requirement-id={message.requirementId||''} data-avatar={Array.from(message.author||'成员')[0]?.toUpperCase()||'成'} className={`group-message ${message.kind}`}>
      {['member','coordinator'].includes(message.kind)&&<Avatar value={message.kind==='coordinator'?'preset:coordinator':member?.avatar} name={message.author}/>}<div><strong>{message.author}</strong><time>{new Date(message.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>
      {message.kind!=='user'&&requirement&&<button className="reference-link" onClick={()=>focusVisible(requirement.id)}>回复：{requirement.content.slice(0,60)}</button>}
      <GroupImageLoader.Provider value={actions.loadImage}>{message.reference?.type==='progress'?<ProgressContent message={message} running={!historical&&task?.status==='running'&&requirement?.status==='running'&&latestTaskMessages.get(task.id)===message.id}/>:<LazyContent message={message}/>}</GroupImageLoader.Provider>
      {task&&requirement?.collaborationMode&&requirement.collaborationMode!=='direct'&&<small>第 {task.round||1}/{requirement.maxRounds||3} 轮 · {requirement.collaborationMode==='discussion'?'讨论':'交接'}</small>}
      {message.reference?.type==='decision-request'&&task?.decision&&message.requirementId&&<DecisionRequest task={task} requirementId={message.requirementId} memberName={message.author} actions={actions}/>}
      {(message.reference?.threadId||(message.kind==='member'&&message.reference?.taskId))&&<div className="group-message-actions">{message.reference?.threadId&&<button type="button" className="reference-link" onClick={()=>actions.openThread(message.reference!.threadId)}>打开会话 ↗</button>}{message.kind==='member'&&message.reference?.taskId&&<button type="button" className="reference-link" onClick={()=>actions.reply({taskId:message.reference!.taskId,name:message.author})}>回复 / 追问</button>}</div>}
      {cancelable&&<button className="cancel-requirement" disabled={cancelling===requirement.id} onClick={async()=>{setCancelling(requirement.id);try{await actions.cancel(requirement)}finally{setCancelling(null)}}}>{cancelling===requirement.id?'正在取消…':requirement.collaborationMode&&requirement.collaborationMode!=='direct'?'停止协作':'取消发送'}</button>}
    </article>})}
    {historical&&<button className="room-history" onClick={()=>void load(`after=${encodeURIComponent(messages.at(-1)?.id||'')}`,'top')}>加载后续消息</button>}
    {model.active.map(requirement=>{const decision=requirement.tasks?.find(task=>task.status==='awaiting_input'&&task.decision?.status==='pending')?.decision;return <div className={`room-active ${decision?'awaiting-decision':''}`} data-requirement-id={requirement.id} key={`active:${requirement.id}`}><span>{decision?`${decision.title} — 等待你的决定`:`${requirement.content.slice(0,42)} — 正在处理`}</span>{requirement.collaborationMode&&requirement.collaborationMode!=='direct'&&<button disabled={cancelling===requirement.id} onClick={async()=>{setCancelling(requirement.id);try{await actions.cancel(requirement)}finally{setCancelling(null)}}}>停止协作</button>}</div>})}
    {!followLatest&&<button className="room-latest" onClick={returnToLatest}>↓ 回到最新</button>}
  </>;
});

export function installGroupTimeline(){const area=document.getElementById('group-timeline');if(!area)return;const root:Root=createRoot(area),handle={current:null as RoomHandle|null},render=(model:Model,actions:Actions)=>root.render(<Timeline ref={value=>{handle.current=value}} model={model} actions={actions} area={area}/>);window.omegaReactGroup={render,focus:async id=>handle.current?.focus(id)??false,clear:()=>handle.current?.clear(),returnToLatest:()=>handle.current?.returnToLatest()};window.dispatchEvent(new Event('omega:react-group-ready'))}
