import {createRoot} from 'react-dom/client';
import {CommandPalette} from './CommandPalette.js';
import {ControlCenter} from './ControlCenter.js';
import {installChatTimeline} from './ChatTimeline.js';
import {installGroupTimeline} from './GroupTimeline.js';
import {installWorkspaceSidebar} from './WorkspaceSidebar.js';
import {installGroupPanels} from './GroupPanels.js';
import {installFormLayer} from './FormLayer.js';
import {installApprovalPanel} from './ApprovalPanel.js';
import {installComposer} from './Composer.js';
import {installGroupComposer} from './GroupComposer.js';
import {installAppState} from './AppState.js';
import {installConversationHeader} from './ConversationHeader.js';
import {installNotice} from './Notice.js';
import {installSessionRuntime} from './SessionRuntime.js';
import {installTypeToCompose} from './type-to-compose.js';
import {installRegionNavigation} from './region-navigation.js';
import {installFeishuNotifyDialog} from './FeishuNotifyDialog.js';

document.body.classList.add('omega-product');
installAppState();
installSessionRuntime();
installConversationHeader();
installNotice();
installChatTimeline();
installWorkspaceSidebar();
installGroupPanels();
installGroupTimeline();
installFormLayer();
installApprovalPanel();
installComposer();
installGroupComposer();
installFeishuNotifyDialog();
installTypeToCompose();
installRegionNavigation();
const host=document.createElement('div');host.id='omega-product-layer';document.body.append(host);createRoot(host).render(<><CommandPalette/><ControlCenter/></>);
await import('./AppController.js');
