import {MAX_MESSAGE_TEXT_FILES} from '../../src/shared/attachment-limits.js';
import {mentionAvatar} from './mention-avatar.js';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import type {PastedTextRef,PastedTextTransport} from './pasted-content.js';

import {readTextFile,validateAttachmentFile,isDocument} from './text-files.js';

const LONG_PASTE_CHARS=1000;
type StoredPaste=PastedTextRef&{key:string};
export interface MemberMention{id:string;name:string;role?:string;avatar?:string;start:number;end:number}
export interface RichPastePayload{mentions?:MemberMention[];imageIds?:string[];text:string;pasteIds:string[];collaborationMode?:'direct'|'handoff'|'discussion';maxRounds?:number;maxMinutes?:number;maxTokens?:number}
export interface RichPasteDraft{mentions?:MemberMention[];text:string;pastedTexts?:PastedTextRef[]}
interface InlineImage{key:string;id?:string;name:string;status:string;url:string;ready:boolean}
export interface RichPasteEditorHandle{insertMention(count:number,member:Omit<MemberMention,'start'|'end'>):void;replaceBeforeCaret(count:number,value:string):void;insertFiles(files:File[]):void;getDraft():RichPasteDraft;rememberDraft(value:RichPasteDraft):void;saveSelection():void;insertImages(keys:string[]):void;focus():void;clear():void;setDraft(value:RichPasteDraft):void;payload():RichPastePayload;insertText(value:string):void;textBeforeCaret():string}
interface Props{mentionMembers?:Array<Omit<MemberMention,'start'|'end'>>;onShortcut?(event:React.KeyboardEvent<HTMLDivElement>):boolean;scope?:string;images?:InlineImage[];onRemoveImage?(key:string):void;className?:string;id:string;label:string;placeholder:string;disabled?:boolean;transport:PastedTextTransport;onChange?(state:{text:string;hasContent:boolean;uploading:boolean;textBeforeCaret:string}):void;onEnter?():void;onFiles?(files:File[]):void;report(message:string):void}

const tokenLabel=(chars:number)=>`Pasted Content ${chars} chars`;
const draftKey=()=>{if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(12));return[...bytes].map(value=>value.toString(16).padStart(2,'0')).join('');};

function selectionRange(editor:HTMLElement){const selection=window.getSelection();if(!selection?.rangeCount)return null;const range=selection.getRangeAt(0);return editor.contains(range.commonAncestorContainer)?range:null;}
function insertNode(editor:HTMLElement,node:Node){const selected=selectionRange(editor),anchor=node.nodeType===Node.DOCUMENT_FRAGMENT_NODE?node.lastChild:node;if(selected){selected.deleteContents();selected.insertNode(node);}else editor.append(node);if(anchor?.parentNode){const caret=document.createRange();caret.setStartAfter(anchor);caret.collapse(true);const selection=window.getSelection();selection?.removeAllRanges();selection?.addRange(caret);}editor.focus();}
function insertPlainText(editor:HTMLElement,text:string){const fragment=document.createDocumentFragment(),parts=text.split('\n');parts.forEach((part,index)=>{if(index)fragment.append(document.createElement('br'));if(part)fragment.append(document.createTextNode(part));});insertNode(editor,fragment);}
function appendPlainText(editor:HTMLElement,text:string){const fragment=document.createDocumentFragment(),parts=text.split('\n');parts.forEach((part,index)=>{if(index)fragment.append(document.createElement('br'));if(part)fragment.append(document.createTextNode(part));});editor.append(fragment);}
function normalizeText(value:string){return value.replace(/[\u00a0\u200b]/g,value=>value==='\u00a0'?' ':'').replace(/\n{3,}/g,'\n\n');}
function recallWithoutImages(draft:RichPasteDraft):RichPasteDraft{
  const replace=(text:string)=>text.replace(/\[OmegaImage:[a-zA-Z0-9-]+\]/g,'[图片需重新添加]');
  return {...draft,text:replace(draft.text),mentions:draft.mentions?.map(member=>({...member,start:replace(draft.text.slice(0,member.start)).length,end:replace(draft.text.slice(0,member.end)).length}))};
}

export const RichPasteEditor=forwardRef<RichPasteEditorHandle,Props>(function RichPasteEditor({mentionMembers=[],onShortcut,scope='',className,id,label,placeholder,disabled,transport,onChange,onEnter,onFiles,images=[],onRemoveImage,report},ref){
  const documentQueue=useRef<Promise<unknown>>(Promise.resolve());
  const selectedMention=useRef<HTMLElement|null>(null);
  const recall=useRef(new Map<string,RichPasteDraft>()),self=useRef<RichPasteEditorHandle|null>(null);
  const savedRange=useRef<Range|null>(null),imageRefs=useRef(images);imageRefs.current=images;
  const [imagePreview,setImagePreview]=useState<InlineImage|null>(null);
  const editor=useRef<HTMLDivElement>(null),pastes=useRef(new Map<string,StoredPaste>()),uploading=useRef(new Set<string>());
  const [preview,setPreview]=useState<{title:string;text:string;loading:boolean}|null>(null),[,rerender]=useState(0);
  const serializeNode=(node:Node):string=>{
    if(node.nodeType===Node.TEXT_NODE)return node.textContent||'';
    if(!(node instanceof HTMLElement))return'';
    if(node.dataset.mentionId)return '@'+node.dataset.mentionName;
    if(node.dataset.imageKey){const image=imageRefs.current.find(item=>item.key===node.dataset.imageKey);return image?.id?`[OmegaImage:${image.id}]`:'';}
    if(node.dataset.pasteKey){const item=pastes.current.get(node.dataset.pasteKey);return item?`[${tokenLabel(item.chars)} id=${item.id}]`:'';}
    if(node.tagName==='BR')return'\n';
    const text=[...node.childNodes].map(serializeNode).join('');return ['DIV','P'].includes(node.tagName)?text+'\n':text;
  };
  // Serialize only the prefix: unfinished block ancestors must not add a trailing newline.
  const prefixText=(node:Node,end:Node,offset:number):string=>{
    if(node===end)return node.nodeType===Node.TEXT_NODE?(node.textContent||'').slice(0,offset):[...node.childNodes].slice(0,offset).map(serializeNode).join('');
    let text='';for(const child of node.childNodes){if(child===end||child.contains(end))return text+prefixText(child,end,offset);text+=serializeNode(child);}return text;
  };
  const payload=():RichPastePayload=>{const root=editor.current;if(!root)return{text:'',pasteIds:[]};const ids:string[]=[];root.querySelectorAll<HTMLElement>('[data-paste-key]').forEach(node=>{const item=pastes.current.get(node.dataset.pasteKey||'');if(item&&!ids.includes(item.id))ids.push(item.id);});const raw=normalizeText([...root.childNodes].map(serializeNode).join('')),leading=raw.length-raw.trimStart().length;
    const mentions=[...root.querySelectorAll<HTMLElement>('[data-mention-id]')].map(node=>{const range=document.createRange();range.selectNodeContents(root);range.setEndBefore(node);const start=normalizeText(prefixText(root,range.endContainer,range.endOffset)).length-leading;return{id:node.dataset.mentionId!,name:node.dataset.mentionName!,role:node.dataset.mentionRole,start,end:start+1+node.dataset.mentionName!.length};});
    return{text:raw.trim(),pasteIds:ids,mentions};};
  const beforeCaret=()=>{const root=editor.current,range=root&&selectionRange(root);if(!root||!range)return'';const copy=range.cloneRange();copy.selectNodeContents(root);copy.setEnd(range.endContainer,range.endOffset);return normalizeText(prefixText(root,copy.endContainer,copy.endOffset));};
  const changed=()=>{const root=editor.current;const selection=root&&selectionRange(root);if(selection)savedRange.current=selection.cloneRange();if(root){const live=new Set([...root.querySelectorAll<HTMLElement>('[data-paste-key]')].map(node=>node.dataset.pasteKey||''));for(const key of pastes.current.keys())if(!live.has(key))pastes.current.delete(key);for(const key of uploading.current)if(!live.has(key))uploading.current.delete(key);}if(root){const keys=new Set([...root.querySelectorAll<HTMLElement>('[data-image-key]')].map(node=>node.dataset.imageKey));for(const image of imageRefs.current)if(!keys.has(image.key))onRemoveImage?.(image.key);}const value=payload();onChange?.({text:value.text,hasContent:!!value.text,uploading:uploading.current.size>0||imageRefs.current.some(item=>!item.ready),textBeforeCaret:beforeCaret()});};
  const removeImage=(node:HTMLElement)=>{const key=node.dataset.imageKey||'',next=node.nextSibling;if(next?.nodeType===Node.TEXT_NODE)next.textContent=(next.textContent||'').replace(/^\u200b/,'');node.remove();onRemoveImage?.(key);changed();};
  const insertImages=(keys:string[])=>{const root=editor.current;if(!root)return;const range=selectionRange(root)||savedRange.current;if(range&&root.contains(range.commonAncestorContainer)){const selected=window.getSelection();selected?.removeAllRanges();selected?.addRange(range);}for(const key of keys){const token=document.createElement('span');token.dataset.imageKey=key;token.contentEditable='false';token.className='inline-image-token';token.tabIndex=0;token.setAttribute('role','button');token.setAttribute('aria-label','图片，点击预览');const img=document.createElement('img');img.alt='';img.hidden=true;const label=document.createElement('span');label.className='inline-image-label';label.textContent='图片 · 上传中…';const close=document.createElement('span');close.dataset.action='remove';close.setAttribute('role','button');close.setAttribute('aria-label','移除图片');close.textContent='×';token.append(img,label,close);insertNode(root,token);insertNode(root,document.createTextNode('\u200b'));}changed();};
  useEffect(()=>{const root=editor.current;if(!root)return;for(const node of root.querySelectorAll<HTMLElement>('[data-image-key]')){const item=images.find(image=>image.key===node.dataset.imageKey);if(!item){node.remove();continue;}const img=node.querySelector('img')!;if(item.url){if(img.getAttribute('src')!==item.url)img.src=item.url;img.hidden=false;}node.querySelector('.inline-image-label')!.textContent=item.ready?'图片':item.status;node.title=item.name+' · '+item.status;}changed();},[images]);
  const makeToken=(key:string,chars:number,status='')=>{const token=document.createElement('span');token.className='pasted-content-token';token.dataset.pasteKey=key;token.contentEditable='false';token.tabIndex=0;token.setAttribute('role','button');token.setAttribute('aria-label',`${tokenLabel(chars)}，点击预览`);const mark=document.createElement('span');mark.className='pasted-content-mark';mark.textContent='›';const name=document.createElement('span');name.className='pasted-content-name';name.textContent=tokenLabel(chars);const state=document.createElement('span');state.className='pasted-content-status';state.textContent=status;const close=document.createElement('span');close.className='pasted-content-remove';close.dataset.action='remove';close.setAttribute('role','button');close.setAttribute('aria-label','删除整段粘贴内容');close.textContent='×';token.append(mark,name,state,close);return token;};
  const addLongPaste=async(source:string|File)=>{
    const root=editor.current;if(!root||disabled)return;
    if(pastes.current.size+uploading.current.size>=MAX_MESSAGE_TEXT_FILES){report('每条消息最多包含 20 个文本附件（含长粘贴）');return;}
    if(typeof source!=='string'){try{validateAttachmentFile(source)}catch(error){report(error instanceof Error?error.message:String(error));return;}}
    const range=selectionRange(root)||savedRange.current;if(range&&root.contains(range.commonAncestorContainer)){const selected=window.getSelection();selected?.removeAllRanges();selected?.addRange(range);}
    const key=draftKey(),name=typeof source==='string'?undefined:source.name,token=makeToken(key,typeof source==='string'?[...source].length:0,'保存中…');
    if(name){token.querySelector('.pasted-content-name')!.textContent=name;token.setAttribute('aria-label',name+'，点击预览');}
    uploading.current.add(key);insertNode(root,token);insertNode(root,document.createTextNode('\u200b'));changed();
    try{
      const document=typeof source!=='string'&&isDocument(source);
      const text=typeof source==='string'?source:document?'':await readTextFile(source);
      if(!token.isConnected||!uploading.current.has(key))return;
      if(document&&!transport.uploadDocument)throw Error('当前连接不支持文档上传，请更新客户端后重试');
      const uploadDocument=()=>{if(!token.isConnected||!uploading.current.has(key))return null;return transport.uploadDocument!(source as File);};
      const pending=document?documentQueue.current.then(uploadDocument):transport.upload(text);
      if(document)documentQueue.current=pending.catch(()=>{});
      const item=await pending;if(!item)return;
      if(!token.isConnected||!uploading.current.has(key))return;
      pastes.current.set(key,{...item,key,name});
      token.querySelector('.pasted-content-name')!.textContent=name||tokenLabel(item.chars);
      token.title=name?name+' · '+item.bytes+' bytes':tokenLabel(item.chars);
      token.querySelector('.pasted-content-status')!.textContent='';
    }catch(error){
      if(token.isConnected){if(typeof source==='string')token.replaceWith(document.createTextNode(source));else token.remove();report(error instanceof Error?error.message:String(error));}
    }finally{uploading.current.delete(key);rerender(value=>value+1);changed();}
  };
  const openPreview=async(key:string)=>{const item=pastes.current.get(key);if(!item)return;setPreview({title:item.name||tokenLabel(item.chars),text:'',loading:true});try{setPreview({title:item.name||tokenLabel(item.chars),text:await transport.read(item.id),loading:false});}catch(error){setPreview(null);report(error instanceof Error?error.message:String(error));}};
  const replaceBeforeCaret=(count:number,value:string|HTMLElement)=>{const root=editor.current;if(!root||disabled)return;const range=selectionRange(root)||savedRange.current;if(!range||!range.collapsed||!root.contains(range.commonAncestorContainer))return;const prefix=range.cloneRange();prefix.selectNodeContents(root);prefix.setEnd(range.endContainer,range.endOffset);let offset=prefix.toString().length-count;if(offset<0)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode())){const length=node.textContent?.length||0;if(offset<=length){if(node.parentElement?.closest('[contenteditable="false"]'))return;range.setStart(node,offset);const selection=window.getSelection();selection?.removeAllRanges();selection?.addRange(range);if(typeof value==='string')insertPlainText(root,value);else{insertNode(root,value);insertPlainText(root,' ');}changed();return;}offset-=length;}};
  const clearMentionSelection=()=>{selectedMention.current?.classList.remove('is-selected');selectedMention.current=null;};
  const selectMention=(node:HTMLElement)=>{clearMentionSelection();selectedMention.current=node;node.classList.add('is-selected');const range=document.createRange();range.selectNode(node);const selection=getSelection();selection?.removeAllRanges();selection?.addRange(range);editor.current?.focus();};
  const makeMention=(member:Omit<MemberMention,'start'|'end'>)=>{const token=document.createElement('span');token.className='mention-token';token.contentEditable='false';token.dataset.mentionId=member.id;token.dataset.mentionName=member.name;token.dataset.mentionRole=member.role||'';token.title=member.name+(member.role?' · '+member.role:'');token.setAttribute('aria-label','指定成员 '+member.name);const avatar=document.createElement('span');avatar.className='mention-avatar';const visual=mentionAvatar(mentionMembers.find(item=>item.id===member.id)||member);if(visual.image){const img=document.createElement('img');img.src=visual.image;img.alt='';avatar.append(img);}else avatar.textContent=visual.label;const name=document.createElement('span');name.className='mention-token-name';name.textContent='@'+member.name;const close=document.createElement('span');close.className='mention-remove';close.dataset.action='remove-mention';close.setAttribute('role','button');close.setAttribute('aria-label','移除成员 '+member.name);close.textContent='×';token.append(avatar,name,close);return token;};
  const appendDraftPart=(root:HTMLElement,text:string,start:number,mentions:MemberMention[]=[])=>{let at=0;for(const member of mentions.filter(m=>m.start>=start&&m.end<=start+text.length).sort((a,b)=>a.start-b.start)){const offset=member.start-start;if(offset<at||text.slice(offset,member.end-start)!=='@'+member.name)continue;appendPlainText(root,text.slice(at,offset));root.append(makeMention(member));at=member.end-start;}appendPlainText(root,text.slice(at));};
  const mentionKey=(event:React.KeyboardEvent<HTMLDivElement>)=>{if(event.nativeEvent.isComposing)return false;const deleting=event.key==='Backspace'||event.key==='Delete';if(!deleting){clearMentionSelection();return false;}const root=editor.current;if(!root)return false;if(selectedMention.current?.isConnected){event.preventDefault();const node=selectedMention.current;clearMentionSelection();const range=document.createRange();range.setStartBefore(node);range.collapse(true);node.remove();const selection=getSelection();selection?.removeAllRanges();selection?.addRange(range);changed();return true;}const range=selectionRange(root);if(!range?.collapsed)return false;const back=event.key==='Backspace',node=range.startContainer,offset=range.startOffset;let candidate:Node|null=null;if(node.nodeType===Node.TEXT_NODE){const rest=back?(node.textContent||'').slice(0,offset):(node.textContent||'').slice(offset);if(!rest.replace(/\u200b/g,''))candidate=back?node.previousSibling:node.nextSibling;}else candidate=node.childNodes[back?offset-1:offset]||null;while(candidate?.nodeType===Node.TEXT_NODE&&!candidate.textContent)candidate=back?candidate.previousSibling:candidate.nextSibling;if(candidate instanceof HTMLElement&&candidate.dataset.mentionId){event.preventDefault();selectMention(candidate);return true;}return false;};
  const handle:RichPasteEditorHandle={insertMention:(count,member)=>replaceBeforeCaret(count,makeMention(member)),replaceBeforeCaret,insertFiles:files=>{for(const file of files)void addLongPaste(file);},getDraft:()=>({text:payload().text,mentions:payload().mentions,pastedTexts:[...pastes.current.values()]}),rememberDraft:value=>{recall.current.delete(scope);recall.current.set(scope,value);if(recall.current.size>20)recall.current.delete(recall.current.keys().next().value!);},insertImages,saveSelection:()=>{const range=editor.current&&selectionRange(editor.current);if(range)savedRange.current=range.cloneRange()},focus:()=>editor.current?.focus(),clear:()=>{if(editor.current)editor.current.innerHTML='';pastes.current.clear();uploading.current.clear();setPreview(null);changed();},setDraft:value=>{const root=editor.current;if(!root)return;root.replaceChildren();pastes.current.clear();uploading.current.clear();setPreview(null);const refs=[...(value.pastedTexts||[])],used=new Set<string>(),pattern=/\[Pasted Content (\d+) chars(?: id=([a-zA-Z0-9-]+))?\]/g;let from=0,match:RegExpExecArray|null;while((match=pattern.exec(value.text))){appendDraftPart(root,value.text.slice(from,match.index),from,value.mentions);const chars=Number(match[1]),item=refs.find(ref=>(match![2]?ref.id===match![2]:ref.chars===chars)&&!used.has(ref.id));if(item){const key=draftKey();used.add(item.id);pastes.current.set(key,{...item,key});const token=makeToken(key,item.chars);if(item.name){token.querySelector('.pasted-content-name')!.textContent=item.name;token.setAttribute('aria-label',item.name+'，点击预览');}root.append(token);}else appendPlainText(root,match[0]);from=match.index+match[0].length;}appendDraftPart(root,value.text.slice(from),from,value.mentions);for(const item of refs)if(!used.has(item.id)){if(root.childNodes.length)root.append(document.createTextNode(' '));const key=draftKey();pastes.current.set(key,{...item,key});const token=makeToken(key,item.chars);if(item.name){token.querySelector('.pasted-content-name')!.textContent=item.name;token.setAttribute('aria-label',item.name+'，点击预览');}root.append(token);}changed();requestAnimationFrame(()=>root.focus());},payload,insertText:value=>{if(editor.current){insertPlainText(editor.current,value);changed();}},textBeforeCaret:beforeCaret};self.current=handle;useImperativeHandle(ref,()=>handle);
  return <>
    {imagePreview&&<div className="pasted-preview-backdrop" onClick={()=>setImagePreview(null)}><section className="pasted-preview" role="dialog" aria-modal="true" aria-label="图片预览"><header><strong>{imagePreview.name}</strong><button type="button" onClick={()=>setImagePreview(null)}>关闭</button></header><img src={imagePreview.url} alt={imagePreview.name} style={{maxWidth:'100%',maxHeight:'75vh',objectFit:'contain'}}/></section></div>}
    <div ref={editor} id={id} className={`rich-paste-editor ${className||''}`} contentEditable={!disabled} role="textbox" aria-label={label} aria-multiline="true" data-placeholder={placeholder} suppressContentEditableWarning
      onInput={()=>{clearMentionSelection();changed()}} onKeyUp={changed} onMouseUp={()=>{clearMentionSelection();changed()}}
      onKeyDown={event=>{if(!event.nativeEvent.isComposing&&onShortcut?.(event))return;if(mentionKey(event))return;if(event.key==='ArrowUp'&&!event.nativeEvent.isComposing&&!event.altKey&&!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!editor.current?.textContent?.replace(/\u200b/g,'').trim()&&!editor.current?.querySelector('[data-image-key],[data-paste-key]')){const previous=recall.current.get(scope);if(previous){event.preventDefault();const hasImages=/\[OmegaImage:/.test(previous.text);self.current?.setDraft(recallWithoutImages(previous));if(hasImages)report('已恢复文字；图片请重新添加，以免使用过期附件');return;}}if(event.key==='Backspace'||event.key==='Delete'){const root=editor.current,range=root&&selectionRange(root);let candidate:Node|null=(event.target as HTMLElement).closest('[data-image-key]');if(!candidate&&range?.collapsed){const node=range.startContainer,offset=range.startOffset,back=event.key==='Backspace';if(node.nodeType===Node.TEXT_NODE){const rest=back?(node.textContent||'').slice(0,offset):(node.textContent||'').slice(offset);if(!rest.replace(/\u200b/g,''))candidate=back?node.previousSibling:node.nextSibling;}else candidate=node.childNodes[back?offset-1:offset]||null;}if(candidate instanceof HTMLElement&&candidate.dataset.imageKey){event.preventDefault();removeImage(candidate);return;}}if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();onEnter?.();}}}
      onPaste={event=>{event.preventDefault();const files=Array.from(event.clipboardData.items).filter(item=>item.kind==='file').map(item=>item.getAsFile()).filter((file):file is File=>!!file);if(files.length)onFiles?.(files);const text=event.clipboardData.getData('text/plain');if(!text)return;if([...text].length>=LONG_PASTE_CHARS)void addLongPaste(text);else if(editor.current){insertPlainText(editor.current,text);changed();}}}
      onClick={event=>{const target=event.target as HTMLElement,mention=target.closest<HTMLElement>('[data-mention-id]');if(mention){event.preventDefault();if(target.closest('[data-action="remove-mention"]')){clearMentionSelection();mention.remove();changed();}else selectMention(mention);return;}const image=target.closest<HTMLElement>('[data-image-key]');if(image){event.preventDefault();const key=image.dataset.imageKey||'';if(target.closest('[data-action="remove"]')){removeImage(image);}else{const item=imageRefs.current.find(item=>item.key===key);if(item?.url)setImagePreview(item);}return;}const token=target.closest<HTMLElement>('[data-paste-key]');if(!token)return;event.preventDefault();const key=token.dataset.pasteKey||'';if(target.closest('[data-action="remove"]')){uploading.current.delete(key);pastes.current.delete(key);token.remove();changed();}else void openPreview(key);}}
      onKeyDownCapture={event=>{if((event.key==='Backspace'||event.key==='Delete')&&(event.target as HTMLElement).closest?.('[data-paste-key]'))event.preventDefault();}}/>
    {preview&&<div className="pasted-preview-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setPreview(null)}}><section className="pasted-preview" role="dialog" aria-modal="true" aria-label={preview.title}><header><strong>{preview.title}</strong><button type="button" onClick={()=>setPreview(null)} aria-label="关闭预览">×</button></header>{preview.loading?<p>正在读取…</p>:<pre>{preview.text}</pre>}</section></div>}
  </>;
});
