import {useEffect,useRef,useState} from 'react';
import {useAppState} from './AppState.js';

type Row=Record<string,any>;
type Entry={id:string;status:string;content:Row|null;source:Row;sourceText?:string;revision:number;error?:string;updatedAt:string};
const api=(data:Row)=>window.omegaProductApi!<any>('skills',data);
const get=(query='')=>window.omegaProductApi!<any>('skills'+query);
const message=(error:unknown)=>error instanceof Error?error.message:String(error);
const names:Record<string,string>={generating:'提炼中',draft:'待确认草稿',active:'已启用',disabled:'已停用',failed:'提炼失败'};
const fields:[string,string][]=[['inputs','所需输入'],['steps','操作步骤'],['verification','验证方式'],['limits','限制与未验证部分']];

export function SkillEntry(){const app=useAppState(),[open,setOpen]=useState(false);useEffect(()=>{const show=()=>setOpen(true);window.addEventListener('omega:open-skills',show);return()=>window.removeEventListener('omega:open-skills',show)},[]);return <><button type="button" className="work-entry" disabled={!app.authenticated} onClick={()=>setOpen(true)}>Skills</button>{open&&<SkillDialog close={()=>setOpen(false)}/>}</>}

function SkillDialog({close}:{close():void}){
  const app=useAppState(),dialog=useRef<HTMLDialogElement>(null),[items,setItems]=useState<Entry[]>([]),[hasMoreSkills,setHasMoreSkills]=useState(false),[selected,setSelected]=useState<Entry|null>(null),[sourceOptions,setSourceOptions]=useState<Row[]>([]),[cursor,setCursor]=useState<string|null>(null),[start,setStart]=useState(''),[end,setEnd]=useState(''),[preview,setPreview]=useState<Row|null>(null),[draft,setDraft]=useState<Row|null>(null),[history,setHistory]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const scope=app.mode==='groups'?'group':'thread',targetId=scope==='group'?app.groupId:app.threadId;
  useEffect(()=>{dialog.current?.showModal();const previous=document.activeElement as HTMLElement;return()=>{dialog.current?.close();if(previous?.isConnected)previous.focus()}},[]);
  useEffect(()=>{let live=true;void get().then(result=>{if(live){setItems(result.items||[]);setHasMoreSkills((result.items||[]).length===30)}}).catch(cause=>{if(live)setError(message(cause))});return()=>{live=false}},[]);
  useEffect(()=>{setSourceOptions([]);setCursor(null);setPreview(null);setStart('');setEnd('');if(!targetId)return;let live=true;void api({action:'sourceOptions',scope,targetId}).then(result=>{if(!live)return;setSourceOptions(result.items||[]);setCursor(result.nextCursor||null);const initial=scope==='thread'&&app.chatHeader?.selectedTurn&&result.items?.some((item:Row)=>item.id===app.chatHeader?.selectedTurn)?app.chatHeader.selectedTurn:result.items?.[0]?.id||'';setStart(initial);setEnd(initial)}).catch(cause=>{if(live)setError(message(cause))});return()=>{live=false}},[scope,targetId]);
  useEffect(()=>{if(selected?.status!=='generating')return;let live=true;const timer=setInterval(()=>{void get('?id='+encodeURIComponent(selected.id)).then(result=>{if(!live)return;setSelected(result.entry);if(result.entry.status!=='generating'){setDraft(result.entry.content?structuredClone(result.entry.content):null);void get().then(value=>{if(live)setItems(value.items||[])});void get('?id='+encodeURIComponent(selected.id)+'&history=1').then(value=>{if(live)setHistory(value.items||[])})}}).catch(cause=>{if(live)setError(message(cause))})},2000);return()=>{live=false;clearInterval(timer)}},[selected?.id,selected?.status]);
  const run=async(work:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await work()}catch(cause){setError(message(cause))}finally{setBusy(false)}};
  const ids=()=>{if(scope==='group')return[start];const older=sourceOptions.findIndex(item=>item.id===start),newer=sourceOptions.findIndex(item=>item.id===end);if(older<newer||newer<0||older-newer>=8)throw Error('请选择连续的 1–8 轮：起点应早于终点');return sourceOptions.slice(newer,older+1).reverse().map(item=>item.id)};
  const source=async()=>{if(!targetId)throw Error('请先打开目标会话或群组');return{scope,targetId,ids:ids()}};
  const load=async(entry:Entry)=>{setSelected(entry);setPreview(null);setDraft(entry.content?structuredClone(entry.content):null);setHistory([]);if(entry.status!=='generating'){const [detail,revisions]=await Promise.all([get('?id='+encodeURIComponent(entry.id)),get('?id='+encodeURIComponent(entry.id)+'&history=1')]);setSelected(detail.entry);setHistory(revisions.items||[])}};
  const setField=(name:string,value:unknown)=>setDraft(current=>({...current,[name]:value}));
  const choose=()=>{if(!selected||!app.threadId||app.mode!=='chats')return;window.omegaAppState?.patch({selectedSkill:{id:selected.id,name:selected.content?.name||'Skill',threadId:app.threadId}});close()};
  return <dialog ref={dialog} className="work-dialog skill-dialog" aria-label="Omega Skills" onCancel={event=>{event.preventDefault();close()}}>
    <header><h2>Omega Skills</h2><button type="button" aria-label="关闭 Skills" onClick={close}>×</button></header>
    <div className="work-body skill-body">
      <p className="skill-intro">从完整任务过程提炼，核对后才启用；使用时需要显式选中，不会自动影响其他会话。</p>
      <section className="work-card skill-source">
        <h3>提炼来源</h3>
        <p>{scope==='thread'?'当前会话：选择连续问答轮次':'当前群组：选择一个已归档的问题'}</p>
        {targetId?<><div className="skill-source-controls"><label>起点<select aria-label="提炼起点" value={start} onChange={event=>{setStart(event.target.value);if(scope==='group')setEnd(event.target.value);setPreview(null)}}>{sourceOptions.map(item=><option key={item.id} value={item.id}>{item.label||item.id}</option>)}</select></label>{scope==='thread'&&<label>终点<select aria-label="提炼终点" value={end} onChange={event=>{setEnd(event.target.value);setPreview(null)}}>{sourceOptions.map(item=><option key={item.id} value={item.id}>{item.label||item.id}</option>)}</select></label>}</div><div className="work-actions">{cursor&&<button type="button" disabled={busy} onClick={()=>void run(async()=>{const result=await api({action:'sourceOptions',scope,targetId,...(scope==='thread'?{cursor}:{before:cursor})});setSourceOptions(value=>[...value,...(result.items||[])]);setCursor(result.nextCursor||null)})}>加载更早范围</button>}<button type="button" disabled={busy||!start} onClick={()=>void run(async()=>setPreview(await api({action:'preview',...(await source())})))}>预览实际来源</button></div>{preview&&<div className="skill-preview"><p>共 {preview.source.ids.length} 轮／问题，{preview.source.chars} 字。{preview.source.omissions?.length?'有未纳入内容，需人工核对。':'未发现被跳过的文字条目。'}</p>{preview.source.omissions?.map((item:string)=><small key={item} className="skill-warning">{item}</small>)}<details><summary>查看提炼所用原文</summary><pre>{preview.text}</pre></details><button type="button" disabled={busy} onClick={()=>void run(async()=>{const result=await api({action:'draft',...(await source())});setSelected(result.entry);setDraft(null);setItems(value=>[result.entry,...value]);setPreview(null)})}>让会话整理草稿</button></div>}</>:<p>先打开会话或群组，再选择来源。</p>}
      </section>
      <section className="skill-library">
        <h3>Skill 库</h3>
        {items.length?<div className="skill-list">{items.map(item=><button type="button" className={selected?.id===item.id?'selected':''} aria-pressed={selected?.id===item.id} key={item.id} onClick={()=>void run(()=>load(item))}><strong>{item.content?.name||item.source?.labels?.join(' / ')||'提炼任务'}</strong><small>{names[item.status]||item.status} · v{item.revision}</small></button>)}</div>:<p className="skill-empty">还没有 Skill。请从上方选择一段完整任务过程并预览来源。</p>}
        {hasMoreSkills&&<button type="button" disabled={busy} onClick={()=>void run(async()=>{const result=await get('?before='+encodeURIComponent(items.at(-1)!.id));setItems(value=>[...value,...(result.items||[])]);setHasMoreSkills((result.items||[]).length===30)})}>加载更早 Skill</button>}
      </section>
      {selected&&<section className="work-card skill-editor"><h3>{selected.content?.name||'Skill 草稿'}</h3><small>{names[selected.status]||selected.status} · 来源：{selected.source?.labels?.join(' → ')}</small>{selected.status==='generating'?<p>正在按所选任务过程整理。可以关闭窗口，稍后回来查看。</p>:selected.status==='failed'?<p role="alert">{selected.error||'提炼失败，请检查来源后重新生成'}</p>:draft&&<><label>名称<input maxLength={100} value={draft.name||''} onChange={event=>setField('name',event.target.value)}/></label><label>用途简介<input maxLength={300} value={draft.description||''} onChange={event=>setField('description',event.target.value)}/></label><label>何时使用<textarea rows={3} maxLength={1000} value={draft.whenToUse||''} onChange={event=>setField('whenToUse',event.target.value)}/></label>{fields.map(([key,label])=><label key={key}>{label}（每行一项）<textarea rows={key==='steps'?6:3} value={(draft[key]||[]).join('\n')} onChange={event=>setField(key,event.target.value.split('\n').map((line:string)=>line.trim()).filter(Boolean))}/></label>)}<div className="skill-actions"><button type="button" disabled={busy} onClick={()=>void run(async()=>{const result=await api({action:'save',id:selected.id,revision:selected.revision,content:draft,status:'active'});setSelected(result.entry);setDraft(result.entry.content);setItems(value=>value.map(item=>item.id===result.entry.id?result.entry:item))})}>确认并启用</button><button type="button" disabled={busy} onClick={()=>void run(async()=>{const result=await api({action:'save',id:selected.id,revision:selected.revision,content:draft,status:'draft'});setSelected(result.entry);setItems(value=>value.map(item=>item.id===result.entry.id?result.entry:item))})}>保存草稿</button>{selected.status==='active'&&<button type="button" disabled={busy} onClick={()=>void run(async()=>{const result=await api({action:'save',id:selected.id,revision:selected.revision,content:draft,status:'disabled'});setSelected(result.entry);setItems(value=>value.map(item=>item.id===result.entry.id?result.entry:item))})}>停用</button>}{selected.status==='active'&&<button type="button" disabled={app.mode!=='chats'||!app.threadId} onClick={choose}>用于当前会话下一条消息</button>}</div><details><summary>来源、遗漏与版本</summary>{selected.source?.omissions?.map((item:string)=><p className="skill-warning" key={item}>{item}</p>)}<pre>{selected.sourceText||'点击列表重新打开以读取完整来源'}</pre>{history.map(item=><details key={item.revision}><summary>v{item.revision} · {item.actor}</summary><pre>{JSON.stringify(item.snapshot,null,2)}</pre></details>)}</details></>}</section>}
      {error&&<p className="skill-error" role="alert">{error}</p>}
    </div>
  </dialog>;
}
