import {useEffect,useRef,useState} from 'react';

interface Health{status:string;version:string;startedAt:string;uptimeSeconds:number;memory:{rss:number;heapUsed:number;heapTotal:number};bridge:{ready:boolean;pid:number|null;pendingRequests:number;pendingApprovals:number};devices:number;activeTurns:number;pendingRestore:boolean;supervised:boolean}
interface Account{type:string;email?:string|null;planType?:string|null}
interface RateWindow{usedPercent:number;windowDurationMins:number|null;resetsAt:number|null}
interface Credits{hasCredits:boolean;unlimited:boolean;balance:string|null}
interface RateLimit{limitId:string|null;limitName:string|null;primary:RateWindow|null;secondary:RateWindow|null;credits:Credits|null;planType?:string|null;rateLimitReachedType?:string|null}
interface Limits{ordinaryUsageAllowed?:boolean|null;rateLimits?:RateLimit|null;rateLimitsByLimitId?:Record<string,RateLimit>|null}
interface Usage{summary?:{lifetimeTokens?:number|null;peakDailyTokens?:number|null;longestRunningTurnSec?:number|null;currentStreakDays?:number|null;longestStreakDays?:number|null};dailyUsageBuckets?:Array<{startDate:string;tokens:number}>|null}
const size=(value:number)=>(value/1024/1024).toFixed(1)+' MB';
const duration=(seconds:number)=>{const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);return hours?`${hours} 小时 ${minutes} 分钟`:`${minutes} 分钟`;};
const number=(value:number|null|undefined)=>typeof value==='number'&&Number.isFinite(value)?value.toLocaleString():'暂无';
const planName=(value:string|null|undefined)=>({free:'Free',go:'Go',plus:'Plus',pro:'Pro',prolite:'Pro Lite',team:'Team',business:'Business',enterprise:'Enterprise',edu:'Edu',edu_plus:'Edu Plus',edu_pro:'Edu Pro'}[value||'']||value||'未知套餐');
const accountName=(account:Account|null)=>!account?'未登录':account.type==='chatgpt'?`ChatGPT · ${planName(account.planType)}`:account.type==='apiKey'?'OpenAI API Key':account.type==='amazonBedrock'?'Amazon Bedrock':account.type;
const resetTime=(value:number|null|undefined)=>value?new Date(value*1000).toLocaleString():'暂无重置时间';
const rpc=<T,>(method:string,params?:Record<string,unknown>)=>{if(!window.omegaProductApi)return Promise.reject(new Error('Omega 客户端尚未连接'));return window.omegaProductApi<T>('rpc',{method,params});};

function RateLimitCard({limit}:{limit:RateLimit}){
  const windows=[['主要窗口',limit.primary],['次要窗口',limit.secondary]] as const;
  return <article className="codex-limit-card"><div><strong>{limit.limitName||limit.limitId||'Codex 额度'}</strong>{limit.planType&&<span>{planName(limit.planType)}</span>}</div>{windows.map(([label,window])=>window&&<div className="codex-limit-window" key={label}><p><span>{label}</span><b>{Math.round(window.usedPercent)}% 已用</b></p><progress max="100" value={Math.min(100,Math.max(0,window.usedPercent))}/><small>{window.windowDurationMins?`${window.windowDurationMins} 分钟窗口 · `:''}{resetTime(window.resetsAt)}</small></div>)}{limit.credits&&<small>{limit.credits.unlimited?'Credits 不限量':limit.credits.hasCredits?`剩余 Credits：${limit.credits.balance??'可用'}`:'没有可用 Credits'}</small>}{limit.rateLimitReachedType&&<em>当前限制：{limit.rateLimitReachedType}</em>}</article>;
}
function CodexUsage({account,limits,usage,error}:{account:Account|null;limits:Limits|null;usage:Usage|null;error:string}){
  const buckets=Object.values(limits?.rateLimitsByLimitId||{}).filter(Boolean);if(!buckets.length&&limits?.rateLimits)buckets.push(limits.rateLimits);
  const days=(usage?.dailyUsageBuckets||[]).slice(-14),peak=Math.max(1,...days.map(day=>Number(day.tokens)||0)),summary=usage?.summary;
  const unsupported=account?.type==='apiKey'||account?.type==='amazonBedrock';
  return <section className="codex-usage" aria-label="Codex 账户与用量"><div className="omega-center-section-title"><div><h3>Codex 账户与用量</h3><p>直接读取当前 Codex App Server 的账户额度和 Token 活动，只读展示。</p></div></div><div className="codex-account-summary"><article><strong>{accountName(account)}</strong><p>{account?.email||'当前 App Server 认证'}</p><small>{unsupported?'此认证方式不提供 ChatGPT 账户用量':limits?.ordinaryUsageAllowed===false?'普通额度当前不可用':'账户信息由 Codex 服务返回'}</small></article>{summary&&<><article><strong>{number(summary.lifetimeTokens)}</strong><p>累计 Tokens</p><small>单日峰值 {number(summary.peakDailyTokens)}</small></article><article><strong>{summary.currentStreakDays??'—'} 天</strong><p>当前连续使用</p><small>最长 {summary.longestStreakDays??'—'} 天 · 最长任务 {summary.longestRunningTurnSec?duration(summary.longestRunningTurnSec):'暂无'}</small></article></>}</div>{buckets.length>0&&<div className="codex-limits">{buckets.map((limit,index)=><RateLimitCard key={limit.limitId||index} limit={limit}/>)}</div>}{days.length>0&&<div className="codex-usage-chart" aria-label="近期每日 Token 用量"><h4>近期每日 Token</h4><div>{days.map(day=><span key={day.startDate} title={`${day.startDate} · ${number(day.tokens)} tokens`}><i style={{height:`${Math.max(4,(Number(day.tokens)||0)/peak*100)}%`}}/><small>{day.startDate.slice(5)}</small></span>)}</div></div>}{error&&<p className="omega-error" role="status">{unsupported?'当前使用 API Key 或 Bedrock 认证，Codex 不提供 ChatGPT 账户额度与用量。':error}</p>}{!error&&!buckets.length&&!summary&&!unsupported&&<p className="omega-empty">当前账户没有返回可展示的额度或用量数据。</p>}</section>;
}

export function SystemPanel(){
  const restoreInput=useRef<HTMLInputElement>(null);
  const [health,setHealth]=useState<Health|null>(null),[account,setAccount]=useState<Account|null>(null),[limits,setLimits]=useState<Limits|null>(null),[usage,setUsage]=useState<Usage|null>(null),[accountError,setAccountError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const refreshHealth=async()=>{try{setHealth(await window.omegaProductApi?.<Health>('health')||null)}catch(error){setNotice(error instanceof Error?error.message:String(error))}};
  const refreshAccount=async()=>{setAccountError('');const results=await Promise.allSettled([rpc<{account:Account|null}>('account/read',{refreshToken:false}),rpc<Limits>('account/rateLimits/read'),rpc<Usage>('account/usage/read')]);if(results[0].status==='fulfilled')setAccount(results[0].value.account);if(results[1].status==='fulfilled')setLimits(results[1].value);else setLimits(null);if(results[2].status==='fulfilled')setUsage(results[2].value);else setUsage(null);const failures=results.filter(result=>result.status==='rejected') as PromiseRejectedResult[];if(failures.length)setAccountError(failures.map(result=>result.reason instanceof Error?result.reason.message:String(result.reason)).filter((value,index,all)=>all.indexOf(value)===index).join('；'))};
  const refresh=async()=>{await Promise.all([refreshHealth(),refreshAccount()])};
  useEffect(()=>{void refresh();const healthTimer=setInterval(refreshHealth,5000),accountTimer=setInterval(refreshAccount,60000);return()=>{clearInterval(healthTimer);clearInterval(accountTimer)}},[]);
  const run=async(action:'restartCodex'|'restartOmega')=>{setBusy(true);setNotice('');try{const result=await window.omegaProductApi?.<{message:string}>('system',{action});setNotice(result?.message||'操作已提交');setTimeout(refreshHealth,800)}catch(error){setNotice(error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
  const restore=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file||!confirm('恢复会替换 Omega 的群组、自动化、附件、索引和设置，访问密钥保持不变。继续吗？'))return;setBusy(true);try{const result=await window.omegaSystem?.restore(file);setNotice(`备份已校验并暂存（${result?.files||0} 个文件），请重启 Omega 完成恢复。`);await refreshHealth()}catch(error){setNotice(error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
  return <div className="omega-system"><div className="omega-center-section-title"><div><h3>服务健康与数据</h3><p>查看服务状态、安全备份并执行受控重启。</p></div><button onClick={()=>void refresh()}>刷新</button></div>{notice&&<p className="omega-center-notice">{notice}</p>}{health?<div className="omega-health-grid"><article><strong>{health.status==='healthy'?'运行正常':'服务降级'}</strong><p>Omega {health.version} · 已运行 {duration(health.uptimeSeconds)}</p><small>启动于 {new Date(health.startedAt).toLocaleString()}</small></article><article><strong>Codex App Server</strong><p>{health.bridge.ready?'已连接':'正在恢复'} · PID {health.bridge.pid||'—'}</p><small>{health.bridge.pendingRequests} 个请求 · {health.bridge.pendingApprovals} 个审批</small></article><article><strong>资源</strong><p>RSS {size(health.memory.rss)} · Heap {size(health.memory.heapUsed)}</p><small>{health.devices} 台设备 · {health.activeTurns} 个执行中轮次</small></article><article><strong>恢复状态</strong><p>{health.pendingRestore?'备份等待重启恢复':'没有待恢复备份'}</p><small>{health.supervised?'守护运行，可在线重启':'直接运行，需在终端重启'}</small></article></div>:<p className="omega-empty">正在读取健康状态…</p>}<CodexUsage account={account} limits={limits} usage={usage} error={accountError}/><div className="omega-system-actions"><button disabled={busy} onClick={()=>void window.omegaSystem?.backup()}>下载数据备份</button><button type="button" disabled={busy} onClick={()=>restoreInput.current?.click()}>选择备份恢复</button><input ref={restoreInput} aria-label="备份文件" type="file" accept=".gz,.omega-backup.gz,application/gzip" hidden disabled={busy} onChange={restore}/><button disabled={busy} onClick={()=>void run('restartCodex')}>重启 Codex App Server</button><button disabled={busy||!health?.supervised} onClick={()=>void run('restartOmega')}>重启 Omega</button></div><p className="omega-system-help">备份不包含访问密钥。恢复采用“校验 → 暂存 → 重启应用”的安全流程，执行前必须停止正在运行或等待审批的任务。</p></div>;
}
