import {useEffect,useState,useRef} from 'react';

interface Health{status:string;version:string;startedAt:string;uptimeSeconds:number;memory:{rss:number;heapUsed:number;heapTotal:number};bridge:{ready:boolean;pid:number|null;pendingRequests:number;pendingApprovals:number};devices:number;activeTurns:number;pendingRestore:boolean;supervised:boolean}
const size=(value:number)=>(value/1024/1024).toFixed(1)+' MB';
const duration=(seconds:number)=>{const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);return hours?`${hours} 小时 ${minutes} 分钟`:`${minutes} 分钟`;};
export function SystemPanel(){
  const restoreInput=useRef<HTMLInputElement>(null);
  const [health,setHealth]=useState<Health|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const refresh=async()=>{try{setHealth(await window.omegaProductApi?.<Health>('health')||null)}catch(error){setNotice(error instanceof Error?error.message:String(error))}};
  useEffect(()=>{void refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer)},[]);
  const run=async(action:'restartCodex'|'restartOmega')=>{setBusy(true);setNotice('');try{const result=await window.omegaProductApi?.<{message:string}>('system',{action});setNotice(result?.message||'操作已提交');setTimeout(refresh,800)}catch(error){setNotice(error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
  const restore=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file||!confirm('恢复会替换 Omega 的群组、自动化、附件、索引和设置，访问密钥保持不变。继续吗？'))return;setBusy(true);try{const result=await window.omegaSystem?.restore(file);setNotice(`备份已校验并暂存（${result?.files||0} 个文件），请重启 Omega 完成恢复。`);await refresh()}catch(error){setNotice(error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
  return <div className="omega-system"><div className="omega-center-section-title"><div><h3>服务健康与数据</h3><p>查看服务状态、安全备份并执行受控重启。</p></div><button onClick={()=>void refresh()}>刷新</button></div>{notice&&<p className="omega-center-notice">{notice}</p>}{health?<div className="omega-health-grid"><article><strong>{health.status==='healthy'?'运行正常':'服务降级'}</strong><p>Omega {health.version} · 已运行 {duration(health.uptimeSeconds)}</p><small>启动于 {new Date(health.startedAt).toLocaleString()}</small></article><article><strong>Codex App Server</strong><p>{health.bridge.ready?'已连接':'正在恢复'} · PID {health.bridge.pid||'—'}</p><small>{health.bridge.pendingRequests} 个请求 · {health.bridge.pendingApprovals} 个审批</small></article><article><strong>资源</strong><p>RSS {size(health.memory.rss)} · Heap {size(health.memory.heapUsed)}</p><small>{health.devices} 台设备 · {health.activeTurns} 个执行中轮次</small></article><article><strong>恢复状态</strong><p>{health.pendingRestore?'备份等待重启恢复':'没有待恢复备份'}</p><small>{health.supervised?'守护运行，可在线重启':'直接运行，需在终端重启'}</small></article></div>:<p className="omega-empty">正在读取健康状态…</p>}<div className="omega-system-actions"><button disabled={busy} onClick={()=>void window.omegaSystem?.backup()}>下载数据备份</button><button type="button" disabled={busy} onClick={()=>restoreInput.current?.click()}>选择备份恢复</button><input ref={restoreInput} aria-label="备份文件" type="file" accept=".gz,.omega-backup.gz,application/gzip" hidden disabled={busy} onChange={restore}/><button disabled={busy} onClick={()=>void run('restartCodex')}>重启 Codex App Server</button><button disabled={busy||!health?.supervised} onClick={()=>void run('restartOmega')}>重启 Omega</button></div><p className="omega-system-help">备份不包含访问密钥。恢复采用“校验 → 暂存 → 重启应用”的安全流程，执行前必须停止正在运行或等待审批的任务。</p></div>;
}
