import {useEffect,useMemo,useRef,useState} from 'react';
import {appStore,type WorkPanel,useAppState} from './AppState.js';
import {ApprovalCard} from './ApprovalPanel.js';
import {repositoryDiffLines} from '../../src/shared/repository-diff.js';
import {ProjectEntry} from './ProjectPanel.js';

const api=async<T=any>(route:string,data?:unknown):Promise<T>=>{if(!window.omegaProductApi)throw Error('尚未连接');return window.omegaProductApi<T>(route,data);};
type Attention={id:string;kind:string;request?:any;groupId?:string;requirementId?:string;taskId?:string;threadId?:string;memberName?:string;groupName?:string;title?:string;decision?:any;pauseKind?:string;updatedAt?:string;automationId?:string;status?:string;error?:string};
export function WorkPanelEntry(){
  const app=useAppState(),[panel,setPanel]=useState<WorkPanel|null>(null),[total,setTotal]=useState<number|null>(null),dialog=useRef<HTMLDialogElement>(null),actions=useMemo(()=>({open:(next:WorkPanel)=>setPanel(next)}),[]);
  useEffect(()=>{appStore.patch({workPanelActions:actions});return()=>{if(appStore.getSnapshot().workPanelActions===actions)appStore.patch({workPanelActions:null})}},[actions]);
  useEffect(()=>{let alive=true,busy=false;const refresh=async()=>{if(busy||!app.authenticated||document.hidden)return;busy=true;try{const page=await api('attention?summary=1');if(alive)setTotal(page.total??0);}catch{if(alive)setTotal(null);}finally{busy=false;}};void refresh();const timer=setInterval(refresh,10000);window.addEventListener('focus',refresh);window.addEventListener('omega:attention-changed',refresh);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('omega:attention-changed',refresh)}},[app.authenticated]);
  useEffect(()=>{if(!panel||panel==='project')return;const previous=document.activeElement as HTMLElement;dialog.current?.showModal();return()=>{dialog.current?.close();if(previous?.isConnected)previous.focus();}},[panel]);
  return <><ProjectEntry open={panel==='project'} onOpen={()=>setPanel('project')} onClose={()=>setPanel(null)}/><button type="button" className="work-entry" disabled={!app.authenticated} onClick={()=>setPanel('attention')}>待处理{total!==null?` ${total}`:''}</button><button type="button" className="work-entry" disabled={!app.authenticated} onClick={()=>setPanel('repository')}>变更</button>
    {panel&&panel!=='project'&&<dialog ref={dialog} className="work-dialog" aria-label={panel==='attention'?'需要你处理':'仓库变更'} onCancel={event=>{event.preventDefault();setPanel(null)}}><header><h2>{panel==='attention'?'需要你处理':'仓库变更'}</h2><button type="button" aria-label="关闭工作面板" onClick={()=>setPanel(null)}>×</button></header>{panel==='attention'?<AttentionPanel onCount={setTotal} close={()=>setPanel(null)}/>:<RepositoryPanel close={()=>setPanel(null)}/>}</dialog>}
  </>;
}
function AttentionPanel({onCount,close}:{onCount:(n:number)=>void;close:()=>void}){
  const app=useAppState(),[page,setPage]=useState<{items:Attention[];total:number}>({items:[],total:0}),[offset,setOffset]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
  const refresh=()=>{setRevision(n=>n+1);window.dispatchEvent(new Event('omega:attention-changed'));};
  useEffect(()=>{let alive=true,loading=false;const load=async()=>{if(loading||document.hidden)return;loading=true;try{const result=await api(`attention?offset=${offset}`);if(alive){setPage({items:result.items||[],total:result.total||0});onCount(result.total||0);setError('');}}catch(e){if(alive)setError(String(e));}finally{loading=false;}};void load();const timer=setInterval(load,5000);return()=>{alive=false;clearInterval(timer)}},[offset,revision]);
  const action=async(work:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);refresh();}};
  const decision=async(item:Attention)=>{await window.omegaDialogs?.open('decision',{memberName:item.memberName,decision:item.decision,onSubmit:async(values:Record<string,unknown>)=>{try{await api('groups',{action:'resolveDecision',groupId:item.groupId,taskId:item.taskId,requirementId:item.requirementId,...values,view:'room'});}finally{refresh();}}});};
  const budget=async(item:Attention)=>{const result=await api(`groups/${encodeURIComponent(item.groupId!)}?requirementId=${encodeURIComponent(item.requirementId!)}`);await window.omegaDialogs?.open('budget',{requirement:result.group.requirement,onSubmit:async(values:Record<string,unknown>)=>{await api('groups',{action:'setBudget',groupId:item.groupId,requirementId:item.requirementId,maxRounds:Number(values.maxRounds),maxMinutes:Number(values.maxMinutes),maxTokens:Number(values.maxTokens),expectedUpdatedAt:item.updatedAt,view:'room'});refresh();}});};
  return <div className="work-body"><p>只显示需要决策、审批或恢复的事项；正常完成无需验收。每 5 秒刷新。</p><button onClick={refresh}>刷新</button>{error&&<p role="alert">{error}</p>}{!page.items.length&&!error&&<p>当前页没有待处理事项。</p>}
    {page.items.map(item=><section className="work-card" key={item.id}>{item.kind==='automation'?<><small>自动化 · {item.status==='unknown'?'结果待核对':'失败'}</small><h3>{item.title}</h3><p>{item.error}</p><div className="work-actions">{item.status==='unknown'&&<button disabled={busy} onClick={()=>void action(()=>api('automations',{action:'reconcile',id:item.automationId}))}>核对原轮次</button>}<button onClick={()=>{close();void window.omegaNavigation?.openThread(item.threadId!)}}>打开原会话</button></div></>:item.kind==='approval'?<><small>会话：{app.threads.find(t=>t.id===item.request?.params?.threadId)?.name||item.request?.params?.threadId||'待确认来源'}</small><ApprovalCard request={item.request} actions={{resolve:async(id,result)=>{try{await api('answer',{id,result})}finally{refresh()}},report:setError}}/></>:<><small>{item.groupName} {item.memberName?`· ${item.memberName}`:''}</small><h3>{item.decision?.title||item.title}</h3><p>{item.decision?.question||(item.pauseKind==='budget'?'等待追加预算':item.pauseKind==='recovery'?'执行结果待核对，不会直接重发任务':'执行异常，重试不会回滚已有修改')}</p><div className="work-actions">
      {item.kind==='decision'?<button disabled={busy} onClick={()=>void action(()=>decision(item))}>选择方案</button>:item.pauseKind==='budget'?<button disabled={busy} onClick={()=>void action(()=>budget(item))}>调整预算</button>:<button disabled={busy} onClick={()=>{if(item.pauseKind==='recovery'||confirm('重新执行失败任务？已有文件修改不会回滚，请先核对结果。'))void action(()=>api('groups',{action:'retry',groupId:item.groupId,requirementId:item.requirementId,expectedUpdatedAt:item.updatedAt,view:'room'}));}}>{item.pauseKind==='recovery'?'核对原执行':'重试失败任务'}</button>}
      <button onClick={()=>{close();void app.groupActions?.open(item.groupId!)}}>打开群组</button></div></>}</section>)}
    <div className="work-actions"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-30))}>上一页</button><span>共 {page.total} 项</span><button disabled={offset+30>=page.total} onClick={()=>setOffset(offset+30)}>下一页</button></div></div>;
}
function RepositoryPanel({close}:{close:()=>void}){
  const [repository,setRepository]=useState<string|undefined>();
  const app=useAppState(),[threadId,setThread]=useState(app.mode==='chats'?app.threadId||'':''),[scope,setScope]=useState('unstaged'),[offset,setOffset]=useState(0),[data,setData]=useState<any>(null),[file,setFile]=useState(''),[diff,setDiff]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),preview=useRef<HTMLPreElement>(null);
  useEffect(()=>{let alive=true;setData(null);setFile('');setDiff('');setError('');setLoading(false);if(!threadId)return;setLoading(true);void api('repository',{threadId,scope,offset,repository}).then(result=>{if(alive)setData(result)}).catch(e=>{if(alive)setError(e instanceof Error?e.message:String(e))}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[threadId,scope,offset,repository,revision]);
  useEffect(()=>{let alive=true;setDiff('');if(!file)return;void api('repository',{threadId,scope,file,repository:data?.repository??repository}).then(result=>{if(alive)setDiff(result.diff||'暂无可显示差异')}).catch(e=>{if(alive)setError(e instanceof Error?e.message:String(e))});return()=>{alive=false}},[file,threadId,scope,repository,revision]);
  const quote=async()=>{const selection=window.getSelection(),text=selection?.anchorNode&&preview.current?.contains(selection.anchorNode)&&selection.focusNode&&preview.current?.contains(selection.focusNode)?selection.toString():'';const quoted=`请查看仓库 ${data?.root||''} 中的文件 ${file}：\n${text.slice(0,12000)||'请结合当前工作区的改动继续分析。'}`;try{await window.omegaNavigation?.openThread(threadId);close();const editor=document.getElementById('prompt');if(editor){editor.focus();const range=document.createRange();range.selectNodeContents(editor);range.collapse(false);selection?.removeAllRanges();selection?.addRange(range);document.execCommand('insertText',false,`\n${quoted}\n`);}}catch(e){setError(String(e));}};
  return <div className="work-body">
    <p>只读展示仓库当前变化，可能包含你或其他会话的修改，不代表全部由本次任务产生。</p>
    <div className="work-actions">
      <select aria-label="变更所属会话" value={threadId} onChange={e=>{setThread(e.target.value);setRepository(undefined);setFile('');setOffset(0)}}><option value="">选择会话</option>{app.threads.map(t=><option key={t.id} value={t.id}>{t.name||t.preview||t.id}</option>)}</select>
      <select aria-label="变更范围" value={scope} onChange={e=>{setScope(e.target.value);setFile('');setOffset(0)}}><option value="unstaged">未暂存 / 未跟踪</option><option value="staged">已暂存</option></select>
      <button onClick={()=>{setFile('');setRevision(n=>n+1)}}>刷新</button>
    </div>
    {data?.directory&&<p>会话工作目录：{data.directory}</p>}
    {!!data?.repositories?.length&&<div className="work-actions"><select aria-label="项目仓库" value={data.repository||''} onChange={e=>{setRepository(e.target.value||undefined);setFile('');setOffset(0)}}><option value="">请选择项目仓库</option>{data.repositories.map((r:any)=><option key={r.id} value={r.id}>{r.name}{r.id==='.'?'（当前目录）':''}</option>)}</select></div>}
    {data?.truncated&&<p role="note">仅检查当前目录的前 200 个条目，未递归扫描。未列出的项目请切换到对应仓库会话。</p>}
    {data?.message&&<p role="status">{data.message}</p>}
    {error&&<p role="alert">{error} <button onClick={()=>{setRepository(undefined);setOffset(0);setFile('');setRevision(n=>n+1)}}>重新选择仓库</button></p>}
    {loading&&<p>正在读取…</p>}
    {data?.root&&<><p className="repository-location">{data.root} · {data.branch} · {data.total} 个文件</p><div className="repository-layout"><nav aria-label="改动文件">{data.files.map((item:any)=><button type="button" className="repository-file" key={item.path} title={item.path} aria-pressed={file===item.path} onClick={()=>{setFile(item.path);setError('')}}><span className="repository-file-status">{({M:'修改',A:'新增',D:'删除','?':'未跟踪'} as Record<string,string>)[item.status]||item.status}</span><span className="repository-file-path">{item.path}</span></button>)}</nav><section>{file&&<><div className="repository-file-heading"><strong>{file}</strong><button onClick={()=>void quote()}>引用文件 / 选中片段追问</button></div><div className="repository-diff-legend"><span data-kind="added">新增</span><span data-kind="removed">删除</span><span>行号：原文件 / 新文件</span></div><pre ref={preview} className="repository-diff" aria-label="文件变更内容">{diff?repositoryDiffLines(diff).map((line,index)=><span key={index} className={`repository-diff-line is-${line.kind}`}><span className="repository-line-number" data-line={line.oldLine??''} aria-hidden="true"/><span className="repository-line-number" data-line={line.newLine??''} aria-hidden="true"/><span className="repository-line-code">{line.text||' '}{'\n'}</span></span>):'正在读取差异…'}</pre></>}</section></div><div className="work-actions"><button disabled={!offset} onClick={()=>{setFile('');setOffset(Math.max(0,offset-50))}}>上一页</button><button disabled={data.nextOffset===null} onClick={()=>{setFile('');setOffset(data.nextOffset)}}>下一页</button></div></>}
  </div>;
}
